### ISSUE TITLE
Bug Reporter "How to report" tab 

### ISSUE THREAD

**Issue by GadgetSteve** [wxGlade/wxGlade#312]
The "how to report a bug" tab of the bug reporter references https://sourceforge.net/p/wxglade/bugs/ rather than https://github.com/wxGlade/wxGlade/issues which is the current location. I am not sure if the mailing list is also incorrect.

Glade version v0.8.0

**Comment by GadgetSteve** [comment]
![image](https://user-images.githubusercontent.com/5593690/37959979-4cad98a0-31ac-11e8-9eeb-e0622e4fe40c.png)

Shows the issue.

**Comment by DietmarSchwertberger** [comment]
Thanks. I missed this one as I usually run under a debugger and so never reach the dialog.
It's updated in the repository now.

**Comment by DietmarSchwertberger** [comment]
Fixed with 0.8.1 (see https://github.com/wxGlade/wxGlade/releases )
