### ISSUE TITLE
Can't define a top panel if it is defined as a custom widget

### ISSUE THREAD

**Issue by jabozzo** [wxGlade/wxGlade#314]
I want to be able to define my own widgets derived from Panel in the same file as the rest of my application's frames. But depending on the order of the operations wxGlade won't let me proceed.

To reproduce:
- Create a new application, add a frame to it.
- Put in the frame a custom widget with class 'Foo'.
- Click Add a Panel/Dialog specify its class as 'Foo'. The textbox will turn yellow and you will not be able to procceed.

Workaround:
Doing the reverse works,
- Create a new application, add a frame to it.
- Click Add a Panel/Dialog, create a Panel with class 'Foo'
- Put in the frame a custom widget with class 'Foo'.

I don't know if for Dialog it has some sense to let it pass as a custom widget. But for Panel it definitively does!

**Comment by DietmarSchwertberger** [comment]
Could you please test release 0.8.1 from https://github.com/wxGlade/wxGlade/releases ?

**Comment by jabozzo** [comment]
I've tested it and it works. It still warns yellow but now let's me click on OK.
