### ISSUE TITLE
Custom classes sometimes shown next to name, sometimes not.

### ISSUE THREAD

**Issue by jabozzo** [wxGlade/wxGlade#315]
This looks like a very petty bug. I hope it doesn't have some implications under the hood.

To reproduce:
1. Create a new application.
2. Add a frame with a sizer of 3 slots.
3. Add to the first slot a custom widget with class 'Foo'. Only it's name will appear in the application tree.
4. Add to the second slot a custom widget with class 'Foo'. Again, only it's name will appear in the application tree.
5. Change the class name of the second custom widget to 'Spam', now Spam appears next to the name of this widget in the application tree.
6. Add a third custom widget to the last slot and have its class be 'Spam'. This widget does not have it's class name displayed in the application tree but the second control still does.
7. Change the class name of the third widget to 'Foo'. Now the class name will appear in the application tree. Also, in the properties window of that widget, the class field will be yellow.
8. Change back the class names of widget 2 and 3 to 'Foo' and 'Spam' respectively and the class names next to the widget name will disappear in the application tree.

So far I've not noticed any bugs in the generated code. \<opinion\> So I don't think it would bother anyone if it sinks in priority if it's just a visual thing. \</opinion\>

![step_7](https://user-images.githubusercontent.com/9649979/38277985-aa4967b8-3770-11e8-928d-0986ff6113aa.png)
Image of step 7

Sidenote:
I would like to thank the developer for maintaining this tool. It's so useful.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. There was a bug in the label generation code. I have also modified the code not to suggest CustomWidget0 if CustomWidget is in use already.
