### ISSUE TITLE
Problem with AllWidgets_30.wxg

### ISSUE THREAD

**Issue by Alchemist45** [wxGlade/wxGlade#316]
When I try to show design window in wxglade with AllWidgets_30.wxg using python 3.6  wxglade crashes. The AllWidgets_28.wxg works.

**Comment by DietmarSchwertberger** [comment]
What OS and wxPython version do you have?
On Windows with 4.0.1 things seem to work fine.

**Comment by Alchemist45** [comment]
Windows 10, python 3.6 from Anaconda, wxpython 3.0.  Do I need to upgrade to wxpython 4.01?

Thanks,

Scott

**Comment by DietmarSchwertberger** [comment]
Yes, please try with 4.0.1.

Usually wxPython 3 does not work with Python 3.6.
Either this is a pre-release of wxPython Phoenix when it had the 3 revision number from wxWidgets or it's something very, very special to Anaconda.
The wxPython Phoenix version number was set to 4.x only very late to differentiate it from Classic which is typically 2.8.x or 3.0.2.

**Comment by Alchemist45** [comment]
Thanks.  The AllWidgets_30.wsg now displays and outputs useful python code that runs just fine.

 

Regards,

Alchemist45

**Comment by DietmarSchwertberger** [comment]
Fine. Please give feedback if you observe issues in the documentation or program.
