### ISSUE TITLE
Error when try to delete item from toolbar editor

### ISSUE THREAD

**Issue by DamirKh** [wxGlade/wxGlade#318]
First, thanks for great tool!
If i try to delete item from toolbar editor I have got an error:
=========================================================
Exception type:      <class 'AttributeError'>
Exception details:   'ToolsDialog' object has no attribute 'item_level'

Application stack traceback:
  File "/home/damir/bin/wxGlade/widgets/toolbar/toolbar.py", line 364, in remove_item
    if index<self.items.GetItemCount() and (self.item_level(self.selected_index) < self.item_level(index)):

Date and time:       2018-05-04T08:37:01.101002
Python version:      3.5.3
wxPython version:    4.0.1
wxWidgets platform:  __WXGTK__
wxGlade version:     0.8.0
======================================================

Screenshot and wxg attached.
![screenshot from 2018-05-04 08-48-14](https://user-images.githubusercontent.com/25591489/39613473-7b04b38e-4f78-11e8-9cbe-30c02bdeaf13.png)

[data_conf.zip](https://github.com/wxGlade/wxGlade/files/1973306/data_conf.zip)

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. Seems that I did not test after copying some code from the menu editor to the toolbar editor.
A fix is in the repository. Please try out https://github.com/wxGlade/wxGlade/releases/tag/v0.8.2

**Comment by DietmarSchwertberger** [comment]
Release 0.8.2 uploaded to the project download page.
