### ISSUE TITLE
No scrolling in properties window

### ISSUE THREAD

**Issue by lamarc5** [wxGlade/wxGlade#319]
Screen properties window - No vertical scrolling - Horizontal scroll show as vertical
If the properties window is too short to show everything, there is no way to access information hidden at the bottom: no scroll bar, mouse wheel doesn't scroll the window. When we decrease properties window width, a -vertical- scroll control appears but has no effect.
Vertical scroll bar is shown/hidden when we change window width; horizontal scroll bar is never shown.

wxGlade 0.8.1
wxWidgets 3.0.1
python 3.6.5
cinnamon 3.6.7 desktop
also tested on gnome 3.28.1
ubuntu 18.04
amd64 processor
screen 1280 x 800
also tested 960x600

**Comment by DietmarSchwertberger** [comment]
I will look into this. gtk 3 seems to behave different from gtk 2 and Windows...

**Comment by DietmarSchwertberger** [comment]
I have just uploaded a fix. Could you please try it (branch REV_0.8)?
If you did not clone the repository, the easiest way is to download the zip or tar archive:
https://api.github.com/repos/wxGlade/wxGlade/zipball/REV_0.8
https://api.github.com/repos/wxGlade/wxGlade/tarball/REV_0.8
Unfortunately, there seems to be no way to get rid of the gtk assertion messages about sizes <=0.

Revision 0.9 will have an improved user interface with all threee windows merged into one with switchable layouts. The most relevant changes are in the master branch already.

**Comment by lamarc5** [comment]
The properties values start hidden at the left; they show if we widen the properties window. Vertical scroll bar doesn't work on displayed grid and neither on the properties windows (attached screenshot).
Displayed on start:
![first](https://user-images.githubusercontent.com/39003357/39854099-132cf58e-53f4-11e8-8c23-1927e01018dc.jpg)
After partial horizontal expanding:
![rightexpanded](https://user-images.githubusercontent.com/39003357/39854118-27396012-53f4-11e8-87c0-c8bac7d97a92.jpg)
Fully expanded window ie no scroll bars:
![fullexpanded](https://user-images.githubusercontent.com/39003357/39854137-3d39c316-53f4-11e8-903a-4f2014f4236d.jpg)
Reduced height:
![halfheight](https://user-images.githubusercontent.com/39003357/39854185-8186895a-53f4-11e8-9112-f7e6f26d5d59.jpg)

**Comment by DietmarSchwertberger** [comment]
OK, I have just installed Cinnamon and see the problems there.

**Comment by lamarc5** [comment]
It is usable now: I can access all parts of the window properties. It still has abnormal scroll controls when resizing to a narrow window; horizontal and vertical scroll bar are displayed in the inner widget. The inner vertical scroll does not work.
![narrow](https://user-images.githubusercontent.com/39003357/39897771-cb8bf020-5481-11e8-9e85-3cddc1324cd4.jpg)

**Comment by DietmarSchwertberger** [comment]
Grids inside sizers are always a bit difficult, as there is not much of an automatism.
I will give it a try next week whether I can at least ensure that the vertical size of the grid is always big enough such that only the outer scroll bar is required. I will probably not do much about the horizontal scrolling as I don't see how anyone would work with such a narrow view. The new user interface (in the master branch) is a bit more flexible here as it allows to switch between different layouts easily.

**Comment by DietmarSchwertberger** [comment]
I have just added a commit to completely avoid scroll bars on grid properties. This is probably the best behaviour we can get. Please try. It's in REV_0.8 and master.

**Comment by DietmarSchwertberger** [comment]
Release 0.8.2 uploaded to the project download page.
