### ISSUE TITLE
 Display custom widgets defined in the same project

### ISSUE THREAD

**Issue by jabozzo** [wxGlade/wxGlade#321]
Suggestion: Display custom widgets defined in the same project. For example, if you create a custom panel with class A and then a window B that instances a custom widgets with class A. Then the instances are displayed in the preview and design windows of B.

Image attached to clarify.

![tmp](https://user-images.githubusercontent.com/9649979/40678430-88b341aa-634e-11e8-9c37-3d5ae9aed86d.png)

**Comment by DietmarSchwertberger** [comment]
I will think about this. It could have many side effects due to called code or event handling, so by default it would not be a good idea to have this. Maybe it's possible to add two flags "show in design window" and "show in preview windows" to the creation dialog and the property editor.

**Comment by jabozzo** [comment]
I agree that would be a bad idea to not have the option to turn it on/off.

In the case of the design window, from the user-experience perspective, I think that the child widget should not respond to any mouse event but instead simply select the custom widget. Otherwise selecting the widget will be a pain.

**Comment by DietmarSchwertberger** [comment]
Yes, but for a custom widget one cannot rely on `custom_widget.Bind(wx.EVT_MOUSE_EVENTS...)` or `custom_widget.GetChildren()`.
It's difficult enough for some other widgets already, like the ComboBox.
Probably I need to check that the custom widget has the `GetChildren` method even if it's not derived from `wx.Window`.

**Comment by DietmarSchwertberger** [comment]
Besides custom widget, it's also possible to change the `class` property of e.g. a Button to use an own implementation or an implementation from `wx.lib` like `wx.lib.buttons.GenButton`.

I think I will implement the design and preview mechanism for this as well.
I won't do this for 0.9, though. I would like to fix some internals about `class`, `custom_class` and `custom_base` first and this is out of scope for 0.9.

**Comment by DietmarSchwertberger** [comment]
I have just uploaded an experimental version as branch ISS321_CUSTOM_WIDGETS.
I'm not yet sure whether it would be a good idea to add this to the master branch.
The implementation is very fragile.

**Comment by DietmarSchwertberger** [comment]
Took some time, but now a first version is in the master branch:

![grafik](https://user-images.githubusercontent.com/5512021/104962511-dd90e280-59d8-11eb-804d-31a4c78f5a8f.png)

**Comment by DietmarSchwertberger** [comment]
pre-release 1.1.0a1 is online now
