### ISSUE TITLE
wxWrapSizer include file for C++ gen

### ISSUE THREAD

**Issue by BrendanSimon** [wxGlade/wxGlade#322]
Generated C++ code does not compile when using wxWrapSizer (when wrap checkbox is set) as the associated include file is missing.

Need to add `#include <wx/wrapsizer.h>` to the generated sources.

**Comment by DietmarSchwertberger** [comment]
Thanks. A fix is in the master branch now.

**Comment by BrendanSimon** [comment]
Didn't seem to make to the tagged `v0.8.3` release.  I see it in the `master` branch, but not in the tag `v0.8.3` on the `REV_0.8` branch.

Just thought I'd mention it as the above message indicates the issue was added to the `0.8.3` milestone.

**Comment by DietmarSchwertberger** [comment]
Sorry, that was a mistake. WrapSizer is 0.9 only.
