### ISSUE TITLE
wxglade script doesn't support Python 3

### ISSUE THREAD

**Issue by swt2c** [wxGlade/wxGlade#324]
The wxglade script (that gets installed to /usr/bin when using setup.py) doesn't support Python 3.

This script could probably just be replaced by using entry_points in setuputils.

**Comment by Moriand** [comment]
Hi, open wxglade.py  with IDLE Python and execute since the IDLE

**Comment by swt2c** [comment]
I'm not referring to 'wxglade.py' (which works fine with Python 3) but 'wxglade' bash script.

**Comment by DietmarSchwertberger** [comment]
As the script would pick any interpreter instead of the one that was being used, it's probably not too useful.
I'm not sure how to handle this. My experience with Linux and setuputils is almost zero...

**Comment by DietmarSchwertberger** [comment]
I have just modified the script to search for Python 3 first.
The script tries to install wxGlade into site-packages. This is something that I don't find useful at all. A development tool has not to install itself into the target installation.
Maybe it would be best to drop it completely.

**Comment by Moriand** [comment]
hi @DietmarSchwertberger There are some details that you want to add, for example wx.aui

**Comment by DietmarSchwertberger** [comment]
@Moriand : That's rather unlikely. I don't see much of an intersection of the types applications that use profit from wx.aui and the ones that are generated by a GUI builder. I have not had the need to use wx.aui within almost 20 years of wxPython usage.
But I also don't see how this is related to issue #324.

**Comment by Moriand** [comment]
@DietmarSchwertberger Ah, sorry, the problem was that it can not be installed and what I said was just a suggestion to the application in general

**Comment by DietmarSchwertberger** [comment]
I have updated the script to support Python 3. It should be extended to check whether wxGlade is really available for the tested version.

**Comment by DietmarSchwertberger** [comment]
The check for Python 3 is in and will be part of 0.9.0.
The check whether wxGlade is really available for this version is beyond my shellscript capabilities...

**Comment by DietmarSchwertberger** [comment]
in 0.9.0b1
