### ISSUE TITLE
After insertion of a separator in the Menu editor, a faulty event handler is generated.

### ISSUE THREAD

**Issue by Slechtvalk** [wxGlade/wxGlade#326]
In the menu editor a separator can be inserted between menus.

This results the XML into this :

```
<item>
 <label>---</label>
 <name>---</name>
 <handler>---</handler>                 
</item>
```

The entry " <handler>---</handler>       " is wrong and should not be there.

A corresponding event handler is generated that does not make sense  
`void ---(wxCommandEvent &event); // wxGlade: <event_handler>`

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. I introduced this but when modifying the menu editor to have column ordering "Label", "Handler" as "Id" is usually no longer required.
As it happens only when editing, the older test cases were OK and the only new test case was done with the new editor...
A fix is in the repository now (branch master). Please test.

**Comment by DietmarSchwertberger** [comment]
0.9.0a1 is available
