### ISSUE TITLE
GridBagSizer growable last column

### ISSUE THREAD

**Issue by BrendanSimon** [wxGlade/wxGlade#327]
I have a GridBagSizer with 1 row and 4 columns.  Columns 2 and 3 have a button.  Columns 1 and 4 are set to growable and (should) act like spacers, so the buttons are always together in the horizontal centre of the window.

The first col expands, but the forth column does not, and two buttons are anchored to the RHS of the window.

If I set only one growable column (column 4), then the two buttons stay anchored to the LHS (which is normal behaviour if now growable columns are set).

If I place a button in the empty slot at column 4, then columns 1 and 4 expand correctly.

If place a spacer at column 4 instead of a button, I get an exception, regardless of whether growable columns is set or not.

```
ERROR   : An internal error occurred while Generate Preview
An unexpected error occurred!

Exception type:      <class 'TypeError'>
Exception details:   GridBagSizer.Add(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'tuple'
  overload 2: argument 1 has unexpected type 'tuple'
  overload 3: argument 1 has unexpected type 'tuple'
  overload 4: argument 1 has unexpected type 'tuple'
  overload 5: argument 2 has unexpected type 'int'

Application stack traceback:
  File "/Users/brendan/Sandbox/wxglade_git/application.py", line 511, in preview
    frame = preview_class(None, -1, '')
  File "/Users/brendan/app.py", line 22, in __init__
    self.__do_layout()
  File "/Users/brendan/app.py", line 39, in __do_layout
    grid_sizer_1.Add((20, 20), 0, 0, 0)

Date and time:       2018-07-09T00:25:58.505366
Python version:      3.6.5
wxPython version:    4.0.3
wxWidgets platform:  __WXMAC__
wxGlade version:     0.9.0pre
```
I hope that just having an empty slot in the last column should work ok.  It seems to work ok for the first column.

**Comment by DietmarSchwertberger** [comment]
This is quite a special use case. For this use case a horizontal sizer with two spacers is the common solution.

In wxWidgets the rows and cols are not explicitely set, but are created by adding items to cells.
So if no item is added to the fourth column, then this does not exist and therefore does not get extended (actually, `AddGrowableCol` will fail already).

Only in wxGlade a GridBagSizer has explicit rows and cols and slots as I don't know how to edit without...

As a GridBagSizer is not really supposed to contain spacers, this case has never been tested. I need to fix the code generation from
`grid_sizer_1.Add( (20, 20), 0, 0, 0)`
to
`grid_sizer_1.Add( 20, 20, (0,0), (1, 1), 0, 0)  # width, height, pos, span, flags, border`

Also, when creating the test case, I found a bug when creating grid sizers.

**Comment by DietmarSchwertberger** [comment]
A fix is in the master branch. Spacers should now be handled correctly.

**Comment by DietmarSchwertberger** [comment]
0.9.0a1 is available
