### ISSUE TITLE
wxGlade support for Centos/Red Hat/Scientific Linux

### ISSUE THREAD

**Issue by faitjx** [wxGlade/wxGlade#328]
I took the time to make python setup.py install work on Scientific Linux 7.5, which is binary compatible with Centos 7.5 and Red Hat Enterprise Linux 7.5.  I have attached the patch file for the changes, which add options to the path finding routines, and fixed a minor issue with the man files missing.  It is based off of the wxGlade-8.3.zip download.

I have been using wxGlade for over 15 years on various iterations of EL, always doing similar tweaks to get it installed.  I am in the process of going to a new version of the GUI that we use to control a large scientific instrument, that has been extremely well received by our outside users.  Thanks for the valuable tool that you have developed. 
[wxGlade.patch.txt](https://github.com/wxGlade/wxGlade/files/2174172/wxGlade.patch.txt)

J. Fait, Ph.D.

**Comment by DietmarSchwertberger** [comment]
Thanks a lot. I'm mainly on Windows and I did not like the fact too much that wxGlade installs itself into a Python installation via setup or egg, so I don't work too much on the installation scripts...
Recently I adjusted the wxglade shell script to work at least for Python 3.
I will review your modifications, but it will take a few days. They will for sure be in the next release.

**Comment by DietmarSchwertberger** [comment]
It's in the repository now.

**Comment by DietmarSchwertberger** [comment]
in 0.9.0b1
