### ISSUE TITLE
Deprecation warning issued : Constructor 'wxFont' is deprecated : use wxFONT(FAMILY,STYLE,WEIGHT}_XXX constants

### ISSUE THREAD

**Issue by Slechtvalk** [wxGlade/wxGlade#329]
wxGlade generates deprecated C++ code that uses the old wxFont calling conventions. Selecting a different font than the standard font is done in the "common" tab :

<img width="713" alt="schermafbeelding 2018-07-09 om 11 23 21" src="https://user-images.githubusercontent.com/8831731/42442378-cf1f65ba-836a-11e8-86d2-7a91b96a3f9c.png">

The resulting code is this :

<img width="737" alt="schermafbeelding 2018-07-09 om 11 23 56" src="https://user-images.githubusercontent.com/8831731/42442472-08984604-836b-11e8-8811-9e3ae6c35a84.png">

In wxWidgets 3.0, wxDEFAULT has become wxFONTFAMILY_DEFAULT and wxNORMAL has become either 
wxFONTSTYLE_NORMAL or wxFONTWEIGHT_NORMAL .

It is not a show stopper at the moment, but at some point the old enumerations will disappear.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. I will modify the code generation accordingly at some point in the near future (end of July or beginning of August).

**Comment by Slechtvalk** [comment]
O.K , danke sehr!

Ewout Boks

**Comment by DietmarSchwertberger** [comment]
I have just modified the code generation and added test cases. It's in the repository.
It seems the new constants were available in wxPython 2.8 already, but the modification is for >=3.0 only as I'm not sure about wxLISP and wxPERL.

**Comment by DietmarSchwertberger** [comment]
0.9.0a1 is available
