### ISSUE TITLE
Add possibility to not let automated build depend on user's local config

### ISSUE THREAD

**Issue by olofandersson2** [wxGlade/wxGlade#331]
When using wxGlade as part of an automated build system like this:
wxglade --generate-code=C++ layout.wxg

the output still depends on each user's config file
For example, if the user has enabled write_timestamp = True
then each class will be rebuilt (and if the files are in version control, they will show up as modified)

Steps to reproduce:
- A wxg file with "Separate file for each class" enabled
- "write_timestamp = True" in user's local config (~/.wxglade/wxgladerc)
- run wxglade as part of build system (something like: "wxglade --generate-code=C++ layout.wxg")

Actual result:
- all cpp/h files are changed with new string "generated by wxGlade 0.8.3 on Thu Aug 16 10:17:46 2018" and thus re-compiled

Expected result:
- local config should not affect automated build, OR:
- add a possibility to specify what wxgladerc will be used, (something like this: wxglade --use-config=path/to/wxgladerc  ...)

**Comment by DietmarSchwertberger** [comment]
I will look into this. Probably I will go for your second suggestion (supply a wxgladerc on the command line).

**Comment by DietmarSchwertberger** [comment]
I have just added an option: `-c`  or `--use-config`
I could not test it, though, as I would need to set up a test environment.
Please try whether it's working. If not, I will set up an environment and fix it.

**Comment by olofandersson2** [comment]
I tested it on master branch. The fix is working fine!

**Comment by olofandersson2** [comment]
Note: It does not give any warning if the file does not exist. if you point to a non-existing config file:
```python ~/wxGlade/wxglade.py --generate-code=C++ gui/layout.wxg --use-config=asdasgasdf```

it still says:
```INFO    : Configuration file:         asdasgasdf ```

but it seems to use some default settings, (I don't think it falls back to ~/.wxglade/wxgladerc either, because it generated some backup-files that I normally don't get)

Anyway, this is not a big problem as long as the config file exists.

**Comment by DietmarSchwertberger** [comment]
An error message will now be printed. For interactive usage, it would only be printed on the console, but that should not be a real problem.

**Comment by DietmarSchwertberger** [comment]
0.9.0a1 is available
