### ISSUE TITLE
Generating code from command line requires GUI

### ISSUE THREAD

**Issue by ardovm** [wxGlade/wxGlade#332]
Since commit 2036e33a349fe6bd6907b4a0b26021691002be17, that fixed issue #310, wxGlade needs to initialize the GUI in order to allow code generation.

This means that it is not possible to generate code in automated build environments that do not offer a X11 display.

    python wxglade.py -g python test.wxg
    INFO    : Starting wxGlade version "0.8.3" on Python 2.7.15.rc1
    ...
    Unable to access the X display, is $DISPLAY set properly?```

The above error message is displayed when instancing the `wxGlade` class, that is derived from `wx.App`.

**Comment by DietmarSchwertberger** [comment]
Actually, that has not been working for a longer time than the referenced commit.
This is a side effect when I modified the code generation.
Previously, the code generation was from an XML parser directly to code. Even for the loaded file, an XML representation was generated and then parsed and converted to code. Unfortunately, the code generator was a nightmare to maintain as the parser had no knowledge of the following structures. It's still complicated to maintain, but at least much easier than before. For relases >1.0 I would like to make things much more straightforward.

The current data structure is tied to the tree control that is used to display the Tree window and therefore `wxGladeFrame` and `wxGlade` are required. I want to get rid of this coupling and then it would be easier to load the file without initializing `wx.App`.
But this will probably only happen towards the end of the year.
So for now, I don't know how to address this. Did you try to fake the `DISPLAY` environment variable?

I have set the label to "wontfix" to keep it out of the way. If there's no workaround, please re-submit when the first alpha or beta versions for 1.0 will be available.

**Comment by DietmarSchwertberger** [comment]
Maybe you could try this one in edit_windows:
```
        if "font" in self.PROPERTIES:
            self._font_changed = False # this is True if the user has selected a custom font
            if config.use_gui:
                font = self._build_from_font( compat.wx_SystemSettings_GetFont(wx.SYS_DEFAULT_GUI_FONT) )
                font[1] = 'default'
            else:
                font = (9, 'default', 'normal', 'normal', 0, 'Segoe UI')
            self.font = np.FontPropertyD(tuple(font))
```

I would guess that not too many classes are querying such things, but I don't really know.
Unfortunately I don't have an easy way to use a headless Linux.
Maybe you can try some more steps and if it works, I will integrate your patches. That's probably the better option for you compared to waiting for months.

**Comment by DietmarSchwertberger** [comment]
Thanks a lot. Your PR is merged.

**Comment by DietmarSchwertberger** [comment]
0.9.0a1 is available
