### ISSUE TITLE
Extra code before/after not generated in C++

### ISSUE THREAD

**Issue by olofandersson2** [wxGlade/wxGlade#333]
When generating C++ output, it seems that the "Code to be inserted before" and "Code to be inserted after" have no effect.

**Steps to reproduce:**
Version: wxGlade 0.8.3.
Create a new project with language C++. Add a wxFrame, a sizer and a button. In the button settings enter custom code:
In "Extra (import) code for this widget", enter:

    #include <myfile>

In "Code to be inserted before", enter:

    foo();

In "Code to be inserted after", enter:

    bar();

Save project and generate sources.
I attached an example project in [gui.zip](https://github.com/wxGlade/wxGlade/files/2301849/gui.zip)

**Actual result:**
The extra code is not found in the generated C++ sources

**Expected result:**
The extra code is found in the generated C++ sources

**Note:**
If you instead of a wxFrame use a wxDialog, and for that _dialog_ also add something under  "Extra (import) code for this widget", then the dialog's include-code AND the button's include-code will show up the generated sources, which is all good, but it only works for the "include" code. The "before/after" code still does not appear.

**Comment by DietmarSchwertberger** [comment]
I have just uploaded a commit to the master branch that should fix both issues.
Please check whether it's working for you. Once you confirm, I will also add your file as test case.

**Comment by DietmarSchwertberger** [comment]
0.9.0a1 is available
