### ISSUE TITLE
Perl code generation: dependencies replaced incorrectly.

### ISSUE THREAD

**Issue by SueDNymme** [wxGlade/wxGlade#336]
**Summary:** Perl code generation, when using custom child widget classes (which introduce dependencies), generates incorrect code.  The first time the source is generated is fairly innocuous.  The second time creates a syntax error in the source file that prevents it from compiling/running.

**Version & Platform Info:**
* Windows 10 Pro, 64-bit, version 1703
* Python 3.6.2
* wxPython 4.0.3
* wxGlade 0.8.3

**Steps to reproduce:**
1. Start wxGlade.  In Application Properties, set:
    * Separate file for each class
    * Language: Perl
    * Keep user code: Yes
    * Output path: `C:\temp\wxGladeText`     _(e.g.)_
1. Add a frame to the application.  Leave its class name as MyFrame.
1. Add a Notebook control to the frame.
1. In Notebook Properties, set the class name to "MyNotebook".
1. Generate code for the project.
1. Look at the generated file `MyFrame.pm`.  Notice that there are some duplications.  At the top of the file, there's a "use Wx" line, a "use strict" line, and a "wxGlade: dependencies" section.  Then, below the "package MyFrame" line, there's another "use Wx" line (with a different import list), another "use strict" line, and another "wxGlade: dependencies" section.  This is not exactly an *error*; the program will run just fine this way, but it may be a clue to the next problem.
1. Go back into wxGlade.  Generate code again.
1. Look at `MyFrame.pm` again.  It's mostly the same, but the second "wxGlade: dependencies" section has been replaced with the line
`<153496587857908771602565wxGlade replace MyFrame dependencies>`
which is a syntax error, preventing the program from running.

**Workarounds:**
1. Delete `MyFrame.pm` before each time you generate code.
1. Manually remove one of the "wxGlade: dependencies" sections.  This seems to fix the problem longer-term.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting.
Of the two sections that are generated in the first run, which one is the one that is correct?
````
use Wx qw[:allclasses];
use strict;
# begin wxGlade: dependencies
use MyNotebook;
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package MyFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

# begin wxGlade: dependencies
use MyNotebook;
# end wxGlade
```

**Comment by DietmarSchwertberger** [comment]
Or is the one from a single file code generation the best one?
```
use Wx qw[:allclasses];
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package MyNotebook;

use Wx qw[:everything];
use base qw(Wx::Panel);
use strict;
```

**Comment by SueDNymme** [comment]
The first one is more correct.

In Perl, "use Foo qw(symbols)" loads the Foo module, and imports the specified symbols into the current namespace (which is declared via the "package" directive).  So in both cases, the first "use Wx" line is superfluous:  It loads the Wx module (good) but then imports the ":allclasses" symbol set into ... no package namespace.  The second "use Wx" line correctly appears *after* the "package MyWhatever" line, and so the specified symbol set (":everything", which I believe is a superset of ":allclasses") is imported into the package--- which allows those symbols to be used later.  Loading Wx in both places isn't exactly *wrong*, it's just slightly wasteful.

The "wxGlade: dependencies", similarly, probably ought to occur after the "package" line, but most class libraries do not export symbols, so 99% of the time it's not a real problem, I think.

**Comment by DietmarSchwertberger** [comment]
So this would be the correct header (also moved extracode to the end, where it is e.g. for Python)?
```
package MyFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

# begin wxGlade: dependencies
use MyNotebook;
# end wxGlade

# begin wxGlade: extracode
# end wxGlade
```

**Comment by SueDNymme** [comment]
Yes, that would be correct!

**Comment by DietmarSchwertberger** [comment]
In the source code, there was already a comment "# TODO: Don't add dependencies twice with Perl".
I have left this as it is, but the bug should be gone now in the master branch.

**Comment by SueDNymme** [comment]
I can confirm that the latest commit of the "master" branch (14e52066ac2bc458db6ca0765e1afb6bcf86ab69, as of 2018-10-16 13:36) does **not** exhibit the bug behavior described in point 8 of my original report.  So that's good!  Thank you.

**Comment by DietmarSchwertberger** [comment]
0.9.0a1 is available
