### ISSUE TITLE
wxGridBagSizer Rows and Cols cannot edit

### ISSUE THREAD

**Issue by whdxwym** [wxGlade/wxGlade#337]
I just add a frame to the application, and change the sizer_1 to wxGridBagSizer. On the Grid tab, everytime I click the Rows and Cols, the wxglade crashes. I've tried the other six Sizer, all work well.
and the error info is as below:
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'IndexError'>
Exception details:   list index out of range

Application stack traceback:
  File "C:\Program Files\Python36\lib\site-packages\wx\core.py", line 3240, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "F:\Download\wxGlade-0.8.3\edit_sizers\edit_sizers.py", line 561, in change_sizer
    szr._check_slots(remove_only=True)  # mark overlapped slots
  File "F:\Download\wxGlade-0.8.3\edit_sizers\edit_sizers.py", line 2138, in _check_slots
    occupied = set( self._get_occupied_slots() )
  File "F:\Download\wxGlade-0.8.3\edit_sizers\edit_sizers.py", line 2112, in _get_occupied_slots
    child = self.children[pos]

Date and time:       2018-09-06T16:11:12.516409
Python version:      3.6.6
wxPython version:    4.0.3
wxWidgets platform:  __WXMSW__
wxGlade version:     0.8.3

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. It seems that there are some issues when the number of rows or cols is 1.
I will try to fix as soon as possible.

**Comment by DietmarSchwertberger** [comment]
This seems to be quite tricky. It will proably take me some days.

**Comment by DietmarSchwertberger** [comment]
It should work now in the master branch.

**Comment by whdxwym** [comment]
yes, it works now, thank you very much.
