### ISSUE TITLE
Disable wx.Frame does not work

### ISSUE THREAD

**Issue by BrendanSimon** [wxGlade/wxGlade#338]
Calling `Disable()` on a `wx.Frame` derived object does not disable user input.  e.g. `myFrame.Disable()` does not get grey out buttons and they still react to a user clicking on them.

This posts suggest adding a `wx.Panel` to the frame and that all other objects should be children of the panel, then calling `myFrame.panel.Disable()` should disable the child objects.

http://wxpython-users.1045709.n5.nabble.com/wx-Frame-Disable-not-working-td3304307.html

Is this something that should be automated by wxGlade (maybe with a check box to add the panel or not), or should the user have to explicitly do this for all frames?

**Comment by DietmarSchwertberger** [comment]
Sorry, I just saw this now. It seems I missed the notification mail.

I don't think that this should be handled by wxGlade. The panel has a Disable method, right?

The internal data structure of wxGlade requires the sizer between Frame and Panel. I would like to get rid of this as it is not useful, but this will take some time. My plan is to change the internal structure of wxGlade during winter.
Having the sizer should not hurt, though, so it should not be necessary to call Destroy.

You should be able to build a panel with wxGlade and then use it within your other design as a CustomWidget. I have not tried this, though and you would not have a preview.

**Comment by BrendanSimon** [comment]
In the end I didn't need this functionality as I needed a progress dialog, which is modal, so the frame didn't accept any user input.
