### ISSUE TITLE
wxSlider event in wxGlade does not match wxSlider events available

### ISSUE THREAD

**Issue by Slechtvalk** [wxGlade/wxGlade#339]
wxGlade offers the insertion of a wxSlider. However, one of the events (_EVT_COMMAND_SCROLL_ENDSCROLL_) listed for wxSlider is not meant for wxSlider but for wxScrollBar:

<img width="625" alt="schermafbeelding 2018-09-28 om 09 53 56" src="https://user-images.githubusercontent.com/8831731/46195450-ae846d80-c304-11e8-97de-39df3339979c.png">

Compiling the inserted event handler results in an error:

```
/Users/kiwanda/techniek/software/Pallas/toepassing/PallasVenster.cpp:1153:76: error: call to non-static member function without an object argument
        EVT_COMMAND_SCROLL_ENDSCROLL(AantalBeperkingHoeveelheidID, PallasVenster::aantalBeperkingQueryHandler)
```

I reckon the appropriate event handler that wxGlade should list instead of _EVT_COMMAND_SCROLL_ENDSCROLL_ is _EVT_SCROLL_THUMBRELEASE_ .

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting.
`EVT_COMMAND_SCROLL_THUMBRELEASE` should be there already.
But probably `EVT_COMMAND_SCROLL_CHANGED` should be added, even though it is of limited use only (MS Windows only).

**Comment by DietmarSchwertberger** [comment]
0.9.0a1 is available
