### ISSUE TITLE
Exception on showing SplitterWindow

### ISSUE THREAD

**Issue by majkls23** [wxGlade/wxGlade#340]
Hello,
I met small issue when I opened my project:

ERROR   : None
An unexpected error occurred!

Exception type:      <type 'exceptions.AttributeError'>
Exception details:   'SplitterWindowSizer' object has no attribute 'item_properties_modified2'

Application stack traceback:
  File "C:\Users\semler\wxGlade-0.8.3\tree.py", line 792, in on_left_dclick
    self.show_toplevel(None, widget)
  File "C:\Users\semler\wxGlade-0.8.3\tree.py", line 928, in show_toplevel
    self._show_widget_toplevel(node)
  File "C:\Users\semler\wxGlade-0.8.3\tree.py", line 875, in _show_widget_toplevel
    self.create_widgets(c)
  File "C:\Users\semler\wxGlade-0.8.3\tree.py", line 859, in create_widgets
    self.create_widgets(c)
  File "C:\Users\semler\wxGlade-0.8.3\tree.py", line 859, in create_widgets
    self.create_widgets(c)
  File "C:\Users\semler\wxGlade-0.8.3\tree.py", line 860, in create_widgets
    node.widget.post_load()  # only edit_sizers.SizerBase has this method implemented and calls it for toplevel
  File "C:\Users\semler\wxGlade-0.8.3\widgets\notebook\notebook.py", line 237, in post_load
    self.sizer.item_properties_modified2(self)

Date and time:       2018-10-02T08:53:01.040000
Python version:      2.7.12
wxPython version:    3.0.2.0
wxWidgets platform:  __WXMSW__
wxGlade version:     0.8.3

**Comment by DietmarSchwertberger** [comment]
Hi!
I tried it, but did not see problems.
Would you mind attaching a small sample .wxg file?

**Comment by majkls23** [comment]
Hi there is sample file.
Things which I noticed:
If the child of splitter window is panel, it works ok,
If the child of splitter window is notebook, it fails to render.
However generated design works normally. So I thing it should be working.
[splitter_test.txt](https://github.com/wxGlade/wxGlade/files/2440687/splitter_test.txt)
(File should have .wxg suffix)

**Comment by DietmarSchwertberger** [comment]
Thanks. That explains the root cause: a notebook in a virtual sizer triggers the bug. The same could happen with a notebook as page of a notebook. I will have a look.

**Comment by DietmarSchwertberger** [comment]
This should be fixed in master branch now.

**Comment by majkls23** [comment]
It works now.
