### ISSUE TITLE
(Perl) Incorrect code generated for CheckListBox

### ISSUE THREAD

**Issue by sciurius** [wxGlade/wxGlade#341]
wxGlade 0.8.3 on Linux (Fedora 27). Same for GitHub version.

The Perl code generated for a CheckListBox contains an additional comma plus Pos/Size:

        Wx::CheckListBox->new($self, wxID_ANY, wxDefaultPosition, wxDefaultSize, [...], , wxDefaultPosition, wxDefaultSize, wxLB_EXTENDED|wxLB_NEEDED_SB);

This should be

        Wx::CheckListBox->new($self, wxID_ANY, wxDefaultPosition, wxDefaultSize, [...], wxLB_EXTENDED|wxLB_NEEDED_SB);

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. This one seems rather old...
I will have a look.

**Comment by DietmarSchwertberger** [comment]
Please try the version from repository.
The change is in `widgets/check_list_box/perl_codegen.py`:
```
class PerlCheckListBoxGenerator(wcodegen.PerlWidgetCodeWriter):
    tmpl = '%(name)s = %(klass)s->new(%(parent)s, %(id)s, ' \
           'wxDefaultPosition, wxDefaultSize, [%(choices)s], %(style)s);\n'
    prefix_style = False
```

**Comment by sciurius** [comment]
Confirmed. Thanks!
