### ISSUE TITLE
import from xrc error

### ISSUE THREAD

**Issue by whdxwym** [wxGlade/wxGlade#342]
I want to convert my wxformbuilder project to wxglade through xrc file, but fails with error. 
then I build a simple wxformbuilder project which only contains a panel, it still fails.

The error details is as below:

ERROR   : An internal error occurred while Import File "b'testGlade.xrc'"
An unexpected error occurred!

Exception type:      <class 'TypeError'>
Exception details:   expected str, bytes or os.PathLike object, not list

Application stack traceback:
  File "F:\Software\wxGlade\main.py", line 1137, in import_xrc
    self._open_app(ibuffer)
  File "F:\Software\wxGlade\main.py", line 937, in _open_app
    fn = os.path.basename(filename).encode('ascii','replace')
  File "C:\Python36\lib\ntpath.py", line 236, in basename
    return split(p)[1]
  File "C:\Python36\lib\ntpath.py", line 205, in split
    p = os.fspath(p)

Date and time:       2018-10-15T11:07:53.984603
Python version:      3.6.6
wxPython version:    4.0.3
wxWidgets platform:  __WXMSW__
wxGlade version:     0.9.0pre

**Comment by DietmarSchwertberger** [comment]
Actually, there were two errors. One in import and one in raising the exception.
Please try whether it's working now.
I'm not sure about the quality of the xrc import, though. wxGlade may expect a structure that's different from the one that wxformbuilder does export. E.g. wxGlade expects a frame to have a sizer as child while wx does not require this. So manual tweaking may be required.

**Comment by whdxwym** [comment]
the simple panel project works now. but my real project cannot work. so I make a new test case with a wxgridbagsizer in a panel, and the error is:

WARNING : Unknown widget "wxGridBagSizer" - fallback to generic widget "CustomWidget"

Since wxformbuilder can build a UI start from a panel, wxglade have to start from a frame or a dialog, this may cause some problem when parse the xml.

**Comment by DietmarSchwertberger** [comment]
I have added GridBagSizer to the list of widgets that `xrc2wgx.py` will try to import.
I don't know whether this alone is enough already. Maybe you want to upload the sample(s) here and I will give them a try. You could also mail me the full xrc file via personal mail if you want.

**Comment by whdxwym** [comment]
there is new errors, please help to debug. the xrc file is uploaded.

[testglade.txt](https://github.com/wxGlade/wxGlade/files/2485382/testglade.txt)

**Comment by DietmarSchwertberger** [comment]
Thanks. I will look into it, but only over the weekend. Probably the Span properties need to be converted.

**Comment by DietmarSchwertberger** [comment]
Your example should now be imported. I have not tested nested GridBag sizers.

**Comment by whdxwym** [comment]
it works well, thank you very much. Since wxglade does not contain dataviewctrl widget, my real case cannot recognize it, well I think it's an enhancement, not a bug.

**Comment by DietmarSchwertberger** [comment]
For a widget like DataViewCtrl a GUI builder can't contribute too much except some styles and maybe provide some limited preview. You need to do 99% of the work yourself anyway. So using CustomWidget in wxGlade should be fine for your purpose. If you have not used CustomWidget before, you'll find infos in the supplied documentation (also available here as snapshot: http://wxglade.sourceforge.net/docs/custom_widgets.html )

**Comment by whdxwym** [comment]
I'm a newbie of python, and I will try to do such job. Thank you very much.

**Comment by DietmarSchwertberger** [comment]
Welcome to wxPython. Don't forget to work through the wxGlade tutorial. It's aimed at people who did not use wx before and should get you started.
Probably you should address the DataViewCtrl support in wxGlade not as your first wxPython project...
