### ISSUE TITLE
feature requirement: save string in edtitable format

### ISSUE THREAD

**Issue by retsyo** [wxGlade/wxGlade#343]
usually I use wxGlade to create a  coarse GUI, then add more code to the generated Python file, sometimes re-arrange/create some control widget

now wxGlade saves the string to unicode like `u"\u6253\u5f00"`, as a result the use can't edit the generated python file easily

so is there a way to store the text in generated Python file for human's readability?

**Comment by DietmarSchwertberger** [comment]
Well, if your requirement was about e.g. german umlauts (ÄÖÜ), this could be accomplished by setting application->encoding to "ISO-8859-1", i.e. Latin-1 and then modify wxGlade not to encode it. (At the moment it would still write the encoded version.)
Is there a mongolian encoding that Python supports and that contains all required characters within the range 32 to 255?

**Comment by retsyo** [comment]
I use Chinese, it seems that Chinese are always translated into something like `u"\u6253\u5f00"`

**Comment by DietmarSchwertberger** [comment]
It seems that gb2312 has several thousand characters. So encoding is always required. Your best bet is to find a Python-aware editor that displays encoded characters.

**Comment by retsyo** [comment]
your suggestion on seeking a so-said python-string-aware editor is so crazy since I have never meet/heard such a thing. None of wingide, pycharm, and scite reads and shows `u"\u6253\u5f00"` in their original Chinese character. In fact, we only write a source file and save it with some encoding, then some editor/IDE can read it properly without worry about code the Chinese into `u"\u6253\u5f00"`

So I checked the source of wxGlade, and I found the suspicious function `_quote_str(self, s)` in  `codegen\py_codegen.py`. A note said that 

```
wxGlade don't handles file encoding well currently. Thereby
               we escape all unicode characters.
```

however there is no details, and I DO think it is not necessary to do any `raw-unicode-escape`. So I changed the whole function to
```
    def _quote_str(self, s):
   
     # convert all strings to unicode first
        if not isinstance(s, compat.unicode):
            s = s.decode(self.app_encoding)

        return '"%s"' % s
```

Then the generated python code meets what I stated in this issue.

**Comment by DietmarSchwertberger** [comment]
Does this modification work for you?
```
    def _quote_str(self, s):
        # convert all strings to unicode first
        if not isinstance(s, compat.unicode):
            s = s.decode(self.app_encoding)

        # check if it's pure ascii
        try:
            dummy = s.encode('ascii')
            if self._use_gettext:
                return '_("%s")' % s
            else:
                return '"%s"' % s
        except UnicodeError:
            pass

        # try to write with the given encoding
        try:
            s.encode(self.app_encoding)
        except UnicodeEncodeError:
            s = s.encode('raw-unicode-escape')
            s = self._recode_x80_xff(s)
            s = s.decode("ASCII")

        # convert unicode strings to pure ascii
        # use "raw-unicode-escape" just escaped unicode characters and not default escape sequences
        if self._use_gettext:
            return '_(u"%s")' % s # XXX omit u for Python 3
        else:
            return 'u"%s"' % s # XXX omit u for Python 3
```

**Comment by retsyo** [comment]
Yes, the modification works for me. Thanks

**Comment by DietmarSchwertberger** [comment]
0.9.0a1 is available
