### ISSUE TITLE
Not possible to set decimal Increment property for wxSpinCtrlDouble widget

### ISSUE THREAD

**Issue by boyank** [wxGlade/wxGlade#345]
Using wxGlade 0.9.0a1
It's not possible to set decimal Increment property for wxSpinCtrlDouble widget. The respective field in Widget tab accepts only integer numbers. You need to set the Increment property in Code tab or edit it after the code is generated.

**Comment by DietmarSchwertberger** [comment]
What region settings do you have? E.g. I'm in Germany and I have to enter e.g. "1,1". Using a decimal point does not work. Maybe I can find a workaround. I would prefer to accept either point or comma.

**Comment by DietmarSchwertberger** [comment]
There seems to be no easy way to replace key codes (`KeyEvent` does not allow a modification).
If you confirm that the regional decimal separator is working, I will close the issue.

If you want to give it a try yourself, have a look at `new_properties.py`, class `SpinDoubleProperty`.

**Comment by boyank** [comment]
well, this is strange. I am glad you confirmed there was a problem. My observations from this morning:
On windows/python 2.7
In my regional settings I had a dot as decimal symbol and it was not accepting neither dot nor comma (in previous days).
After reading your comment above I changed the decimal symbol to comma. As a result it started to accept both comma and dot, but if dot - replace it with comma after exit the filed.
I changed the regional settings back to dot. Now it accepts both dot and comma, but after exit the field it replace comma with dot.
After restart (decimal symbol is still dot) it still continue to accept both dot and comma.
In a clean virtual environment - still works.
I also noticed that when decimal part of increment is 0, e.g. 0, 1, 2 (it does not show the decimal part) and you try to enter decimal part e.g. from 0 to make it 0.1, it reverts back to the integer number (e.g. 0) the first time. You have to enter .1 one more time and then it preserves the change.
I will try to test on different windows machine and will test on linux mint and python3 tonight.

**Comment by boyank** [comment]
tested again on linux - it's not possible to enter neither comma, nor dot

**Comment by DietmarSchwertberger** [comment]
It seems that `SpinCtrlDouble` can return strings or floats.
Could you please try this modification in `new_properties.py`?
```
class SpinDoubleProperty(SpinProperty):
    ...
    def _set_converter(self, value):
        if isinstance(value, compat.unicode):
            return float(value.replace(u",", u"."))
        elif isinstance(value, bytes):
            return float(value.replace(b",", b"."))
        return value
```

**Comment by boyank** [comment]
on linux mint, python3, no effect whatsoever - the Increment field on widget tab does not accept dot/comma

**Comment by DietmarSchwertberger** [comment]
Could you please check in the Preview window whether the previewed SpinCtrlDouble has the same problems?
Also, please add a `print("SpinDoubleProperty", repr(value), type(value))`.
Here (on Windows) this reports e.g. 
```
SpinDoubleProperty '1,3' <class 'str'>
SpinDoubleProperty 4.0 <class 'float'>
```
I noticed that I don't always get the update when just leaving the control with the Tab key while it works when I hit Enter. E.g. entering "1,2" plus Tab is working while "1.2" plus Tab does not.

**Comment by boyank** [comment]
![screenshot from 2018-11-08 22-20-07](https://user-images.githubusercontent.com/7230632/48225554-cc35ff80-e3a5-11e8-8f89-bd3b940b872e.png)
![screenshot from 2018-11-08 22-22-11](https://user-images.githubusercontent.com/7230632/48225555-ce985980-e3a5-11e8-96fa-187e4611742c.png)
![screenshot from 2018-11-08 22-24-45](https://user-images.githubusercontent.com/7230632/48225559-d0fab380-e3a5-11e8-81ff-af86de95e79b.png)
![screenshot from 2018-11-08 22-28-27](https://user-images.githubusercontent.com/7230632/48225561-d2c47700-e3a5-11e8-8c91-1c05109e2451.png)
The last screenshot error pop-up, but I didn't realize what actions caused it

**Comment by DietmarSchwertberger** [comment]
OK, we're coming closer. It seems that the ìnc` argument to `SpinCtrlDouble` also initializes the number of digits.
E.g. if it's 1.0, then you can enter only integers, even if later on `SetIncrement` is called with a value <1. So, additionally `SetDigits` needs to be called. Give me some time to thing what's the best solution.

**Comment by DietmarSchwertberger** [comment]
As workaround, you can add a `SetDigits`:
```
    def create_spin_ctrl(self, panel):
        style = wx.TE_PROCESS_ENTER | wx.SP_ARROW_KEYS
        spin = wx.SpinCtrlDouble( panel, -1, style=style, min=self.val_range[0], max=self.val_range[1] )
        spin.SetDigits(3)
        spin.SetValue(self.value)
        range_ = abs(self.val_range[1]-self.val_range[0])
        if range_<=1.0:
            spin.SetIncrement(0.1)
        else:
            spin.SetIncrement(1.0)
        return spin
```

**Comment by boyank** [comment]
Thank you for the efforts. I just wanted to report the bug. For my project I just set the Increment property in the code tab. That workaround works - it accepts comma, but no dot.
By the way, don't you think it's a bit confusing - the min/max values use dot, value/increment - comma, and python uses just dot, no comma as decimal symbol? Just my 2 cents.

**Comment by DietmarSchwertberger** [comment]
You're right. At the moment I would prefer to have just decimal points, but for the SpinCtrlDouble I can't do that as it's done by wx.

**Comment by boyank** [comment]
Then I think you may apply this fix/workaround and close the issue :-).
In any case - thanks for this project, great tool

**Comment by DietmarSchwertberger** [comment]
in 0.9.0b1
