### ISSUE TITLE
Missing icons wxART***

### ISSUE THREAD

**Issue by boyank** [wxGlade/wxGlade#346]
Using wxGlade 0.9.0a1

On Windows I get this error on opening wxglade.py

12:21:47 ч.: can't open file '***mypath***\wxGlade\icons\wxART_NEW' (error 2: the system cannot find the file specified.)
12:21:47 ч.: Failed to load image from file ***mypath***\wxGlade\icons\wxART_NEW".
12:21:47 ч.: can't open file '***mypath***\wxGlade\icons\wxART_FILE_OPEN' (error 2: the system cannot find the file specified.)
12:21:47 ч.: Failed to load image from file "***mypath***\wxGlade\icons\wxART_FILE_OPEN".
12:21:47 ч.: can't open file '***mypath***\wxGlade\icons\wxART_FILE_SAVE' (error 2: the system cannot find the file specified.)
12:21:47 ч.: Failed to load image from file "***mypath***\wxGlade\icons\wxART_FILE_SAVE".
12:21:47 ч.: can't open file '***mypath***\wxGlade\icons\wxART_REDO' (error 2: the system cannot find the file specified.)
12:21:47 ч.: Failed to load image from file "***mypath***\wxGlade\icons\wxART_REDO".
12:21:47 ч.: can't open file '***mypath***\wxGlade\icons\wxART_REDO' (error 2: the system cannot find the file specified.)
12:21:47 ч.: Failed to load image from file ***mypath***\wxGlade\icons\wxART_REDO".
12:21:47 ч.: can't open file '***mypath***\wxGlade\icons\wxART_EXECUTABLE_FILE' (error 2: the system cannot find the file specified.)
12:21:47 ч.: Failed to load image from file "***mypath***\wxGlade\icons\wxART_EXECUTABLE_FILE".
12:21:47 ч.: can't open file '***mypath***\wxGlade\icons\wxART_HELP_BOOK' (error 2: the system cannot find the file specified.)
12:21:47 ч.: Failed to load image from file "***mypath***\wxGlade\icons\wxART_HELP_BOOK".

I don't see these in the icons folder.
Strange is I don't get the same on Linux Mint.

**Comment by DietmarSchwertberger** [comment]
The ART_... icons are built into wxWidgets/wxPython: https://github.com/wxWidgets/wxWidgets/tree/aab02ec1ceb4602ea1da23a5d422af0f7abea21d/art

That looks like a wxPython issue. Are you using the stock wxPython version from PIP?
Please check whether the ArtProvider.py from the wxPython demo is working for you.

**Comment by boyank** [comment]
The problem is on my office computer, but I believe I installed from pip. However there it's python2, and on linux I use it with python3 and wheels from https://extras.wxpython.org/wxPython4/extras/linux/

Note that error message pops-up on open wxglade.py (no project loaded, etc.) also note that the path is wxGlade\icons, i.e. it looks for these in the wxGlade subfolder.

**Comment by DietmarSchwertberger** [comment]
That's probably the fallback to check for a file. I've just tried and with Python 2.7 and Phoenix I see the problem too.

**Comment by DietmarSchwertberger** [comment]
It turned out that for Phoenix wxART_... constants are strings in Python 2.
Fix is in the repository. Thanks a lot.

**Comment by DietmarSchwertberger** [comment]
fixed in 0.9.0b1
