### ISSUE TITLE
Assertion error with frame icon (Mac)

### ISSUE THREAD

**Issue by BrendanSimon** [wxGlade/wxGlade#347]
Assigning an icon to a frame causes a Mac app bundle to generate an assertion error.

An app bundle generated for Windows seems fine.

```
  File "BJS_Frame_WXG.py", line 54, in __set_properties
    _icon.CopyFromBitmap(wx.Bitmap("../../../images/BJS_Transparent_75dpi.png", wx.BITMAP_TYPE_ANY))
wx._core.wxAssertionError: C++ assertion "IsOk()" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py36/Phoenix/ext/wxWidgets/src/osx/core/bitmap.cpp(1504) in GetHeight(): invalid bitmap
[35667] Failed to execute script Blair Digital Bagpipes
Segmentation fault: 11
```

**Comment by BrendanSimon** [comment]
The app does **NOT** generate the assertion if run from the command line with the python interpreter.

`/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m BJS.py `

It seems to be a problem when bundled with pyinstaller.

These links do not specify which file types are supported for wx.Icon on Mac.

- https://wxpython.org/Phoenix/docs/html/bitmap_overview.html#bitmaps-and-icons
- https://wxpython.org/Phoenix/docs/html/bitmap_overview.html#supported-bitmap-file-formats

Should `wxGlade` warn or cater for different file types for different platforms.  e.g. generate different code that can change the filetype if required?

**Comment by DietmarSchwertberger** [comment]
I don't see how that is related to wxGlade.
wxBitmap will not raise an error, even if the path is invalid. So probably your packager places the file somewhere else.
```
>>> a = wx.App()
>>> wx.Bitmap("../../../images/BJS_Transparent_75dpi.png", wx.BITMAP_TYPE_ANY)
<wx._core.Bitmap object at 0x02ED50D0>
>>> wx.Bitmap("../../../images/BJS_Transparent_75dpi.png", wx.BITMAP_TYPE_ANY).IsOk()
False
>>>
```

**Comment by BrendanSimon** [comment]
It's not related at all.  It was an oversight by me (not updating my build script so that pyinstaller would bundle it).

Sorry about the bogus issue report !!

<mental-note>Coding on Sunday night should be verbotten</mental-note>
