### ISSUE TITLE
wxPyDeprecationWarning for SetStringItem calls (and other errors)

### ISSUE THREAD

**Issue by ichibrosan** [wxGlade/wxGlade#349]
Here is the invocation with version numbers:

Dougs-MBP:wxGlade doug$ python3 wxGlade.py
INFO    : Starting wxGlade version "0.9.0b1" on Python 3.7.1
INFO    : Base directory:             /Users/doug/Documents/GitHub/wxGlade
INFO    : Documentation directory:    /Users/doug/Documents/GitHub/wxGlade/docs
INFO    : Icons directory:            /Users/doug/Documents/GitHub/wxGlade/icons
INFO    : Build-in widgets directory: /Users/doug/Documents/GitHub/wxGlade/widgets
INFO    : Template directory:         /Users/doug/Documents/GitHub/wxGlade/templates
INFO    : Credits file:               /Users/doug/Documents/GitHub/wxGlade/CREDITS.txt
INFO    : License file:               /Users/doug/Documents/GitHub/wxGlade/LICENSE.txt
INFO    : Manual file:                /Users/doug/Documents/GitHub/wxGlade/docs/html/index.html
INFO    : Tutorial file:              docs/tutorial.html
INFO    : Home directory:             /Users/doug
INFO    : Application data directory: /Users/doug/.wxglade
INFO    : Configuration file:         /Users/doug/.wxglade/wxgladerc
INFO    : History file:               /Users/doug/.wxglade/file_history.txt
INFO    : Log file:                   /Users/doug/.wxglade/wxglade.log
INFO    : Using wxPython 4.0.3

Here is the concerning warning messages:

/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:215: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  self.menu_items.InsertStringItem(index, indent + label)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:216: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(index, 2, name)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:217: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(index, 3, check_radio)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:218: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(index, 5, id)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:289: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(self.selected_index, 0, value)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:302: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(self.selected_index, 1, value)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:333: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(self.selected_index, 4, self.help_str.GetValue())
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:338: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(self.selected_index, 5, self.id.GetValue())
objc[4758]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff981d31d0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1165c1dc8). One of the two will be used. Which one is undefined.
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:215: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  self.menu_items.InsertStringItem(index, indent + label)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:216: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(index, 2, name)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:217: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(index, 3, check_radio)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:218: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(index, 5, id)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:466: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(index, 0, misc.wxstr(" "*4) + label)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:289: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(self.selected_index, 0, value)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:302: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(self.selected_index, 1, value)
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:338: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(self.selected_index, 5, self.id.GetValue())
Unable to find application named 'Help Viewer.app'
Unable to find application named 'Help Viewer.app'
/Users/doug/Documents/GitHub/wxGlade/widgets/menubar/menubar.py:328: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.menu_items.SetStringItem(self.selected_index, 3, str(self.check_radio.GetSelection()))

**Comment by DietmarSchwertberger** [comment]
I will not include the changes into revision 0.9. The risk to introduce bugs is too high.

**Comment by DietmarSchwertberger** [comment]
I've refactored a lot, but myself I'm rarely editing menus or toolbars and so it's quite likely that I will miss some bugs.
Would you mind testing the modifications? They're in the branch NEW_STRUCTURE. Loading and saving with this branch is compatible to the release versions.

**Comment by DietmarSchwertberger** [comment]
1.0.0a1 is online.
