### ISSUE TITLE
Show Manual (F1) Icon references unknown App on mac

### ISSUE THREAD

**Issue by ichibrosan** [wxGlade/wxGlade#350]
Clicking on the manual icon causes the following debug message on the glade invocation console...

Unable to find application named 'Help Viewer.app'

I was unable to locate any information about where from or how to install the proper viewer so this will work correctly. This is not a show stopper, just a little issue.

Thanks

**Comment by ichibrosan** [comment]
wxGlade/main.py:
at line 1098:
        if wx.Platform == "__WXMAC__":
            os.system(r'open -a Help\ Viewer.app %s' % html_file)

This seems to be where the action is. I don't know if this app used to exist, or whether this was meant to be configurable. Maybe a soft link in the Applications folder to Safari? There is nothing in the App Store called "Help Viewer".

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. It seems that only `HelpViewer` is available now, but a quick check did not work with command line arguments.
The better option seems to be to just call open.
Does it work for you if you replace the `os.system` line with
`os.system(r'open "%s"' % html_file)` ?

**Comment by ichibrosan** [comment]
I modified the os call to use safari instead, since that is always available on the mac.
It’s job is opening html files after all.

**Comment by DietmarSchwertberger** [comment]
Fixed in 0.9.0b2
