### ISSUE TITLE
Hashbangs explicitly use py2

### ISSUE THREAD

**Issue by ashleywaite** [wxGlade/wxGlade#351]
Both entry points, `wxglade.py` and `wxglade.pyw` currently want to run with python 2.

This is pretty confusing because the docs pretty explicitly say that we should be running on target version, http://wxglade.sourceforge.net/docs/intro.html#running-wxglade

With some python launchers this means that it doesn't run by default. Such as on Windows:
``` 
D:\wxGlade-0.8.3>py wxglade.pyw
Requested Python version (2) is not installed
```

It actually requires forcing the version at present with `py -3 wxglade.pyw` which could pretty easily lead to people that intend to be building on python 3 actually running it in python 2 because it is also present on their systems.

The explicit version in the hashbang should be removed if py2 and py3 execution are equally supported.
`#!/usr/bin/env python2` -> `#!/usr/bin/env python`

Which resolves the issue of forcing version or having an unexpected version running it.

**Comment by DietmarSchwertberger** [comment]
You're right. I never noticed this as I don't use py, but always the interpreter path (as I have several installations). I will update for the next 0.9.0 beta version.

**Comment by DietmarSchwertberger** [comment]
It's in the recent betas.
