### ISSUE TITLE
Names missing from sizer and sizeritem objects in XRC output

### ISSUE THREAD

**Issue by blhiggins** [wxGlade/wxGlade#356]
As mentioned on the XRC Overview page on the wxWidgets site (https://docs.wxwidgets.org/3.0/overview_xrc.html, inexplicably in the "C++ header file generation" section), a sizeritem can be accessed using the XRCSIZERITEM macro by giving it the value of the "name" attribute of the sizer object. The example given there shows a spacer type. However, wxGlade's XRC output seems to never generate "name" attributes for these types, even if one explicitly adds a spacer in the sizer's slot and customizes its name in wxGlade. So wxGlade cannot be used to generate an XRC file representing that example.

wxGlade also does not include in XRC output the name attrbiutes of wxBoxSizer types, and possibly other sizers, preventing accessing those with the usual XRCCTRL macro.

This seems to make it problematic to, e.g., add widgets to sizers programmatically.

(I also noticed that the XRC output does not contain any "Extra properties for this widget" for spacers that are added in wxGlade.)

Version 0.9.1 on Python 3.7.2+ and wxPython 4.0.4

**Comment by DietmarSchwertberger** [comment]
I'm just implementing this. The spacer name part is done.
From looking at the overview_xrc page, sizers don't have names.
What would be the point of having extra properties for spacers?

**Comment by blhiggins** [comment]
On Sunday, February 24, 2019 6:32:37 PM EST Dietmar Schwertberger wrote:
> What would be the point of having extra properties for spacers?

Oh I didn't have anything in mind, and there might not be a utility in 
practice. I was just playing around and noticed that it was not propagating. 
Seemed worth mentioning in a "maybe unintentional data loss" way. Feel free to 
ignore.

**Comment by DietmarSchwertberger** [comment]
Well, I don't know why a spacer has extra properties at all. This pre-dates my work with and on wxGlade.

Maybe, you want to give the NEW_STRUCTURE branch a try. This exports the name into the XRC file.
Releases 0.9 and NEW_STRUCTURE are compatible. If editing with NEW_STRUCTURE does not work for you, you can at least use it for XRC export.

**Comment by DietmarSchwertberger** [comment]
1.0.0a1 is online.
