### ISSUE TITLE
Provide a way to define borders in dialog units

### ISSUE THREAD

**Issue by Belse** [wxGlade/wxGlade#357]
I would like to have the possibility to enter layout border as for instance '4d' to have it generated dialog units, which should also have a "Use dialog units by default for border properties" option.

I currently hacked a very old version of wxglade to generate this py_codegen.py to get call for instance: cn('wxDLG_SZE') + '(self, %s, 0).x' % (size)
Yes, one have to define whether x or y is the right choice. Allowing values like '4dx' or '4dy' would expose this choice to the user.

**Comment by DietmarSchwertberger** [comment]
Åke has sent me a patch to add dialog unit support that is based on the master branch.
Once I'm done with my current refactorings, I will look into this.

**Comment by DietmarSchwertberger** [comment]
A branch ISS357_DLG_UNITS is in the repository.
This adds support for dialog units with borders, spacers and hgap/vgap, as it was in Åke's code.
Please try.

To be done:
 - add test cases
 - fix some minor issues (test cases failing)
 - add spin buttons to border
 - validation of border preference settings

**Comment by DietmarSchwertberger** [comment]
Code generation has been changed. Now first Fonts are set and then the size. This way dialog units should actually work with frame and dialog sizes.
Remaining to be done:
 - add test cases
 - add spin buttons
 - validation of border preference settings

**Comment by DietmarSchwertberger** [comment]
@Belse : I have posted a message on the wxglade-general list. It would be good to get some inputs how people want to use dialog units.

**Comment by DietmarSchwertberger** [comment]
Without examples on the list, I need to postpone this at least to 1.1 or 1.2.

**Comment by DietmarSchwertberger** [comment]
Closed due to lack of feedback.
