### ISSUE TITLE
BitmapButton AttributeError with wxPython 2.8.12

### ISSUE THREAD

**Issue by Belse** [wxGlade/wxGlade#358]
Error shown when pressing most buttons in palette. Latest 0.9.2 release.

Example fix in common.py @ line 216
```
-    btn = event.GetEventObject()
-    btn.SetValue(True)
+    if compat.version >= (3,0):
+        event.GetEventObject().SetValue(True)
    palette.reset_togglebuttons(keep=btn)
```
or check instance with wx imported.

===============================

ERROR   : None
An unexpected error occurred!

Exception type:      <type 'exceptions.AttributeError'>
Exception details:   'BitmapButton' object has no attribute 'SetValue'

Application stack traceback:
  File "C:\workspace\optTools\wxGlade-new\common.py", line 216, in add_object
    btn.SetValue(True)

Date and time:       2019-03-29T13:40:46.349000
Python version:      2.7.8
wxPython version:    2.8.12.1
wxWidgets platform:  __WXMSW__
wxGlade version:     0.9.2

=============================

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting and fixing.
I don't routinely test 2.8 interactively, just with test cases for code generation etc.

**Comment by DietmarSchwertberger** [comment]
0.9.3 is released
