### ISSUE TITLE
(C++) Incorrect code generated for wxStaticText with Wrap

### ISSUE THREAD

**Issue by blhiggins** [wxGlade/wxGlade#360]
Affects 0.9.3. Testcase attached. C++ output for a wxStaticText with Wrap enabled looks like this:

    wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, wxT("This is a long line of text for the purpose of testing the C++ code generation when Wrap is enabled."));
    wxStaticText* label_1.Wrap(100);

The second line is the offending one, with the duplicated 'wxStaticText*' and the '.'.

Clearly something's wrong at widgets/static_text/codegen.py:27. My guess is that line should read:
            ret.append( '%s->Wrap(%d);\n'%(obj.name, obj.wrap) )
This seems to work, but I don't know how correct it is within the context of the rest of the codebase.

Thanks!

[wrap_test.wxg.zip](https://github.com/wxGlade/wxGlade/files/3090359/wrap_test.wxg.zip)

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. You're right.
The template key 'name' is highly misleading. I need to figure out a solution for all languages before I will add the fix to the repository, though.

**Comment by DietmarSchwertberger** [comment]
0.9.4 is released
