### ISSUE TITLE
Add MultiSplitterWindow support

### ISSUE THREAD

**Issue by ltybenet** [wxGlade/wxGlade#361]
I saw SplitterWindow, but it doesn't meet my needs. If I can add MultiSplitterWindow, I think it would be better if you have time.

**Comment by DietmarSchwertberger** [comment]
For the moment I don't have time to implement this. Are you aware that you can cascade/nest splitter windows? I have been doing this quite often. Does MultiSplitterWindow have an advantage over this?

I'm currently re-working the internal data structures of wxGlade. After that it should be reasonably simple to implement a MultiSplitterWindow. Would you be willing to implement this yourself?
The basic structure would be more like the notebook implementation.

The new implementation of the noebook looks like this:
https://github.com/wxGlade/wxGlade/blob/NEW_CODEGEN/widgets/notebook/notebook.py

I hope that I can finalize the new structure in May.
