### ISSUE TITLE
Placing ListCtrl fails with error

### ISSUE THREAD

**Issue by cartertemm** [wxGlade/wxGlade#363]
it might be worthy to note that I'm using the ACCESSIBILITY branch, although I'm unaware if this is the cause or not due to an inability to use the app without buttons that appear to a screenreader.

### Steps to reproduce
* Create a frame
* Add a panel
* Insert a slot
* Tab down to ListCtrl
* Press space to select
* Press F2 to get back to the TreeView
* Place the ListCtrl by pressing enter on the empty slot.

### Error
```
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'AttributeError'>
Exception details:   'NoneType' object has no attribute 'GetMinSize'

Application stack traceback:
  File "main.py", line 247, in on_notebook_size
    self._set_page_size(scrolled)
  File "main.py", line 235, in _set_page_size
    wm, hm = panel.GetSizer().GetMinSize()

Date and time:       2019-05-03T07:28:24.375029
Python version:      3.7.1
wxPython version:    4.0.3
wxWidgets platform:  __WXMSW__
wxGlade version:     0.9.9pre


```

**Comment by DietmarSchwertberger** [comment]
I'm not sure whether the traceback matches the problem.
The traceback seems to be triggered by resizing the main window or the property panel.
It can probably be fixed by checking whether the panel actually has a sizer.
I don't know off-hand when this condition happens, though.
I have just pushed a commit for this.

By adding frame/panel/ListCtrl I could not see a problem.

**Comment by cartertemm** [comment]
I've pulled your changes and seem to be getting a different error now.
[log is here](https://github.com/wxGlade/wxGlade/files/3143922/wxglade.log)

This was generated by adding frame/panel/BoxSizer/ListCtrl

**Comment by DietmarSchwertberger** [comment]
Ah, sorry, please de-activate the option Edit->Preferences->Accessibility->Show editors for Grid Properties.
I'm still working on this and it triggered the error that you have seen.
I think that end of next week I can continue to work on the editors.

**Comment by cartertemm** [comment]
Yep, that fixed it. Thanks
