### ISSUE TITLE
ignore unknown event EVT_CHAR for wxTextCtrl

### ISSUE THREAD

**Issue by retsyo** [wxGlade/wxGlade#365]
when I generate python code, the warning comes out. As a result, no python code is created; what is worse, wxGlade deletes EVT_CHAR when I save wxg file. 

But in fact, wxTextCtrl supports the EVT_CHAR event

**Comment by DietmarSchwertberger** [comment]
For one of the next versions I'm planning to support additional events.

**Comment by retsyo** [comment]
In my app, I can't use `self.Bind(wx.EVT_CHAR, self.onTextDeviceIdInput, self.textDeviceID)`, but `self.textDeviceID.Bind(wx.EVT_CHAR, self.onTextDeviceIdInput)` works

maybe I misunderstood. But these two make same sense for me.

**Comment by DietmarSchwertberger** [comment]
I did not try, but I would think that EVT_CHAR is derived from wx.Event and does not propagate to the window as it's handled by the control itself. I.e. you can catch the EVT_CHAR for the widget, but if it's not handled, the text control will handle it and insert the character.

EVT_TEXT on the other hand is derived from wx.CommandEvent and will propagate to the parent window.

I think you should see some info here:
https://wxpython.org/Phoenix/docs/html/events_overview.html#how-events-propagate-upwards

**Comment by BrendanSimon** [comment]
I'm not sure this issue was fully understood.

I added an "EVT_CHAR" entry to my frame with an `on_char` handler.

The project seems to save ok, and I can see an entry in the wxglade project file.

```
            <handler event="EVT_CHAR">on_char</handler>
```

However, when generating code I get an error message:

```
WARNING: Ignore unknown event EVT_CHAR for Main_Frame_WXG
```

and there is no generated code for this event (due to the "error").

I can manually add the event to my derived frame class and the code does capture any key presses.

```
        self.Bind( wx.EVT_CHAR, self.on_char )
```

So, I think it is a bug in wxglade not supporting all known event types.

**Comment by DietmarSchwertberger** [comment]
Ah, OK. Yes, this is work in progress and only in the repository.
The plan is eventually to have pop-up menus or something similar to choose from available events. Generating and grouing the available events is non-trivial, though, so it will take some time.

I will implement at least the code generation soon such that the handler is generated and bound in your case. Give me a few days or weeks.

**Comment by DietmarSchwertberger** [comment]
I think that such events are also not restored when loading from a .wxg file. I will fix this first...

**Comment by DietmarSchwertberger** [comment]
OK, basic support is now in the repository.
To be done: Modify code generation for preview to handle non-existent events.

**Comment by DietmarSchwertberger** [comment]
I think that now everything should be fine:
 - save/load should work
 - binding should work
 - on editing and loading, event names EVT_... should be converted to uppercase
 - preview code has an exception handler which just prints a note to the console

**Comment by BrendanSimon** [comment]
Yes, that seems to work ok now.  That was a very fast "few days or weeks" !!  Tip of that hat to you Dietmar.

**Comment by DietmarSchwertberger** [comment]
Well, it turned out to be easier than expected. All the refactorings of the internal structures are paying off.

**Comment by DietmarSchwertberger** [comment]
1.0.0a1 is online.
