### ISSUE TITLE
Generated C++ event handlers should be virtual (again)

### ISSUE THREAD

**Issue by bk138** [wxGlade/wxGlade#370]
Hi there,
I upgraded from wxGlade 0.6.3 to 0.8.3 and noticed that the newer version does not export C++ event handler methods as `virtual` anymore. 83dafbc9de68fc9fa3188b03e7eacf0e110ded3b introduced this, [the first release with this was 0.7.1](https://github.com/wxGlade/wxGlade/blob/master/NEWS.txt).  83dafbc9de68fc9fa3188b03e7eacf0e110ded3b states that 

> The wx documentation states "The member function that handles an event
    does not have to be virtual."

which might be true, but the event handlers being virtual really relly helps the IMO quite common use case where one subclasses the wxGlade-generated C++-classes. In fact, non-virtual event-handlers break existing projects like [this one here](https://github.com/bk138/multivnc/blob/master/src/gui/multivnc.wxg) where with 0.8.3-generated code only the base class's methods are called although they're overriden in the subclass. 

Is this meant to used differently now? If not, I suggest to revert 83dafbc9de68fc9fa3188b03e7eacf0e110ded3b, although I don't know the exact reasons it was actually introduced. 

PS: I'm aware of https://sourceforge.net/p/wxglade/mailman/message/36706324/ and willing to test this.

**Comment by DietmarSchwertberger** [comment]
I don't know why that was changed at all.
The latest commit in the master branch has the virtual methods again. I would not want to change this in the 0.8 or 0.9 series if not absolutely necessary. Test cases are not adjusted yet. I will do so after feedback.

Would you mind trying? The structure of the generated code is different from before. It should look more like what a human being would write. As I can't easily test C++, it would be great to receive feedback on this. In Python things are working fine.

Next on the list will then be the dynamic event binding...

**Comment by bk138** [comment]
Thanks for the swift reply! I fear, though, that 89400ab242856eba71586cbe55d023061ed81801 did not (yet) fix the issue, for me, adding `virtual` to https://github.com/wxGlade/wxGlade/blob/master/codegen/cpp_codegen.py#L627 did it. Really not sure about those two code paths though. 

I also encountered a separate issue which I reported as #371, will need to dig a bit more into this.

**Comment by DietmarSchwertberger** [comment]
Do the event handlers in the C++ files need to have the virtual keyword as well?

```
void All_Widgets_Frame::onStartConverting(wxCommandEvent &event)  // wxGlade: All_Widgets_Frame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (All_Widgets_Frame::onStartConverting) not implemented yet"));
}
```

**Comment by bk138** [comment]
> Do the event handlers in the C++ files need to have the virtual keyword as well?
> 
> ```
> void All_Widgets_Frame::onStartConverting(wxCommandEvent &event)  // wxGlade: All_Widgets_Frame.<event_handler>
> {
>     event.Skip();
>     // notify the user that he hasn't implemented the event handler yet
>     wxLogDebug(wxT("Event handler (All_Widgets_Frame::onStartConverting) not implemented yet"));
> }
> ```

Nope, only the headers.

**Comment by DietmarSchwertberger** [comment]
OK, then things should work now. Please test.

**Comment by bk138** [comment]
That's it, thanks for the weekend work! ;-)
