### ISSUE TITLE
BoxSizer orientation

### ISSUE THREAD

**Issue by luker98** [wxGlade/wxGlade#372]
When i add a BoxSizer, it inverts the orientation

**Comment by DietmarSchwertberger** [comment]
I can't see this. What version and platform?

**Comment by luker98** [comment]
Version 0.9.3 on Python 2.7.15+ and wxPython 3.0.2.0
Ubuntu 18.04.3 LTS

**Comment by DietmarSchwertberger** [comment]
I have just tried 0.9.3 with Python 2.7 and wxPython 3.0.2 in my Ubuntu 17 VM.
I have added box sizers to the toplevel sizer of a frame.
Everything seems to work as expected. Would you mind posting screenshots?

**Comment by luker98** [comment]
Yes of course.
First pic to show my selection:
![image](https://user-images.githubusercontent.com/49037014/63925917-3742e680-ca4b-11e9-9d95-eed50db6b6ff.png)

And the second for the result:
![image](https://user-images.githubusercontent.com/49037014/63925956-46c22f80-ca4b-11e9-8d0e-887efc5c4ef7.png)

**Comment by DietmarSchwertberger** [comment]
That's a horizontal sizer with two slots next to each other. What's the problem?

**Comment by luker98** [comment]
I supposed that horizontal sizer has horizontal separation

**Comment by DietmarSchwertberger** [comment]
Orientation, not separation. The examples in the wxGlade and wx documentation seem clear.
