### ISSUE TITLE
SyntaxWarnings with Python 3.8

### ISSUE THREAD

**Issue by swt2c** [wxGlade/wxGlade#373]
When building 0.9.4 with Python 3.8 on Fedora, I noticed these SyntaxWarnings:

```
Bytecompiling .py files below /builddir/build/BUILDROOT/wxGlade-0.9.4-1.fc32.x86_64/usr/lib/python3.8 using /usr/bin/python3.8
/usr/lib/python3.8/__init__.py:1690: SyntaxWarning: invalid escape sequence \u
/usr/lib/python3.8/main.py:928: SyntaxWarning: invalid escape sequence \d
/usr/lib/python3.8/new_properties.py:2109: SyntaxWarning: invalid escape sequence \[
/usr/lib/python3.8/wxglade.py:187: SyntaxWarning: invalid escape sequence \d
/usr/lib/python3.8/__init__.py:1690: SyntaxWarning: invalid escape sequence \u
/usr/lib/python3.8/main.py:928: SyntaxWarning: invalid escape sequence \d
/usr/lib/python3.8/new_properties.py:2109: SyntaxWarning: invalid escape sequence \[
/usr/lib/python3.8/wxglade.py:187: SyntaxWarning: invalid escape sequence \d
```

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. I will look through. Probably I just forgot the r for the raw strings.

**Comment by DietmarSchwertberger** [comment]
Can you tell me what the file __init__.py actually looks like? This should be almost empty (just some comments).

**Comment by swt2c** [comment]
What's weird is that I can't reproduce these SyntaxWarnings any more.  It seems like they went away with the latest Python 3.8 beta, so I'm just going to close this.  Sorry for the noise.

**Comment by DietmarSchwertberger** [comment]
The warnings were actually valid.
The warnings were deactivated for 3.8b again. See here: https://bugs.python.org/issue32912
I have changed the strings accordingly in the master branch,

**Comment by swt2c** [comment]
Thanks.  What was further confusing was that part of the path is missing from the warnings.
