### ISSUE TITLE
Deselecting Sash position in a SplitterWindow widget properties generates an error

### ISSUE THREAD

**Issue by steka** [wxGlade/wxGlade#374]
Overview
======
Deselecting Sash position in a SplitterWindow widget properties generates an error.

How to reproduce
============
1. File->New
2. Add a wxFrame
3. Add a SplitterWindow in SLOT 1 of sizer_1
4. Select slitter window in treeview and view its widget properties
5. Select "Sash position" checkbox
6. Deselect "Sash position" checkbox.

...and an Error Dialog will open with the following information:

Reported Error Summary
================
> An internal error occurred
> 
> Error type: <class 'TypeError'>
> Error summary: No summary available
> 
> This is a bug - please report it.

Reported Error Details
==============
> ERROR   : None
> An unexpected error occurred!
> 
> Exception type:      <class 'TypeError'>
> Exception details:   SplitterWindow.SetSashPosition(): argument 1 has unexpected type 'str'
> 
> Application stack traceback:
>   File "U:\My Documents\Tools\wxGlade-0.9.3\new_properties.py", line 388, in <lambda>
>     self.enabler.Bind( wx.EVT_CHECKBOX, lambda event: self.toggle_active(event.IsChecked()) )
>   File "U:\My Documents\Tools\wxGlade-0.9.3\new_properties.py", line 187, in toggle_active
>     self.on_value_edited(self.value, active)
>   File "U:\My Documents\Tools\wxGlade-0.9.3\new_properties.py", line 152, in on_value_edited
>     self._notify()
>   File "U:\My Documents\Tools\wxGlade-0.9.3\new_properties.py", line 176, in _notify
>     self.owner.properties_changed([self.name])
>   File "U:\My Documents\Tools\wxGlade-0.9.3\widgets\splitter_window\splitter_window.py", line 210, in properties_changed
>     self.widget.SetSashPosition(self.sash_pos)
> 
> Date and time:       2019-09-10T18:06:55.784209
> Python version:      3.7.4
> wxPython version:    4.0.6
> wxWidgets platform:  __WXMSW__
> wxGlade version:     0.9.3

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. It should be fixed now in master and REV_0.9.
I did not test 0.9, though.

**Comment by DietmarSchwertberger** [comment]
milestone is 0.9.5, but github is too buggy to accept this input...

**Comment by DietmarSchwertberger** [comment]
released 0.9.5
