### ISSUE TITLE
.desktop file (ubuntu and similar) needs %f in exec key

### ISSUE THREAD

**Issue by tonywallace64** [wxGlade/wxGlade#375]
The exec key of the wxGlade.desktop file needs a %f parameter so that it can be associated with files in a ubuntu system.  My edited desktop file shown below.

[Desktop Entry]
Version=0.7.2
Encoding=UTF-8
Name=wxGlade
Comment=A GUI designer written in Python with the popular GUI toolkit wxPython
Exec=wxglade %f
Terminal=false
Icon=wxglade.xpm
Type=Application
Categories=Development;GUIDesigner;
GenericName=wxGlade

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. It's updated in the repository for 0.9.x and master

**Comment by DietmarSchwertberger** [comment]
released 0.9.5
