### ISSUE TITLE
Add option to store tool references and use with Bind() in generated Python code

### ISSUE THREAD

**Issue by hekkup** [wxGlade/wxGlade#377]
Currently, tool references are not stored at least when generating Python code. Tool ID's cannot be used when binding events to handlers.

```
self.frame_toolbar.AddTool(wx.ID_ANY, "Help", wx.Bitmap("help.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
...
self.Bind(wx.EVT_TOOL, self.onHelpClicked, id=wx.ID_ANY)
```

Preferred way would be to have an option to store references and use them with Bind(). This would be consistent with how menu items are handled.

```
self.helpTool = self.frame_toolbar.AddTool(wx.ID_ANY, "Help", wx.Bitmap("help.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
...
self.Bind(wx.EVT_TOOL, self.onHelpClicked, id=self.helpTool.GetId())
```

**Comment by DietmarSchwertberger** [comment]
I see. I rarely use tool and menu bars and never used them with wxGlade.
It seems that the generated code has never been very helpful.
I need to look into this.

**Comment by DietmarSchwertberger** [comment]
For menu items with and without (attribute) name the generated code looks like this and for Tools it probably should look similar, right?
```
self.frame_menubar.item1 = wxglade_tmp_menu.Append(wx.ID_ANY, "My Menu Item 1", "")
self.Bind(wx.EVT_MENU, self.on_menu_item1, id=self.frame_menubar.item1.GetId())
item = wxglade_tmp_menu.Append(wx.ID_ANY, "My Menu Item 2", "without attribute name")
self.Bind(wx.EVT_MENU, self.on_menu_item2, id=item.GetId())```

As workaround you can use `self.frame_toolbar.GetToolByPos(0)` to retrieve the tool.

I'm sorry that toolbar support is very basic. It would be nice to be able to add 'normal' widgets to toolbars, but that's very low on my priority list. So it probably will not happen except if someone submits code.

**Comment by DietmarSchwertberger** [comment]
Would you mind testing the new branch ISSUE_377 in the repository?
This should bind each tool item right after creation.
names need to be implemented.

**Comment by hekkup** [comment]
I have tested the branch ISSUE_377 and it seems to work. Effectively, it resolves the issue. Thanks!

**Comment by DietmarSchwertberger** [comment]
Fine. I will add some test cases and then integrate it into the master branch.
I will put the optional (attribute) names on my todo list, but not with high priority.

**Comment by hekkup** [comment]
In the longer run, it would be better if the references were stored for each tool individually. The individual references are needed when e.g. setting enabled status of tool.

**Comment by DietmarSchwertberger** [comment]
Sure. Maybe you volunteer to implement this? The main part is to upgrade the editor. The easiest way is to look at all places widgets/menubar/menubar.py with "name" and modify widgets/toolbar/toolbar.py accordingly.

The editor could also be modified to accept e.g. bitmaps dropped to it...

**Comment by DietmarSchwertberger** [comment]
1.0.0a1 is online.
