### ISSUE TITLE
custom widget class cannot have dot

### ISSUE THREAD

**Issue by whdxwym** [wxGlade/wxGlade#378]
I add a wx.adv.TimePickerCtrl by custom widget, but the class entry for input does not allowed dot in the name. the workaround way is input any name in the entry and add a widget first, then modify the class entry in the common page with dot. Is it possible to add pattern match in the class entry so I can insert widgets in wx.adv or wx.dataview?

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. The fix is now in the master and REV_0.9 branches.
