### ISSUE TITLE
Enable adding stretchable space in ToolBar

### ISSUE THREAD

**Issue by hekkup** [wxGlade/wxGlade#380]
Currently only separator is shown in the ToolBar editor.

**Comment by DietmarSchwertberger** [comment]
Well, I could add this to my ToDo list, but the priority would be too low to get implemented in finite time.
Maybe you want to modify the ToolsDialog in widgets\toolbar\toolbar.py to include a type editor for spacers. The type would then not be 0, but 1. If you do this, I will implement the required code generation.

**Comment by DietmarSchwertberger** [comment]
(The type editor would just be a second radio box "Type". Depending on the item being edited, the other radio box would be hidden.)
