### ISSUE TITLE
module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by JMK19** [wxGlade/wxGlade#381]
Date and time:       2019-10-30T08:16:00.348538
Python version:      3.8.0
wxPython version:    4.0.7.post1
wxWidgets platform:  __WXMSW__
wxGlade version:     0.9.4

Accidentally closed wxGlade and need my autosave, but when trying to load my autosave this error comes up.

ERROR   : None
An unexpected error occurred!

Exception type:      <class 'AttributeError'>
Exception details:   module 'time' has no attribute 'clock'

Application stack traceback:
  File "C:\Users\julia\OneDrive\Documents\wxGlade-0.9.4\main.py", line 895, in open_app
    self._open_app(infile)
  File "C:\Users\julia\OneDrive\Documents\wxGlade-0.9.4\main.py", line 907, in _open_app
    start = time.clock()

Thanks for any help!

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. Seems that time.clock() is gone with Python 3.8.
The required modifications are in the repository, in branches REV_0.9 and master.

**Comment by JMK19** [comment]
Thanks! Will close.
