### ISSUE TITLE
Please provide a Dialog example

### ISSUE THREAD

**Issue by emaros** [wxGlade/wxGlade#382]
I have been working on a project where I wanted to have a modal dialog box to obtain information from the user and pass the data back to the main application. I looked through the example directory and found no example on how to do this.

I have been successful with generating a dialog box within wxGlade. I am not sure how to pass the information to the main application.

**Comment by DietmarSchwertberger** [comment]
Yes, I will think about an example.

The wxPython documentation has some code: https://wxpython.org/Phoenix/docs/html/wx.Dialog.html
Typically, you would set some control values after creating the dialog and read them back after the user has hit OK.
```
dlg = MyAskDialog(self)
dlg.text_ctrl1.SetValue("default text")
...
user_text = dlg.text_ctrl1.GetValue()
dlg.Destroy()
```

**Comment by emaros** [comment]
When I try to create an instance of the dialog, I get

`TypeError: Dialog(): arguments did not match any overloaded call:
  overload 1: 'style' is not a valid keyword argument
  overload 2: 'style' is not a valid keyword argument
`
The dialog is invoked by a button press whos callback is in the main frame.

Any suggestions?

**Comment by DietmarSchwertberger** [comment]
I just tried and MyDialog(self) is working for me.

My code looks like this:
```
class MyFrame(wx.Frame):
    ...
    def on_button_show_modal(self, event):  # wxGlade: MyFrame.<event_handler>
        with MyDialog(self) as dlg:
            dlg.text_ctrl_1.SetValue(self.text_ctrl_1.GetValue())
            if dlg.ShowModal() == wx.ID_OK:
                self.text_ctrl_1.SetValue(dlg.text_ctrl_1.GetValue())
...
class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("dialog")
```

**Comment by DietmarSchwertberger** [comment]
The example is now in the master branch.

**Comment by DietmarSchwertberger** [comment]
1.0.0a1 is online.
