### ISSUE TITLE
wxGlade > code generation > grid, propgrid > no import wx.grid, import wx.propgrid generated

### ISSUE THREAD

**Issue by dug9** [wxGlade/wxGlade#385]
Thanks for great tool and the price is right!
I don't get to python often and first time with wxGlade, so took me a while to figure out why generated code wouldn't run from IDLE - it said wx had no grid and no propgrid and context menu confirmed it. I updated python, and piped wxglade again, no diff. then reading your docs I finally saw the pattern and a bit of python experience years ago, bingo - a few imports and worked.

**Comment by DietmarSchwertberger** [comment]
So IDLE still runs the code in the interpreter instance that's running IDLE itself?
I think I will add a note not to run the code inside IDLE or Pythonwin.
There are other IDEs with really good debuggers...

**Comment by dug9** [comment]
I've been running from IDLE by adding the 2 grid imports.
Are you saying I don't need to import wx.grid and import wx.propgrid if I run from command line?
If I run it from (windows 10) command line I find I also have to chop this header stuff from the generated code:
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Mon Jan 20 12:35:35 2020
#

( I am running recent python 3.8.1 - the header stuff might be for early python?)

and if I don't manually add the 2 missing imports, it complains 
    self.grid_1 = wx.grid.Grid(self.window_1_pane_2, wx.ID_ANY, size=(1, 1))
AttributeError: module 'wx' has no attribute 'grid'


________________________________________

So IDLE still runs the code in the interpreter instance that's running IDLE itself?
I think I will add a note not to run the code inside IDLE or Pythonwin.
There are other IDEs with really good debuggers...

**Comment by DietmarSchwertberger** [comment]
OK, I see that I forgot to release an update with a fix for Issue #381 with Python 3.8.
Anyway, if I run a patched wxGlade or the most recent version from branch REV_0.9, I get the correct import code:
```
# generated by wxGlade 0.9.4 on Tue Jan 21 21:02:41 2020
#

import wx
import wx.grid
import wx.propgrid
```
**But: ** If I delete the import code and have "Keep user code" active, it will not be re-created.
So please try with "Keep user code" deactivated.
If you still see the problem, please upload a small example (.wxg and .py file).
If only wx.grid and wx.propgrid were missing, then I would suspect this sequence:
 - create a new file
 - not having edited grid/proprid: generate code
 - add grip/propgrid
 - generate code with "Keep user code"
If this results in missing imports, it needs to be fixed of course.

**Comment by dug9** [comment]
Thanks Dietmar for the detailed suggestions. Now I have trouble making it fail. I don't know what I'm doing right. I'll let you know if it comes back in a reproducible way. -Doug

**Comment by DietmarSchwertberger** [comment]
Anyway, thanks for bringing to my attention that I have to release 0.9.5 for use with Python 3.8.
I will check in the next days whether I can reproduce your problem and by the sequence mentioned above.
If you plan to do more with (wx)Python, you should get a better IDE than IDLE. It really makes a big difference having a proper debugger.

**Comment by DietmarSchwertberger** [comment]
I can reproduce the problem if I first generate code and then later on add a grid or property grid.
This is fixed now in my development branch, which will be soon merged with the master branch.
This bug has been around for many years...
