### ISSUE TITLE
Python 3.8 - fails on startup with reference to time.clock

### ISSUE THREAD

**Issue by johns1c** [wxGlade/wxGlade#387]
I had an offline version will check github code now 

replaced time.clock with time.time in main.py and  wxglade.py and all ok

**Comment by johns1c** [comment]
Sorry, for some reason my version was out of date - you have fixed it.  Many thanks for reviving the project and keeping it up to date

**Comment by DietmarSchwertberger** [comment]
No problem. Unfortunately I forgot for quite some time to fix the .clock problem. 0.9.5 should have been out earlier.
