### ISSUE TITLE
Readme Installation Section does not cover installation

### ISSUE THREAD

**Issue by GadgetSteve** [wxGlade/wxGlade#388]
The current installation section does not even mention the word installation - it only covers starting wxGlade. 

Since wxGlade is **not** available on PyPi this is not the majority of developers first guess `pip install wxglade` so googling to find the source forge page is necessary. Even then it is not 100% clear where to install the content of downloaded zip file.

**Comment by DietmarSchwertberger** [comment]
I'm not a fan of developer tools that install themselves into the target system. So it is not a package, but a program. 
Yes, there is no installation. Just run it. The same as with the generated code.
It does not matter where you unpack it.

I will think how to make this clearer.

**Comment by DietmarSchwertberger** [comment]
Ah, did not see the PR. Will check it.

**Comment by DietmarSchwertberger** [comment]
Had to adapt the rst file to the restrictions of github. Will update the Sourceforge page and the README.txt in the next days.

**Comment by DietmarSchwertberger** [comment]
1.0.0a1 is online. Readme.txt will also be updated with a2.
