### ISSUE TITLE
wxGlade event_handlers block not found, when adding a class

### ISSUE THREAD

**Issue by RSabet** [wxGlade/wxGlade#391]
This is just a minor issue:

When setting wxGlade to `keep user code` and adding a simple
``` python
class Test():
    pass
```
 after the `# end wxGlade`, where user code should go (see example below), this warning will be produced and the generated code contains a line like
`<15890495231133762465125wxGlade event_handlers ClassName># end of class AboutDialog`

This can easily be fixed: when moving the class to a separate file and importing it, wxGlade works fine again.

``` python
[...]
# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_1.Add((0, 0), 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_CLOSE, self.on_close, self)
        # end wxGlade
        class Test():
            pass

    def on_close(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'on_close' not implemented!")
        event.Skip()

# end of class MyFrame
```

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. This should be fixed now. The regex did match leading spaces, which was not necessary.

**Comment by RSabet** [comment]
Thanks, i can conform this fixed the issue.

**Comment by DietmarSchwertberger** [comment]
Release 0.9.6 tagged / draft available
