### ISSUE TITLE
Error when setting speccific font

### ISSUE THREAD

**Issue by mlshore** [wxGlade/wxGlade#393]
Trying to change text box font to Courier

ERROR   : None
An unexpected error occurred!

Exception type:      <class 'KeyError'>
Exception details:   400

Application stack traceback:
  File "C:\python\wxGlade-0.9.5\font_dialog.py", line 67, in choose_specific_font
    self.font_weights_from[font.GetWeight()],

Date and time:       2020-05-11T22:00:22.153751
Python version:      3.8.2
wxPython version:    4.1.0
wxWidgets platform:  __WXMSW__
wxGlade version:     0.9.5

**Comment by DietmarSchwertberger** [comment]
Thanks for testing 4.1.0. There are probably more incompatibilities/deprecations waiting.
Fixes are now in the current repository branches.
Unfortunately I don't have many test cases yet that test interactive editing. I would like to improve this with 1.0 or 1.1.

When you hit a roadblock, just go to 4.0.x.

**Comment by mlshore** [comment]
Thanks Dietmar

 

For the record, wxGlade is working like a Dream for me – an awesome product.   I’ve just started with it but plan on using it fairly extensively going forward as I try to wean myself off using Delphi for Desktop Apps!  

 

Regards

 

Malcolm

**Comment by DietmarSchwertberger** [comment]
Release 0.9.6 tagged / draft available
