### ISSUE TITLE
[Feature] Add wx.Button support for image direction

### ISSUE THREAD

**Issue by nikita-moor** [wxGlade/wxGlade#394]
On adding an image to the button, method [SetBitmap](https://wxpython.org/Phoenix/docs/html/wx.AnyButton.html#wx.AnyButton.SetBitmap) has second parameter `dir` to put the picture above the label (wx.TOP), on the left or right or below.

Adding of the line to the "Code to be inserted after", such as
```python
self.myButton.SetBitmapPosition(wx.TOP)
```
doesn't help, because it's called (in `__init__`) before the image is assigned (in `__set_properties`).

**Comment by DietmarSchwertberger** [comment]
I will look into this. Seems to be a useful feature that I did not know before...
As workaround, the master branch should work. There the "code to be inserted after" and also the properties code will be inserted after the SetBitmap call.

![grafik](https://user-images.githubusercontent.com/5512021/82348006-9a6d1280-99f8-11ea-9108-2c34b8c249d4.png)

**Comment by DietmarSchwertberger** [comment]
Btw. `BitmapButton` does have styles `wxBU_LEFT/RIGHT...`
In wxWidgets `BitmapButton` is just an alias for `Button` with a different constructor.
At some point in future, both widgets should be unified in wxGlade as well.

**Comment by DietmarSchwertberger** [comment]
Ah, sorry, the LEFT/RIGHT styles are for the label alignment only.

**Comment by DietmarSchwertberger** [comment]
First support is in the repository (branch master).
Test cases are missing. Generation for Perl and Lisp is just a guess...

**Comment by nikita-moor** [comment]
It works very nice, thank you! Should I close this task?

**Comment by DietmarSchwertberger** [comment]
"Pending" is the right label. I will close it when 1.0 is released in a few months.

**Comment by DietmarSchwertberger** [comment]
1.0.0a1 is online.
