### ISSUE TITLE
Command line version fail

### ISSUE THREAD

**Issue by mlshore** [wxGlade/wxGlade#395]
I'm using wxglade.pyw on Windows and have struck a minor issue.
The command line invocation 
   python wxglade.py[w]  -h | --help works fine.   

...and the command line invocation 
   python wxglade.py --version works fine

However, the command line invocation
   python wxglade.pyw --version
fails with the error
  File "wxglade.pyw", line 47, in <module>
    if isinstance(code, types.IntType) and code != 0:
AttributeError: module 'types' has no attribute 'IntType'

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. It should be fixed in the current repository branches.

**Comment by DietmarSchwertberger** [comment]
Release 0.9.6 tagged / draft available
