### ISSUE TITLE
Exiting wxGlade

### ISSUE THREAD

**Issue by mlshore** [wxGlade/wxGlade#396]
When running wxGlade from the command line, terminating the application works fine.

When running wxGlade from IDLE, terminating the wxGlade system (either with File>Exit or closing the window) removes all design work, but does not exit. This is dangerous as trying again suggests you might like to save your project (and hence destroy it).

**Comment by DietmarSchwertberger** [comment]
This is probably similar to running with `python -i`.
When you debug wxGlade, it makes sense to run it from an IDE. If not, just run the wxglade.py file. 
Other IDEs are doing better...

**Comment by DietmarSchwertberger** [comment]
On other IDEs you can optionally select options like "external console waits on exit".
