### ISSUE TITLE
Remove notebook tab removes the wrong tab.

### ISSUE THREAD

**Issue by mlshore** [wxGlade/wxGlade#397]
I have a project which has a notebook widget with two tab panes.   I right click on the second pane and select "Add Notebook Tab".   This adds a third tab, as expected.

I select the notebook widget, and check the widget tab.  It shows in the "Tabs" table at the bottom the three tabs.   The Apply button is greyed out.   I select the third tab (which I have just added), and click Remove.   The table removes the third tab and I am left with the two original tabs I had.   However, when I apply the change, the right hand pane structure shows the second tab having been removed, and the first and third remain.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. A fix is now in all current branches of the repository.
I did not take care of the fact that deleting a row in the grid would also trigger a callback storing the current row.

**Comment by DietmarSchwertberger** [comment]
Release 0.9.6 tagged / draft available
