### ISSUE TITLE
wx._core.wxAssertionError with sizer

### ISSUE THREAD

**Issue by Froyok** [wxGlade/wxGlade#398]
**Operating system**: Windows 10
**wxPython version**: 4.1.0
**wxGlade version**: 0.9.5

I recently upgraded from wxPython 4.0.7 to 4.1.0 and there is now a wx._core.wxAssertionError with sizers generated via wxGlade.

**Stack**:
```
Traceback (most recent call last):
  File "E:\DATA\Desktop\ReproBug\LibUI.py", line 61, in OnInit
    self.frameMain = classFrameMain(None, wx.ID_ANY, "")
  File "E:\DATA\Desktop\ReproBug\LibUI.py", line 26, in __init__
    self.__do_layout()
  File "E:\DATA\Desktop\ReproBug\LibUI.py", line 44, in __do_layout
    layoutColumnBase.Add(layoutTopRow, 0, wx.ALIGN_CENTER_VERTICAL, 0)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_VERTICAL)" failed at ..\..\src\common\sizer.cpp(2077) in wxBoxSizer::DoInsert(): Vertical alignment flags are ignored in vertical sizers
OnInit returned false, exiting...
```

**Repro steps**:
I attached files to reproduce the issue, simply run the _LibUI.py_ file. I provided the wxGlade template as well.
[assert_files_repro.zip](https://github.com/wxGlade/wxGlade/files/4681466/assert_files_repro.zip)

**Notes**:
Seems to be related to this issue, which mention a previous warning is now marked as error:
https://github.com/wxWidgets/Phoenix/issues/1635

Also my repro files might seem convoluted but it's an extract from a bigger application from which I removed any unnecessary elements to isolate and reproduce the bug.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting.
Please try the master or REV_0.9 branch from the repository.

**Comment by Froyok** [comment]
I gave a try at master (v0.9.9pre) and REV_0.9 (v0.9.6) and I don't get the assert, it seems to be fixed in both branches. :+1:

**Comment by DietmarSchwertberger** [comment]
Release 0.9.6 tagged / draft available
