### ISSUE TITLE
Generate files with consistent file ending

### ISSUE THREAD

**Issue by udifuchs** [wxGlade/wxGlade#399]
wxGlade generates files with windows line ending (\r\n) on windows and Unix line ending (\n) elsewhere. This creates large differences when switching between development environments.

The attached patch uses the current file ending, if exists, and falls back to the old functionality otherwise.

Another option would be to just always use Unix file ending. Conditional code generation is just a source for confusion for CI systems. Today, even Notepad supports the Unix file ending.

```
index 34c1c449..17518ee1 100644
--- a/common.py
+++ b/common.py
@@ -364,6 +364,13 @@ def save_file(filename, content, which='wxg'):
 
     outfile = None
     try:
+        if os.path.isfile(filename):
+            infile = open(filename, 'r')
+            first_line = infile.readline()
+            win_line_ending = first_line.endswith("\r\n")
+        else:
+            win_line_ending = sys.platform.startswith("win")
+
         if need_backup:
             backup_name = filename + config.preferences.backup_suffix
             if os.path.isfile(backup_name):
@@ -378,7 +385,7 @@ def save_file(filename, content, which='wxg'):
 
         outfile = open(filename, 'wb')
         for line in content:
-            if sys.platform.startswith("win"):
+            if win_line_ending:
                 line = line.replace(b"\n", b"\r\n")
             outfile.write(line)
         outfile.close()
```
[win_line_ending_patch.txt](https://github.com/wxGlade/wxGlade/files/4706219/win_line_ending_patch.txt)

**Comment by DietmarSchwertberger** [comment]
Thanks. Had do adapt as the open 'infile'  is a problem when using rename on the file.

**Comment by DietmarSchwertberger** [comment]
The patch is now in master and REV_0.9 branches.

**Comment by DietmarSchwertberger** [comment]
Release 0.9.6 tagged / draft available
