### ISSUE TITLE
Command line code generation errors

### ISSUE THREAD

**Issue by udifuchs** [wxGlade/wxGlade#400]
Trying to generate python code from the command line fails for many widgets. The problem is always with calls to common.app_tree.refresh() when common.app_tree is None.

The attached patch fixes all the crashes that I encountered with my WXG files. You might want to add checks around all common.app_tree.refresh()  calls.

It was easy to find all these crashes by defining the environment variable WINGDB_ACTIVE. The tricky part was to discover this variable. You might want to add it to the documentation.

[command_line_code_generation_patch.txt](https://github.com/wxGlade/wxGlade/files/4707105/command_line_code_generation_patch.txt)

**Comment by DietmarSchwertberger** [comment]
Thanks. I will integrate the patch.
You can set config.debugging to True to get the exceptions raised.
If you're using a different IDE: is there an easy way to detect whether a program is running in the debugger? Then I would add this detection line to config.py

Anyway, I will move the debugging option to the start of the config file.

**Comment by DietmarSchwertberger** [comment]
It's in the master branch now.
I have added two more fixes and also test cases (test_cli.py).

**Comment by udifuchs** [comment]
When I run wxglade for the first time after pulling from git, I got the warnings below. I'm not sure what triggered python to show these warnings. In subsequent runs they did not show up.

Anyway, the attached trivial patch fixes these warnings.

[fix_warnings.txt](https://github.com/wxGlade/wxGlade/files/4707995/fix_warnings.txt)

```
INFO    : Load code generators:
/opt/APE-pypi/wxGlade/edit_base.py:414: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not self.CHILDREN is 0:
/opt/APE-pypi/wxGlade/edit_base.py:571: SyntaxWarning: "is" with a literal. Did you mean "=="?
  can_add_sizer = self.parent.IS_SIZER or self.parent.CHILDREN is 1
/opt/APE-pypi/wxGlade/edit_base.py:743: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if common.adding_sizer and self.parent.CHILDREN is not 1 and not self.IS_SLOT:
/opt/APE-pypi/wxGlade/edit_base.py:758: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if common.adding_sizer and self.parent.CHILDREN is not 1 and not self.IS_SLOT:
/opt/APE-pypi/wxGlade/edit_base.py:769: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if typename=="sizer" and self.parent.CHILDREN is not 1:
/opt/APE-pypi/wxGlade/edit_base.py:777: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.parent.CHILDREN is not 1 and widget.IS_SIZER:
INFO    : Load sizer generators:
```

**Comment by DietmarSchwertberger** [comment]
Thanks. I think I have seen these and thought I had fixed them already.
You're using Python 3.8, right?
I will add the patch probably tomorrow.

**Comment by udifuchs** [comment]
> You're using Python 3.8, right?

Yes, I'm using Python 3.8. And I figured out how to reproduce the warnings. If I delete the __pycache__ folder, they show up again. Apparently Python only shows these warnings during compilation.

**Comment by DietmarSchwertberger** [comment]
The patch is now in the master branch. Thanks.
