### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by caop288** [wxGlade/wxGlade#401]
ERROR   : An internal error occurred while Save File "b'JSQ.wxg'"
An unexpected error occurred!

Exception type:      <class 'UnicodeDecodeError'>
Exception details:   'gbk' codec can't decode byte 0xab in position 2383: illegal multibyte sequence

Application stack traceback:
  File "D:\1P_Tool\wxGlade-0.9.6\main.py", line 1025, in _save_app
    common.save_file(filename, obuffer, 'wxg')
  File "D:\1P_Tool\wxGlade-0.9.6\common.py", line 377, in save_file
    win_line_ending = infile.readline().endswith("\r\n")

Date and time:       2020-06-09T23:27:47.501355
Python version:      3.7.7
wxPython version:    4.1.0
wxWidgets platform:  __WXMSW__
wxGlade version:     0.9.6

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. Seems that issue #399 should have been more robust...
Could you please check whether the current REV_0.9 branch fixes this?

I have changed lines #374 to 402 there:
```
    try:
        if which=="codegen":
            if os.path.isfile(filename):
                with open(filename, 'rb') as infile:
                    win_line_ending = infile.readline().endswith(b"\r\n")
            else:
                win_line_ending = sys.platform.startswith("win")

        if need_backup:
            backup_name = filename + config.preferences.backup_suffix
            if os.path.isfile(backup_name):
                os.remove(backup_name)
            os.rename(filename, backup_name)
            config.backed_up[filename] = True

        # create necessary subdirectories on demand
        directory = os.path.dirname(filename)
        if directory and not os.path.isdir(directory):
            os.makedirs(directory)

        outfile = open(filename, 'wb')
        for line in content:
            if which=="codegen" and win_line_ending:
                line = line.replace(b"\n", b"\r\n")
            outfile.write(line)
        outfile.close()
    finally:
        if outfile:
            outfile.close()
```

**Comment by DietmarSchwertberger** [comment]
This is already the updated version:
https://github.com/wxGlade/wxGlade/releases/tag/v0.9.6fix
