### ISSUE TITLE
KeyError  (This is a bug - please report it)

### ISSUE THREAD

**Issue by caop288** [wxGlade/wxGlade#402]
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'KeyError'>
Exception details:   'flag'

Application stack traceback:
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python37\lib\site-packages\wx\core.py", line 3383, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "D:\1P_Tool\wxGlade-0.9.6fix\edit_sizers\edit_sizers.py", line 575, in change_sizer
    widget.properties["flag"]._check_value()

Date and time:       2020-06-11T22:49:10.913183
Python version:      3.7.7
wxPython version:    4.1.0
wxWidgets platform:  __WXMSW__
wxGlade version:     0.9.6

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting.
This is probably triggered by a toplevel sizer.
As workaround,  place `if "flag" in widget.properties: ` at the beginning of line 575 of edit_sizers.py.
I can update the repository and release file only on sunday.

**Comment by DietmarSchwertberger** [comment]
A fix is in the repository and also here:
https://sourceforge.net/projects/wxglade/files/wxglade/0.9.6/
