### ISSUE TITLE
Bug when changing menu type using arrow keys

### ISSUE THREAD

**Issue by davidkreynolds** [wxGlade/wxGlade#404]
Using arrow keys when changing menu type in Edit Menus, I get:
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'TypeError'>
Exception details:   ListCtrl.SetItem(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'int'
  overload 2: argument 3 has unexpected type 'str'

Application stack traceback:
  File "C:\Developer\wxGlade\widgets\menubar\menubar.py", line 391, in on_type_edited
    self._on_edited(event, "type", str(self.type.GetSelection()))
  File "C:\Developer\wxGlade\widgets\menubar\menubar.py", line 387, in _on_edited
    compat.ListCtrl_SetStringItem(self.items, self.selected_index, colname, value)

Date and time:       2020-06-19T16:53:16.353099
Python version:      3.8.3
wxPython version:    4.1.0
wxWidgets platform:  __WXMSW__
wxGlade version:     0.9.9pre

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. This should be fixed now.
I'm rarely using menus, so I did not notice this...
