### ISSUE TITLE
Menu editor - buttons not appearing in tab order

### ISSUE THREAD

**Issue by davidkreynolds** [wxGlade/wxGlade#406]
Certain buttons, namely, < > Add Remove and the list view containing already added options do not appear in the tab order in the menu editor.
I use a screen reader, and tab around the form using the keyboard. For a person with sight, this won't be a problem, as the buttons are visible on the screen.
I'd imagine this would be pretty low priority, but it would be nice and less confusing for a new VI user.

**Comment by DietmarSchwertberger** [comment]
Please try the version from the master branch.
This has many improvements for screen reader compatibility, including tab order.
The, original issue for screen reader related improvements was #317. There's also a discussion thread.

**Comment by davidkreynolds** [comment]
Yes, I've downloaded the master now, and it works a lot better. Thanks.
