### ISSUE TITLE
<class 'AttributeError'> <class 'statusbar.statusbar.EditStatusBar'>

### ISSUE THREAD

**Issue by cddrgn** [wxGlade/wxGlade#407]
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'AttributeError'>
Exception details:   <class 'statusbar.statusbar.EditStatusBar'> object has no attribute '_is_toplevel'

Application stack traceback:
  File "C:\Users\user\Downloads\wxGlade-0.9.6fix2\wxGlade-0.9.6\tree.py", line 503, in begin_drag
    clipboard.begin_drag(self, widget)
  File "C:\Users\user\Downloads\wxGlade-0.9.6fix2\wxGlade-0.9.6\clipboard.py", line 43, in begin_drag
    elif widget._is_toplevel:
  File "C:\Users\user
[wxglade_out.txt](https://github.com/wxGlade/wxGlade/files/4811737/wxglade_out.txt)
![screenshot](https://user-images.githubusercontent.com/66864139/85259773-7600bd80-b41e-11ea-8faf-557ba66eea10.jpg)

\Downloads\wxGlade-0.9.6fix2\wxGlade-0.9.6\new_properties.py", line 2972, in __getattr__
    raise AttributeError("%r object has no attribute %r" %(self.__class__, attr))

Date and time:       2020-06-22T00:09:31.713465
Python version:      3.8.2
wxPython version:    4.1.0
wxWidgets platform:  __WXMSW__
wxGlade version:     0.9.6

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. A fix is in the repository, branch REV_0.9.
This just avoids the error.
It does not implement features, though: drag'n'drop and copy / paste of status, tool and menu bars is not supported yet.
This may change in revision 1.0 or 1.1, though.

**Comment by DietmarSchwertberger** [comment]
1.0.0a1 is online.
