### ISSUE TITLE
Error Exporting Separate file for each class

### ISSUE THREAD

**Issue by dracossan** [wxGlade/wxGlade#408]
Hi,

I try to export the code with the option "Separate file for each class" and get the error message popup:
"Error generating Code: Output directory does not exist"

No issue saving the code with a single file in same directory.

Thanks

_Using latest git branch version_

![Screenshot from 2020-06-26 12-39-12](https://user-images.githubusercontent.com/54093207/85821001-3cc3a700-b7aa-11ea-88a9-15440d8a3ed6.png)

**Comment by DietmarSchwertberger** [comment]
I have tried today and did not see problems.
Is "Output Path" really set to a valid directory (or just a dot for the same directory as the .wxg file)?

There is room for improvement, though. On switching the output option, a valid directory should be inserted automatically and also an empty path should be accepted.

**Comment by dracossan** [comment]
Ok. working like this. have to change the output file name to a folder name. Understood. 

Agree, maybe some warning or simply get the parent folder of the ouput file name could be proposed :)

Thanks
