### ISSUE TITLE
Can not import the preview module from file ./wxglade_out.py

### ISSUE THREAD

**Issue by fpusersuggest** [wxGlade/wxGlade#412]
Hi,
I have the following error:

**Can not import the preview module from file ./wxglade_out.py
The details are written to the log file** 

when I click on the preview button.
In the log file  /home/myusername/.wxglade/wxglade.log
there isn't written anything about the error.
I also tried to change the output path but nothing is changed.

**Comment by DietmarSchwertberger** [comment]
This means that importing the preview code fails completely.
Is this with all .wxg files? Can you isolate the problem into a small sample file?

What is the version and the platform?

**Comment by fpusersuggest** [comment]
It's not with all the wxg files. It started with the same project when I added a sizer and some other object like one statictext, a line, and one textctrl. Then with diff I tried to see the difference.. after that I tried to remove the object I have added. To the end I have to file that are pretty the same but one work an the other not work.
Here is the diff:
    $ diff xxxxxx-0.3.wxg NGxxxxxxx.wxg 
    2c2
    < 
    ---
    > 

I also tried to remove __pycache__ directory.. but nothing was changed.
It's very weird.

**Comment by DietmarSchwertberger** [comment]
Could you please try with a recent version? At least 0.9.6 or better from the github master branch?

**Comment by fpusersuggest** [comment]
Yes, I downloaded the 0.9.6 from sourceforge, and it's the same.
I also tried to rename the three file under /home/myuser/.wxglade, but nothing.

**Comment by DietmarSchwertberger** [comment]
Then please upload a small sample .wxg.
From the diff above I can't conclude anything.

**Comment by DietmarSchwertberger** [comment]
Ah, hold on. I see at least one possible source of the problem.

**Comment by DietmarSchwertberger** [comment]
Well, probably it's not related. There's a bug that enables you to add a menu separator as toplevel menu. That will fail.
Could you please check whether you have a menu separator at level 0?

**Comment by fpusersuggest** [comment]
I think I have found the problem but it's really strange. Depend of the . (dot) in the name of the file. All the file that have a dot in the name (excluded the .wxg extension) don't work. Indeed the problem is appeared when I renamed my app with myapp-0.3.wxg

**Comment by DietmarSchwertberger** [comment]
OK, I have updated the master branch to replace "." with "_" for the preview filename.
All in all there's some room for improvement on this. Maybe I will find the time...

If you don't want to update, to the git version, you may fix the issue yourself.
Go to `application.py`. In `Application._get_preview_filename` add a line with `.replace`:
```
                dirname, basename = os.path.split(self.filename)
                basename, extension = os.path.splitext(basename)
                basename = basename.replace(".", "_")
                if not os.path.exists(dirname):
                    error = "Directory '%s' not found"%dirname
                elif not os.path.isdir(dirname):
                    error = "'%s' is not a directory"%dirname
```

Thanks for reporting.

**Comment by fpusersuggest** [comment]
it works! 
wow, so fast!! thank you very much!!
