### ISSUE TITLE
Can no longer add control to a slot

### ISSUE THREAD

**Issue by davidkreynolds** [wxGlade/wxGlade#413]
Having cloned latest master, I can no longer place a control in a slot either in dialog or frame. Steps:
1.Add a dialog/frame to form.
2.Select a control, button or whatever.
3.Press F2 to pass focus to the application tree.
4.Arrow down to slot 0, and press enter.
This used to place the selected control into the slot, in this case,slot 0, but it doesn't.

**Comment by DietmarSchwertberger** [comment]
OK, I will check this asap.

**Comment by DietmarSchwertberger** [comment]
OK, should work again. I did modify the Enter key to show/expand toplevel widgets in the Tree view and forgot that Enter should add a widget. Sorry for this.

**Comment by davidkreynolds** [comment]
No problem. It’s a complex application, and things have changed since you first thought of the idea.

 

With much gratitude,

 

David.
