### ISSUE TITLE
virtual keyword for c++ event handlers missing. 

### ISSUE THREAD

**Issue by pm100** [wxGlade/wxGlade#414]
I just downloaded 9.6.fix2 from sourceforge. The fix for adding 'virtual' to event handlers is not there (issue 370). If I look in the file in github its correct, but its not in the 'release' build.

**Comment by DietmarSchwertberger** [comment]
I did not change this for 0.9.
See the comment in the original issue:
`The latest commit in the master branch has the virtual methods again. I would not want to change this in the 0.8 or 0.9 series if not absolutely necessary. Test cases are not adjusted yet. I will do so after feedback.`

Is the master branch no option for you?
I'm currently working a lot on this. It might not be 100% stable at the moment, but usually I will fix bugs quite fast.

**Comment by pm100** [comment]
TY, I hand edited it.
