### ISSUE TITLE
Accessibility - control properties

### ISSUE THREAD

**Issue by davidkreynolds** [wxGlade/wxGlade#415]
This is hard to explain, but:
When accessing the properties for a control, I can navigate to the various tabs, but within these tabs nothing much is spoken, there are lots of checkboxes which speak as unchecked, and buttons which when pressed experimentally ask for a file name.
Trying to get for example to StockItem currently can't be done. I've even tried with mouse simulation to no effect.
It looks like a pretty tricky and complex window, so I'm not expecting it to be a quick fix,
Thanks.

**Comment by DietmarSchwertberger** [comment]
You are on Windows and using NVDA, right?
Which Python and wxPython versions are you using?
There are some which have problems.
When you go to Preferences -> Accessibility, do you get a warning message like this?

`Please be warned that your version of wxPython
probably does not support screen readers very well`

**Comment by DietmarSchwertberger** [comment]
P.S.: wxPython versions with problems are at least 4.0.4 to 4.0.7 on 32 bit Python on Windows.
The 64 bit versions seem to have no problems.

**Comment by davidkreynolds** [comment]
Dietmar,

 

I don’t get this message. I’m using the latest version of jaws, windows 64-bit, python 3.8 and the latest version of WXPython.

I’ve also tried with NVDA with similar results,

 

David.

**Comment by DietmarSchwertberger** [comment]
That's strange.

I'm testing with NVDA. Python 3.6.4 and wxPython 4.1.0:
 - open the dialog example
 - select the OK button
 - press F10 to focus the "Widget" tab
 - repeatedly press Tab to navigate through

The NVDA log window is showing me:
```
tab control
Enable Stockitem  check box  checked
combo box  OK  collapsed
Enable Bitmap  check box  not checked
 ...   button
Enable Disabled bitmap  check box  not checked
 ...   button
Enable Pressed bitmap  check box  not checked
 ...   button

```
Everything seems fine to me.
The "Label" property is skipped as OK has a stock item and therefore this one is disabled.

**Comment by davidkreynolds** [comment]
OK Dietmar,

I enabled the checkbox label workaround, and all is well. When I tab to the checkboxes they read out, and I can select the button widget tab, and enable stockitem etc,

 

Many thanks,

 

David.

**Comment by DietmarSchwertberger** [comment]
Great.
On the first program start, I should probably check for some registry keys which indicate the presence of a screen reader and give the user some information about how to enable the accessibility options:
```
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\nvda.exe
Computer\HKEY_CURRENT_USER\Software\Freedom Scientific\JAWS
Computer\HKEY_CLASSES_ROOT\AppID\C:\Program Files\Freedom Scientific\JAWS
```
I have  put this on my list.
At the moment I'm working on better accessibility of the grid based properties like Events etc.

**Comment by davidkreynolds** [comment]
Dietmar,

 

That’s fine. If ever you need anything tested before release, please let me know, I’d be happy to help,

 

David.

**Comment by DietmarSchwertberger** [comment]
I have just committed changes to check for screen readers on startup on Windows.
You may try it by deleting the configuration file at `C:\Users\...\AppData\Roaming\wxglade\wxglade.ini`
I have tested with NVDA.

**Comment by davidkreynolds** [comment]
Dietmar,

 

It isn’t currently working with latest version of JAWS.

Are there any registry entries you’d like me to check?

**Comment by DietmarSchwertberger** [comment]
I'm checking for this:
`\HKEY_CURRENT_USER\Software\Freedom Scientific\JAWS`

The check is done at the bottom of `msw.py`

**Comment by davidkreynolds** [comment]
Looks right to me.

Time for debug in VSCode,

**Comment by DietmarSchwertberger** [comment]
You may add this to the end of msw.py:
```
print( "check_for_screen_reader", check_for_screen_reader() )
```
It should print out "JAWS".

But the wxglade.ini file needs to be deleted before. If it's there, the check is not performed.

**Comment by davidkreynolds** [comment]
Dietmar,

 

I added that line, and nothing got printed.

I’m currently working through the code to check where wxglade.ini is created, and where the screen reader check is actually performed,

 

David.

**Comment by DietmarSchwertberger** [comment]
Is it really at the end of the file and without indentation? It should at least print "check_for_screen_reader None".

Only if wxglade.ini does not exist, the check is done at all:

See wxglade.py around line 360:
```
if not os.path.exists(config.rc_file):
    config.inform_screen_reader = msw.check_for_screen_reader()
```

**Comment by davidkreynolds** [comment]
I actually did a print within the if block, but still nothing. It may be that my screen reader isn’t recognizing it.

Once I leave the program, wxglade.ini exists.

At which point do you warn the user about setting accessibility options?

Thanks,

**Comment by DietmarSchwertberger** [comment]
In main.py wxGlade.OnInit the inform_screen_reader variable is checked and a delayed message box should pop up:
```
        if config.inform_screen_reader:
            message = ("It seems you have a screen reader software installed.\n"
                       "Please be aware that there are some options to improve wxGlade accessibility\n"
                       "with screen readers.\n"
                       "See menu Edit -> Preferences -> Accessibility.")
            wx.CallLater(1000, wx.MessageBox, message, "Accessibility Info")
```

**Comment by davidkreynolds** [comment]
Dietmar,

 

I don’t think either screen reader will pick that up.

Is it possible to have it as a message box with an OK button, and an exclamation ping?

 

Thanks,

**Comment by DietmarSchwertberger** [comment]
Replace the `if config.inform_screen_reader:` with `if True:` for testing whether you will be informed.
