### ISSUE TITLE
Referenced before assignment exception thrown when editing menubar

### ISSUE THREAD

**Issue by jackbradach** [wxGlade/wxGlade#416]
Caught an exception when trying to add a menubar:

> Exception type:      <class 'UnboundLocalError'>
> Exception details:   local variable 'item' referenced before assignment
> 
> Application stack traceback:
>   File "/usr/local/src/wxGlade/widgets/menubar/menubar.py", line 638, in edit_menus
>     if not self.value: dialog.add_item(None)
>   File "/usr/local/src/wxGlade/widgets/menubar/menubar.py", line 294, in add_item
>     self._add_new_item(self.default_item)
>   File "/usr/local/src/wxGlade/widgets/menubar/menubar.py", line 284, in _add_new_item
>     if item[1]=="---" and item_level==0: return wx.Bell()

Reproduction instructions:
1. Start wxGlade (0.9.9pre on Python 3.78 and wxPython 4.1.0)
2. Add a frame to empty application.
3. Tick the 'has menubar' option in frame's widget tab.
4. Chose "edit menus" from resultant frame_menubar widget.

**Comment by jackbradach** [comment]
In widgets/menubar/menubar.py[284,286]:

```
if item[1]=="---" and item_level==0: return wx.Bell()
indent = "    " * item_level
item = list(unindented_item)
```
Reordering that so line 286 is above line 284 fixes this.

**Comment by DietmarSchwertberger** [comment]
Thanks a lot. It's fixed now in the repository.
