### ISSUE TITLE
* and & operators c++

### ISSUE THREAD

**Issue by rcraig12** [wxGlade/wxGlade#417]
Hi is it possible to have a preference set for how these are output in c++?

The common approach as I understand it is to use:

             wxTextCtrl *txtTitle; (The same approach is common for the '&' operator)

The thinking being that the variable is the pointer and not the type. Presently the source code generated is wxTextCtrl* txtTitle;

It probably sounds small in terms of issues however when I have to edit the header files to follow our project standards I am sure you can understand how tedious that can become :)

I know it is preference really but set_properties(); and  do_layout(); would be nice if they are SetProperties(); and DoLayout(); Or at least some kind of option to change from snake case to camel case in the generator panel :)

As an additional the ability to prevent all the glade applied remarks through the generated code would also be great!

**Comment by DietmarSchwertberger** [comment]
I don't use C++, so I did not notice. When using C, I always placed the space before the asterisk. I'm surprised that there is a different style...
At some points (e.g. event handlers) the other style is used already:
```virtual void onStartConverting(wxCommandEvent &event); // wxGlade: <event_handler>```

I would prefer to switch to the new style. Making it configurable makes the generation code look uglier.
Would you mind asking on the mailing list whether someone has objections against?

`set_properties` and `do_layout` are gone already in the master branch. The generated code now looks more like what a human being would write.

**Comment by DietmarSchwertberger** [comment]
P.S.: Does deactivating "Mark code blocks" not work for you?

**Comment by rcraig12** [comment]
OK So I use 0.9.5... How far is this behind the repo? I only ask because of the snake case / camel case query.

So if I can use an example....

int* a, b; 

The above example could be misread that both a and b are pointers of type int.

If expressed as:

int *a, b;

It is then clear that a is a pointer of type int where as b is not a pointer and of type int.

I am also aware that there is a convention that would have the declaration int * var. So I do appreciate there is no real hard and fast rule. Only reason I came here was because the team were complaining about the int* var approach and wondered if it could be amended or some kind of pref setting to allow for coding standards.

so the choices could be int* var, int * var and int *var. However in all situations as you have rightly shown when using the variable *var and &var are being handled :)

Hope that makes sense :)

**Comment by rcraig12** [comment]
> P.S.: Does deactivating "Mark code blocks" not work for you?

No the remarks are all there irrespective of the choice made....

**Comment by DietmarSchwertberger** [comment]
The master branch is a year behing and a major internal restructuring towards maintainability. 0.9 will not see any feature updates.


Please post to the list. Not everyone is following the issues here.
I will look into the remarks.

**Comment by DietmarSchwertberger** [comment]
About the remarks:

Use the master branch, change line 351 of codegen/init.py:
```
self._mark_blocks = True if not self._overwrite else app.mark_blocks
```
I will upload the change soon, but need to make sure it does not break anything.

**Comment by DietmarSchwertberger** [comment]
Well, uploaded the change.

**Comment by rcraig12** [comment]
That has fixed the remarks toggle. Many thanks!

**Comment by DietmarSchwertberger** [comment]
Please post to the list for a majority opinion on * and &.

**Comment by DietmarSchwertberger** [comment]
I'm preparing an 1.0 (alpha) release. If you want to make this request into 1.0, you should post to the list soon.
Otherwise I'll close the issue.
