### ISSUE TITLE
Custom classes are not generated correctly

### ISSUE THREAD

**Issue by udifuchs** [wxGlade/wxGlade#418]
The WXG file 
[test_grid.wxg.txt](https://github.com/wxGlade/wxGlade/files/4942489/test_grid.wxg.txt) contains a custom class MyGrid. wxGlade used to generated the correct code:
```
self.grid = my_grid.MyGrid(self, wx.ID_ANY, size=(1, 1))
```
Now, it generates:
```
self.grid = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))
```
The commit that broke this is 948433a239159085329a2d0554ba38afcddcc3fb.

**Comment by DietmarSchwertberger** [comment]
Thanks for testing the master branch. I will look into this ASAP.

**Comment by DietmarSchwertberger** [comment]
A fix is in the repository and test case added.
