### ISSUE TITLE
no_custom_class property ignored

### ISSUE THREAD

**Issue by udifuchs** [wxGlade/wxGlade#419]
Thanks for the quick fix for issue #418. This issue seems closely related.
The WXG file [test_no_custom_class.wxg.txt](https://github.com/wxGlade/wxGlade/files/4945466/test_no_custom_class.wxg.txt) used to generate the correct code. Specifically the line:
`self.test_panel = my_panel.MyPanel(self, wx.ID_ANY)`

With the latest master branch, I get the warning:
`ERROR   : WARNING: Property 'no_custom_class' not supported by this object ('<panel.panel.EditPanel object at 0x7f9a38ca20d0>') `

Then, the generated code contains a custom class `MyPanel` and the line above is replaced with:
`self.test_panel = MyPanel(self, wx.ID_ANY)`

On top of that, when I save the WXG file, the property `no_custom_class` is lost.

**Comment by DietmarSchwertberger** [comment]
OK, if you move `my_panel.MyPanel` from `Class` to `Instance class`, the code gets generated correctly, right?

So the loading needs to be fixed.

**Comment by udifuchs** [comment]
Yes, when using `Instance class` wxglade generates the correct code.

**Comment by DietmarSchwertberger** [comment]
I hope that the separation of `Class` and `Instance class` is clearer than the old approach. Internally it's definitely easier to handle.

Please note that currently you can set `Class` and `Instance Class` at the same time, but this is not supported.
I'm not yet sure whether I will implement this or block one property if the other is set.

**Comment by DietmarSchwertberger** [comment]
This should be fixed now. I hope I did not introduce other bugs...
The header `<!-- generated by wxGlade 0.9.6` in the .wxg files is important now as backward compatibility will be handled accordingly.

**Comment by udifuchs** [comment]
All my files are generated correctly. Thanks.
