### ISSUE TITLE
Segfault when default item of ListBox choices is clicked on and removed

### ISSUE THREAD

**Issue by jackbradach** [wxGlade/wxGlade#421]
1. New project, add window, toss a ListBox into the slot.
2. Go to widget tab of ListBox, click on label showing 'choice 1' 
3. Click remove; oh no segfault!  Like, for real, no stacktrace, core dumped, segfault.  Neat!

It doesn't happen if I don't click on the 'choice 1' widget first.  The default entry will successfully be removed.  Re-adding an item, clicking on it, and clicking remove twice also causes a segfault.

**Comment by DietmarSchwertberger** [comment]
Could you please state version, platform, wxPython version, Pyhon version?
On Windows It just worked for me.

**Comment by jackbradach** [comment]
Oop, yes that would be helpful.

- Python 3.8.2
- wxPython 4.1.0
- wxGlade 0.9.9pre (git HEAD)
- Ubuntu 20.04

Let me know if you still can't reproduce it.  I'll take a look at the core dump when I get a chance.

**Comment by DietmarSchwertberger** [comment]
I have an Ubuntu VM with python 3.7.5 and wxPython 4.0.6. There it seems to work. I need to check my other Ubuntu installation in the next days, but probably only on monday or so.

**Comment by DietmarSchwertberger** [comment]
Btw. the core dumps are usually not helpful for such problems, so don't bother.

**Comment by DietmarSchwertberger** [comment]
Is there a distribution package for wxPython 4.1? I tried ...wxgtk4.1, but that does not seem to exist.

**Comment by jackbradach** [comment]
There's a wheel that can be downloaded and installed manually from a link buried on the wxpython page! :-)

It looks like Python 3.8.2, wxGlade HEAD, and wxPython 4.0.7 *doesn't* exhibit the same problem.  This might be a wxPython bug and not a wxGlade bug.  I'll poke a bit more to try to prove it one way or the other.

**Comment by DietmarSchwertberger** [comment]
Yes, I know these, but I wanted to to avoid it if there's a distribution package.
I'm not a LInux pro. It's much easier for me to handle different version on Windows where I have a bunch of portable installations in parallel.

But anyway, I will look into this, but only middle of next week.

"Bug" is always relative. wxGlade is dynamically changing a lot. There is much more dynamic than with a normal program.
Could you switch to 0.9.6 whether it show the same issue? I would expect it, but am not sure.

You don't have the accessibility options in wxGlade's preferences enabled, right?

**Comment by jackbradach** [comment]
I don't see accessibility options in the preferences.  I didn't explicitly turn them on.

Interesting... 0.9.6 + Python 3.8.2 + wxPython 4.1.0 does not crash.  I waved gdb at it to see where it was bombing out.  The python side of the traceback reads like it's the grid object from the widget editing UI and not the listbox that has the problem.  No worries about having to wait for you to look at it; I have plenty of work-arounds!

> Thread 1 "python" received signal SIGSEGV, Segmentation fault.
> 0x00007ffff5a7dc0d in wxClientDCImpl::wxClientDCImpl(wxClientDC*, wxWindow*) ()
>    from /home/jbradach/.cache/pypoetry/virtualenvs/wxtest-LyV7PhQG-py3.8/lib/python3.8/site-packages/wx/libwx_gtk3u_core-3.1.so.4

> (gdb) py-bt
> Traceback (most recent call first):
>   <built-in method GoToCell of Grid object at remote 0x7fffe871bb80>
>   File "/usr/local/src/wxGlade/new_properties.py", line 2711, in _set_index
>     self.grid.GoToCell( self.cur_row, self.cur_col )
>   File "/usr/local/src/wxGlade/new_properties.py", line 3115, in remove_row
>     self._set_index()
>   File "/usr/local/src/wxGlade/new_properties.py", line 3083, in on_button_remove
>     self.remove_row(set_focus=True, highlight=False)
>   <built-in function MainLoop>
>   File "/home/jbradach/.cache/pypoetry/virtualenvs/wxtest-LyV7PhQG-py3.8/lib/python3.8/site-packages/wx/core.py", line 2224, in MainLoop
>     rv = wx.PyApp.MainLoop(self)
>   File "/usr/local/src/wxGlade/main.py", line 1522, in main
>     app.MainLoop()
>   File "/usr/local/src/wxGlade/wxglade.py", line 384, in run_main
>     main.main(options.filename)
>   File "/usr/local/src/wxGlade/wxglade.py", line 389, in <module>
>     run_main()

**Comment by DietmarSchwertberger** [comment]
Thanks a lot. The backtrace has helped to solve it. Not sure why I missed this. Usually wx should have given an assertion also on Windows.
Please test.

**Comment by jackbradach** [comment]
Confirmed, head of tree no longer bombs out on this.  Thanks!
