### ISSUE TITLE
No module named '_dialogs'

### ISSUE THREAD

**Issue by udifuchs** [wxGlade/wxGlade#423]
There seem to be a missing file in the latest commit. Anything I try to do, I get:

ERROR   : None
An unexpected error occurred!

Exception type:      <class 'ModuleNotFoundError'>
Exception details:   No module named '_dialogs'

Application stack traceback:
  File ".../git/wxGlade/tree.py", line 519, in on_left_click
    editor.on_drop_widget(event)
  File ".../git/wxGlade/edit_base.py", line 779, in on_drop_widget
    new_widget = common.widgets[common.widget_to_add](self.parent, self.index)
  File ".../git/wxGlade/widgets/static_text/static_text.py", line 70, in builder
    import dialogs, misc
  File ".../wxGlade/dialogs.py", line 14, in <module>
    from _dialogs import *

Date and time:       2020-08-06T14:38:29.142721
Python version:      3.8.2
wxPython version:    4.0.7
wxWidgets platform:  __WXGTK__
wxGlade version:     0.9.9pre

**Comment by DietmarSchwertberger** [comment]
Yes, sorry, forgot to add it when re-organizing. It's online now.

I'm currently updating the codumentation, so there are many modified and renamed files and I did not see this.
