### ISSUE TITLE
wxALIGN_CENTER not available

### ISSUE THREAD

**Issue by t-morales** [wxGlade/wxGlade#425]
It seems that the option ALIGN_CENTER is not available any more. This option now appears in red and I cannot select it.

I am currently using the branch REV_0.9 in order to avoid a <class 'AttributeError'> similar to issue #407 when I select Preview Dialog.

![Screenshot_20200808_133037](https://user-images.githubusercontent.com/39190016/89708959-bfc84780-d97b-11ea-9758-9793663113d2.png)

**Comment by DietmarSchwertberger** [comment]
You probably have this item inside a horizontal sizer, right?
wxALIGN_CENTER contains wxALIGN_CENTER_HORIZONTAL and would trigger an assertion with wxPython 4.1 and recent wx versions if assertions are enabled.
Same for wxALIGN_RIGHT.

Could you please post the backtrace with the Attribute error?

**Comment by t-morales** [comment]
Thank you. It is indeed inside a horizontal sizer. I did not know that.
Concerning the Attribute error, do you want me to post it here or as a new issue?

**Comment by DietmarSchwertberger** [comment]
Just post it here. I will try to fix it ASAP.

**Comment by t-morales** [comment]
OK, this is what happens when I select "Preview Dialog" with master branch:
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'AttributeError'>
Exception details:   <class 'frame.frame.EditFrame'> object has no attribute 'toplevel_parent_window'

Application stack traceback:
  File "/home/user/wxGlade/misc.py", line 339, in handler
    func( *args, **kwargs )
  File "/home/user/wxGlade/edit_windows.py", line 224, in preview_parent
    widget = self.toplevel_parent_window # misc.get_toplevel_widget(self)
  File "/home/user/wxGlade/new_properties.py", line 3345, in __getattr__
    raise AttributeError("%r object has no attribute %r" %(self.__class__, attr))

Date and time:       2020-08-08T14:40:16.218421
Python version:      3.7.5
wxPython version:    4.0.6
wxWidgets platform:  __WXGTK__
wxGlade version:     0.9.9pre

**Comment by DietmarSchwertberger** [comment]
Thanks. The preview is fixed now.
I did not notice this as I always press F5 for preview and ESC to close...

If you have a small .wxg sample to reproduce the Alignment screenshot from above, please post it here.
Actually, the blocked flags should be deactivated on loading.
(Blocked grey should mean that e.g. horizontal alignment can't be selected in a horizontal sizer. Blocked red means that selecting such a flag will deactivate another, e.g. when you select ALIGN_RIGHT, then CENTER_HORIZONTAL will be unchecked.)

**Comment by t-morales** [comment]
OK, the AttributeError is now solved.

Here is a screenshot of a simple example. The left one corresponds to version 0.9.3, which corresponds to the one I originally created the wxg. The right one corresponds to 0.9.9 after loading the wxg.

Thank you for your help! 
![Screenshot_20200808_190350](https://user-images.githubusercontent.com/39190016/89716076-5f9cca00-d9aa-11ea-895f-1f82045f51d7.png)

**Comment by DietmarSchwertberger** [comment]
I have checked with the current master branch and there it looks correct:
![grafik](https://user-images.githubusercontent.com/5512021/89730769-30399c00-da42-11ea-9a6f-ac4478a0a8b0.png)

Unfortunately, deactivated checkboxes can't have tooltip help, so at first it's not obvious why items are not checkable.
