### ISSUE TITLE
In version 1.0.0.a2 statusbar is given the name "frame_menubar"

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#431]
Testing Version 1.0.0a1 on Python 3.6.9 and wxPython 4.0.1 

I added a Frame, then ticked 'Has MenuBar' & 'Has StatusBar'.

Both the menubar and the statusbar were given the name "frame_menubar". 

In previous versions the statusbar was given the name "frame_statusbar"

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. I have just implemented the fix. I will look into #432 right now.

**Comment by DietmarSchwertberger** [comment]
fixed in a3
