### ISSUE TITLE
Request that ID TextCtrls in Toolbar & Editor Menus are made wider

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#432]
The ID TextCtrls in the Toolbar Editor and Menu Editor can only show 9 characters without scrolling. 

Please can you make them wider, say 20 characters?

**Comment by DietmarSchwertberger** [comment]
I have changed the fields to grow to half the width of the columns above.
Why are you using IDs? In most cases they should not be required at all, at least for Python.

**Comment by reticulatus** [comment]
My preferred way of working is to use wxGlade to generate base classes for frames, dialogs and panels. The base classes just handle widget creation and layout. I then create derived classes which bind event handlers and implement functionality. For menus and toolbars I use IDs when creating the bindings.
