### ISSUE TITLE
[Feature] Add wx.Button support for image states (normal, disabled, pressed, focus, current) [sf#44]

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxGlade/wxGlade#44]
**Reported by brendansimon on 2017-10-08 11:24 UTC**
Add wx.Button support for image states (normal, disabled, pressed, focus, current).

Note: Since v2.9.1 `wx.Button()` and `wx.BitmapButton()` are the same, except for the convenience of being able to specify the normal image in the constrcutor of the latter class.

It's a pity there are no default constructors for the other image states, so the widget methods need to be called to set them.

> A button may have either a single image for all states or different images for the following states (different images are not currently supported under OS X where the normal image is used for all states):
> 
> * normal: the default state
> * disabled: bitmap shown when the button is disabled.
> * pressed: bitmap shown when the button is pushed (e.g. while the user keeps the mouse button pressed on it)
> * focus: bitmap shown when the button has keyboard focus (but is not pressed as in this case the button is in the pressed state)
> * current: bitmap shown when the mouse is over the button (but it is not pressed although it may have focus). Notice that if current bitmap is not specified but the current platform UI uses hover images for the buttons (such as Windows XP or GTK+), then the focus bitmap is used for hover state as well. This makes it possible to set focus bitmap only to get reasonably good behaviour on all platforms.

https://wxpython.org/Phoenix/docs/html/wx.Button.html

https://wxpython.org/Phoenix/docs/html/wx.BitmapButton.html

**Comment by DietmarSchwertberger** [comment]
**Commented by dschwertberger on 2017-10-08 11:54 UTC**
Ticket moved from /p/wxglade/bugs/219/

Can't be converted:

- **_version**:

**Comment by DietmarSchwertberger** [comment]
**Updated by dschwertberger on 2017-10-08 11:55 UTC**
- **status**: open --> accepted
- **assigned_to**: Dietmar Schwertberger
- **Group**:  --> Next Release

**Comment by DietmarSchwertberger** [comment]
**Commented by dschwertberger on 2017-10-08 11:55 UTC**
I think that from a usability point of view it makes sense to keep BitmapButton separate. That's easier for the user than having to choose afterwards.

So these need to be called: SetBitmapDisabled, SetBitmapPressed , SetBitmapFocus, SetBitmapCurrent

Regards,
Dietmar

**Comment by DietmarSchwertberger** [comment]
**Updated by dschwertberger on 2017-11-02 18:34 UTC**
- **Group**: Next Release --> 0.9.0

**Comment by DietmarSchwertberger** [comment]
**Commented by dschwertberger on 2017-12-28 08:31 UTC**
For now, you may define *Properties -> Code -> Extra Properties*:
~~~
Bitmap          wx.Bitmap("icons\\normal1.xpm", wx.BITMAP_TYPE_ANY)
BitmapDisabled  wx.Bitmap("icons\\off1.xpm", wx.BITMAP_TYPE_ANY)
BitmapPressed   wx.Bitmap("icons\\pressed1.xpm", wx.BITMAP_TYPE_ANY)
BitmapCurrent   wx.Bitmap("icons\\current1.xpm", wx.BITMAP_TYPE_ANY)
BitmapFocus	    wx.Bitmap("icons\\focus1.xpm", wx.BITMAP_TYPE_ANY)
~~~

Actually, Button and BitmapButton are not 100% identical: a BitmapButton has a SetLabel method, but this does not add a label while a normal Button can have a Label and a bitmap.

**Comment by BrendanSimon** [comment]
> It's a pity there are no default constructors for the other image states, so the widget methods need to be called to set them.

Agreed.  Should we put in a feature request for wxPython and/or wxWidgets ?

**Comment by DietmarSchwertberger** [comment]
I don't think so. Calling methods is OK. The difficult part is not the code generation, but the editor. E.g. the order in which images are added, what happens if the size is different and so on.
I made good progress on this beginning of January, but was distracted by work on and with Matplotlib, as I found it important that a Matplotlib canvas can easily be integrated into a wxGlade design. This is now the case with Matplotlib 2.2.

**Comment by DietmarSchwertberger** [comment]
A first version is in the repository. Please have a look. I did not yet really use it myself, so expect bugs...

**Comment by BrendanSimon** [comment]
Hi Dietmar,

The button images seem to work ok -- I'm using latest from master
[b1a59076].

I am having trouble placing the image in the centre of button.

If I have wxExpand unchecked, and wxCenter checked, the image seems to
be left or close to left justified.

If I have wxExpand unchecked, and wxRight checked, the image seems to be
closer to the center, but not at the right.

I'm using Mac, which may or may not make a difference.

Brendan.

------------------------------------------------------------------------

**Comment by BrendanSimon** [comment]
It seems the button is left, centre or right justified ok.

It's the image within the button area that seems to be left justified. 
In another app I've been using wx.BitmapButton (not wx.Button).  I'm not
sure if that makes any difference or not.  I tried changing the class
from "wxButton" to "wx.BitmapButton" and it didn't seem to make much
difference.

Actually, checking wxBU_EXACT_FIT seems to help, but I'm not convinced
it's necessarily doing the right thing or not ???

On another note, I had two buttons in a flex grid sizer.  I decided to
add extra characters to one button (normal button) and it expanded in
the design and preview windows (as I expected), however when I removed
the extra characters only the preview window reduced the button/sizer
size -- the design window updated the text but the button/sizer width
remained at the expanded width.  The deisgn window doesn't seem to
resize the sizers.

Brendan.

------------------------------------------------------------------------

**Comment by DietmarSchwertberger** [comment]
Hi Brendan,

I'm not sure whether buttons are well prepared to have a size that is different from the bitmap.
The alignment styles seem to apply only to the label, e.g. "wx.BU_RIGHT: Right-justifies the bitmap label. Windows and GTK+ only."
If you need more control, you probably need to create a bitmap yourself or render it during runtime (e.g. there are examples for rendering a mathematical formula to a bitmap button using matplotlib).
Please tell me if you find a case where the generated code is correct and behaves correct but the Design window does not.

I will look into the resizing issue. Recently I changed the behaviour of TextCtrl to change size to "-1, -1" before calculating the best size again. Maybe the same should be done for Buttons. Maybe it would be the best to do this for all widgets, but I'm a bit afraid whether this would introduce other problems.

**Comment by DietmarSchwertberger** [comment]
I have just added a workaround for the resizing issues. Please test.

**Comment by DietmarSchwertberger** [comment]
I did just modify the resizing code a bit to handle things in a more generic way. I hope it did not break anything.
About the buttons: I don't have  the impression that Buttom plus images really behaves the same as a BitmapButton.

**Comment by BrendanSimon** [comment]
According to this url, there isn't any difference in functionality 
between `wxButton` and `wxBitmapButton` these days.

    http://docs.wxwidgets.org/3.1/classwx_bitmap_button.html

    /"""
    Notice that since wxWidgets 2.9.1 bitmap display is supported by the
    base //wxButton
    <http://docs.wxwidgets.org/3.1/classwx_button.html>//class itself
    and the only tiny advantage of using this class is that it allows to
    specify the bitmap in its constructor, unlike //wxButton
    <http://docs.wxwidgets.org/3.1/classwx_button.html>//. Please see
    the base class documentation for more information about images
    support in //wxButton
    <http://docs.wxwidgets.org/3.1/classwx_button.html>//.
    """
    /


Brendan

------------------------------------------------------------------------

**Comment by DietmarSchwertberger** [comment]
I know the docs, but the actual behaviour is different. It might be that for wxBitmapButton wxBU_EXACTFIT is on by default. The wxGlade design window does not correctly reflect wxBU_EXACTFIT for a wxButton. I will check this.

**Comment by DietmarSchwertberger** [comment]
The different default styles of Button and BitmapButton are now handled by wxGlade.

**Comment by ardovm** [comment]
I am afraid there is a problem with the `disabled` attribute. I don't know if it is related to this particular issue, though.

The problem consists of the fact, that the `disabled` attribute is interpreted by `wxrc` as the **image** for disabled buttons. Whereas `wxGlade` seems to treat it as a negated equivalent of the `enabled` property.

The outcome is that a disabled `wxBitmapButton`, when exported into XRC code, has **two** attributes:
1. `enabled` set to `0`,
1. `disabled` set to `1`.

`wxrc` treats the latter as an image file name and prints an error message. Reference: http://www.github.com/wxWidgets/wxWidgets/blob/master/utils/wxrc/wxrc.cpp#L483

Please note I am encountering this problem on wxg files made with previous versions of wxGlade.

**Comment by DietmarSchwertberger** [comment]
@ardovm : so this is only with old files or also with new ones? Could you please attach a sample and tell which wxGlade version you are using? These changes are only in the master branch of the repository yet, but e.g. not in 0.8.3.

**Comment by DietmarSchwertberger** [comment]
Just create a small sample and state which combination of version fails. I will have a look then.
E.g. created wxg created with 0.7.2, XRC created with 0.8.0.

**Comment by ardovm** [comment]
I had to rename into ".txt" the WXG files, otherwise GitHub would refuse to attach them.

- [wxbitmap_problematico.wxg](https://github.com/wxGlade/wxGlade/files/2387702/wxbitmap_problematico.wxg.txt) made with wxGlade 0.7.2.
- [wxbitmap_problematico_wxGlade0.8.wxg](https://github.com/wxGlade/wxGlade/files/2387709/wxbitmap_problematico_wxGlade0.8.wxg.txt) made with wxGlade 0.8.0

Both are compiled well by wxGlade 0.7.2 and wrong by wxGlade 0.8.0.
The problem is that wxGlade 0.8.0 adds the "disabled" attribute to the wxBitmapButton.

I hope this helps.

**Comment by DietmarSchwertberger** [comment]
Please modify `codegen\xrc_codegen.py`, `DefaultXrcObject.write` to see whether this fixes the problem:
From:
```
            elif name=='disabled':
                # 'disabled' property is actually 'enabled' for XRC
                if prop.get():
                    properties['enabled'] = '0'
                else:
                    continue
```
To:
```
            elif name=='disabled':
                # 'disabled' property is actually 'enabled' for XRC
                if prop.get():
                    properties['enabled'] = '0'
                continue
```

**Comment by ardovm** [comment]
Yes! This fixes the problem!

**Comment by DietmarSchwertberger** [comment]
0.9.0a1 is available
