### ISSUE TITLE
No line break between extra-code segments for C++ project

### ISSUE THREAD

**Issue by foolo** [wxGlade/wxGlade#440]
Steps to reproduce:
1. Create a new C++ project and add a wxFrame
2. Select the frame in the navigation tree and add some extra code (for example `#include <foo>`) under  **Properties > Code > Extra (import) code for this widget**
3. Select some other component (for example the panel that was automaticall created on the frame), and add some extra code (for example `#include <bar>`) for that as well
4. Generate code and open the output file `wxglade_out.h`, and find  `// begin wxGlade: ::extracode`

Expected output:
```
// begin wxGlade: ::extracode
#import <foo>
#import <bar>
// end wxGlade
```

Actual output:
```
// begin wxGlade: ::extracode
#import <foo>#import <bar>
// end wxGlade
```

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. Which version is this? 0.9, 1.0 or from the repository?

**Comment by foolo** [comment]
Ah, sorry, forgot to add which version. It was wxGlade-1.0.0a6 downloaded from SourceForge.

**Comment by DietmarSchwertberger** [comment]
Thanks. I recently changed something because import segments with and without a trailing line break were not being identified as identical. Maybe this introduced the bug. I will have a look.

**Comment by DietmarSchwertberger** [comment]
It turns out that this problem has persisted for many years already.
Please try 1.0.0a7 from https://github.com/wxGlade/wxGlade/releases/tag/v1.0.0a7
If you confirm and after some more testing, I will also update the Sourceforge download page.

**Comment by foolo** [comment]
Nice! It seems to work fine in 1.0.0a7.
