### ISSUE TITLE
Minor C++ feature suggestion: Option to disable generating main.cpp

### ISSUE THREAD

**Issue by foolo** [wxGlade/wxGlade#441]
In some of my applications, I have special functionality in the startup code, which means I don't use the main.cpp that is generated by wxGlade (I use all the other generated files, only not main.cpp), which means that I either remove it manually, or put it in .gitignore (in which case it will obviously still be seen in the IDE and in the folder).
My suggestion is an option "Don't generate main.cpp". If not, I would also be happy with just patching it away in my local wxGlade source code if that's reasonably simple.

**Comment by DietmarSchwertberger** [comment]
I think it should be sufficient to deactivate Application -> Name and Class:
![grafik](https://user-images.githubusercontent.com/5512021/93015686-878bd880-f5bb-11ea-9c7d-38f96e74cb1b.png)

**Comment by foolo** [comment]
Ahh, that seems to work. Thanks!
