### ISSUE TITLE
Dragging widgets in gridsizer does not work when using Python 2.7

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#442]
When I use wxGlade 1.0.0a8 in Python 3.7 and wxPython 4.0.3, I am able to drag widgets around.
When I switch to Python 2.7 and wxPython 2.9, widgets cannot be dragged.

**Comment by programmingkidx** [comment]
To reproduce this issue:

Launch wxGlade using Python 2.7
Create a new frame
Unselect "Add Panel and Sizer".
Add a GridSizer.
Add a button.
Try to drag the button to a different square.

**Comment by DietmarSchwertberger** [comment]
Please note that wxPython 2.9 is not supported. Odd minor versions indicate unstable releases.
The 2.9 series is far away from mainstream. You can see this from the download numbers at https://sourceforge.net/projects/wxpython/files/wxPython/

I wanted to try 2.8.12 and 3.0.2 with my system Python 2.7, but the .dmg packages are reported to be corrupted. Do you know a way to install? I know that some years ago I had success...

**Comment by DietmarSchwertberger** [comment]
OK, I can install this one, built with a newer installer:
https://wxpython.org/Phoenix/other/wxPython3.0-osx-3.0.3.0.b20160914-cocoa-py2.7.dmg

https://discuss.wxpython.org/t/unable-to-install-wxpython-2-8-12-1/32949/2

**Comment by DietmarSchwertberger** [comment]
3.0 is working, as is 2.8 on Windows. There's nothing else I can do on this unless you find a way for me to install 2.8, if this has the same problem.

You may debug this yourself.
The entry point is edit_windows.ManagedBase.on_mouse_events.

**Comment by iMacker2020** [comment]
I wasn't aware that odd minor versions meant it was unstable. What is your source for this information?

**Comment by iMacker2020** [comment]
When I switched to wxPython 3.0.2.0 the issue disappeared.

**Comment by DietmarSchwertberger** [comment]
Fine.

The version numbering is documented here:  https://docs.wxwidgets.org/3.0/overview_backwardcompat.html

"A stable release of wxWidgets will have an even number for minor, e.g. 2.6.0."

Unfortunately, this is not widely known for wxPython and also e.g. PIP does not indicate that 4.1 is unstable, so people use it for production.
