### ISSUE TITLE
Main window is too high up

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#443]
![window location](https://user-images.githubusercontent.com/19289541/95223603-ca5e5c00-07c7-11eb-8f58-1c235574d395.png)

When starting wxGlade, the main window appears to be located too high up. It is so high up that some of the buttons on the window are not accessible. 

My info:
Machine: MacBook Pro 15" (1440x900 resolution)
OS: Mac OS 10.8.5
Python: 2.7
wxPython: 3.0.2.0
wxGlade: 1.0.0a9

**Comment by DietmarSchwertberger** [comment]
Ah, yes, I remember this being reported, but did not yet look into it.
I will do so asap now as I don't add features to 1.0.0 any more.

**Comment by DietmarSchwertberger** [comment]
Please try the master branch. I have just added code to check whether the top edge of the window is visible.

**Comment by iMacker2020** [comment]
When I first tried the master branch the problem was still present. But when I tried it again the window was perfectly aligned. I opening wxGlade several times and everytime the window was positioned perfectly. So I think this issue is resolved.

**Comment by programmingkidx** [comment]
When I first tried the master branch the problem was still present. But when I tried it again the window was perfectly aligned. So I tried opening wxGlade several times and every time the window was positioned perfectly. So I think this issue is resolved.

**Comment by DietmarSchwertberger** [comment]
Could you please check your preference setting?
I would think that you have "Remember position and size of wxGlade windows" active.
Please deactivate and re-start and report whether the window is positioned correctly.
I'm still wondering what was the root cause for the wrong position.

Thanks,
Dietmar

**Comment by programmingkidx** [comment]
I did have it checked. I did as you asked and the window positioned itself correctly.

**Comment by DietmarSchwertberger** [comment]
Thanks a lot.
