### ISSUE TITLE
Controls appear cropped in design window on Windows

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#444]
When adding a control to a gridsizer, the control will appear cropped by the grid. This happens in the design window on Windows. 
![Windows xp](https://user-images.githubusercontent.com/19289541/95900846-7a9c0980-0d60-11eb-85f3-3dfb30a23275.png)

On Mac OS X the buttons appears fully on the gridsizer. 
![Mac OS 10 8](https://user-images.githubusercontent.com/19289541/95900819-7112a180-0d60-11eb-8047-e3d780fbc958.png)

To reproduce this issue simply create a new frame. Then delete the boxsizer in the slot and replace it with a 10x10 gridsizer. Then add a button to the gridsizer.

My guess is the control is being drawn first, then the grid is being drawn over it on Windows.

**Comment by DietmarSchwertberger** [comment]
I think that's correct. One platform is clipping if there is not enough space, the other does not. Either way it's not useful to place a large widget inside smaller grid sizer cells.

Are you trying to use a grid sizer as base for your GUI? Thats not a good idea. Always use the simplest sizers.

**Comment by programmingkidx** [comment]
Being able to put a large widget inside a small grid sizer does enable the user to layout a GUI easily.

**Comment by programmingkidx** [comment]
The Gridsizer is a very familiar concept. It is just like graphing everyone did in algebra class in school. Boxsizers are not as familiar.

**Comment by DietmarSchwertberger** [comment]
Forget about this. This will not result in nice or good GUIs.

**Comment by DietmarSchwertberger** [comment]
See here for how to create a big mess: https://www.youtube.com/watch?v=fiiKtu9knpA
