### ISSUE TITLE
Error occurs when adding Boxsizer

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#445]
ERROR   : None
An unexpected error occurred!

Exception type:      <type 'exceptions.TypeError'>
Exception details:   new_StaticBoxSizer() takes at most 2 arguments (3 given)

Application stack traceback:
  File "/Users/misbah/Desktop/untitled folder/wxGlade-master/tree.py", line 549, in on_left_click
    editor.on_drop_widget(event)
  File "/Users/misbah/Desktop/untitled folder/wxGlade-master/edit_base.py", line 798, in on_drop_widget
    new_widget = common.widgets[common.widget_to_add](self.parent, self.index)
  File "/Users/misbah/Desktop/untitled folder/wxGlade-master/edit_sizers/edit_sizers.py", line 2136, in builder
    dialog = _SizerDialog(common.adding_window or parent, parent.toplevel_parent.WX_CLASS=="wxDialog")
  File "/Users/misbah/Desktop/untitled folder/wxGlade-master/edit_sizers/edit_sizers.py", line 2047, in __init__
    vsizer = wx.StaticBoxSizer(wx.VERTICAL, self, _('Orientation'))
  File "/usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 15151, in __init__
    _core_.StaticBoxSizer_swiginit(self,_core_.new_StaticBoxSizer(*args, **kwargs))

Date and time:       2020-10-13T16:09:20.096411
Python version:      2.7.2
wxPython version:    3.0.2.0
wxWidgets platform:  __WXMAC__
wxGlade version:     1.0.0a9

Steps to reproduce:
Start wxGlade.
Push the "Add a Frame" button.
Push the "Add a BoxSizer" button.
Click on "SLOT 0".

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. It should be fixe d now in the master branch.

**Comment by programmingkidx** [comment]
It does appear to be fixed. There is another problem I noticed. In the "Select size type" window that appears, there are two radio buttons. One is for vertical and the other is for horizontal. Neither one of them is selected. I suggest the top radio button be initially selected.

**Comment by DietmarSchwertberger** [comment]
Thanks. I did not see this on Windows.
I have changed it such that the defaulf is perpendicular to the parent sizer if that one is a box sizer as well.
A minor issue with StdDialogButton sizers remains to be fixed.

**Comment by iMacker2020** [comment]
The issue is resolved now. Thank you :)

**Comment by DietmarSchwertberger** [comment]
1.0.0b1 is online.
