### ISSUE TITLE
Feature request: Add additional ways to delete a widget

### ISSUE THREAD

**Issue by iMacker2020** [wxGlade/wxGlade#446]
To delete a widget from the tree window, the user on a full sized keyboard can push the forward delete key. This key isn't available on some laptops, so the convenience of deleting a widget with a single key stroke isn't there. I suggest that the delete key (on a Macintosh) or the backspace key (on a PC) be given the power to delete a widget.

I also request that a menu item be added to the Edit menu called "Delete" what would allow the user to delete a widget as well.

Thank you.

**Comment by DietmarSchwertberger** [comment]
You can always use Ctrl-X. It might be Command-X on the Mac.

The backspace key, at least on Windows, will go up by one in the hierarchy.
I would not want to mask that feature as there are also blind people who are only using the tree for navigation.

Most Windows notebooks seem to have the Delete key anyway, usually at the top right.

What is the situation on Mac Os? Unfortunately I don't have Apple hardware for testing. When looking at a keyboard in the store, there is one "Delete" where a PC has Backspace and one "Delete |x>" where a PC has the Del/Delete key.
The latter seems to be missing from the MacBooks.
What are those keys doing now in the Tree control? In my Mac VM the "Delete"/Backspace does nothing, so on Mac Os it could be assigned for deleting.


I will look into menu and toolbar support for deleting.

**Comment by iMacker2020** [comment]
All MacBooks lack a 'Forward Delete' key. Pushing the 'Delete' key does nothing in the Tree control or on the Design Window when a widget is selected.

**Comment by DietmarSchwertberger** [comment]
OK, I will look to assign the Delete key on Mac Os.

**Comment by DietmarSchwertberger** [comment]
Could you please try this?

In `main.py`, around line 513, replace:
`    ("",  wx.WXK_DELETE):(_remove, ()),`
with
`    ("",  wx.WXK_BACK):(_remove, ()),`

Does this work for you?

**Comment by iMacker2020** [comment]
I was not able to find the code. I looked in both the 1.0.0a9 and master repos.

**Comment by DietmarSchwertberger** [comment]
Sorry, it's misc.py, not main.py.

**Comment by iMacker2020** [comment]
It worked great.

**Comment by DietmarSchwertberger** [comment]
Cool. It's in the repository now.

**Comment by DietmarSchwertberger** [comment]
1.0.0b1 is online.
