### ISSUE TITLE
Error while adding choices to RadioBox widget

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#447]
While adding choices to a RadioBox widget I saw this error:

ERROR   : None
An unexpected error occurred!

Exception type:      <type 'exceptions.IndexError'>
Exception details:   list index out of range

Application stack traceback:
  File "/Users/user/Desktop/wxGlade-master/new_properties.py", line 2938, in on_cell_changed
    self._on_value_edited(row, col, value)      # this can add a row
  File "/Users/user/Desktop/wxGlade-master/new_properties.py", line 2972, in _on_value_edited
    if data[row] is None:

Date and time:       2020-10-15T14:04:53.786565
Python version:      2.7.2
wxPython version:    3.0.2.0
wxWidgets platform:  __WXMAC__
wxGlade version:     1.0.0a9

Steps to reproduce:
Add a window.
Add a RadioBox widget.
Navigate to the Widget tab.
Add a few choices.
Push the Apply button.

I think I had one or two rows that were blank when the error occurred.

**Comment by DietmarSchwertberger** [comment]
Thanks. I know that there's at least one bug in the grid based properties (e.g. part of issue #439).
Unfortunately, I could never reproduce it and also can't reproduce it from your description.

**Comment by DietmarSchwertberger** [comment]
Could not be reproduced.
