### ISSUE TITLE
Crash when adding menubar

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#449]
When adding a menubar to my application, wxGlade crashed. Here is some info about the crash:

Process:         Python [518]
Path:            /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:      org.python.python
Version:         2.7.2 (2.7.2)
Build Info:      python-60004000000000~1
Code Type:       X86-64 (Native)
Parent Process:  bash [220]
User ID:         501

PlugIn Path:       /usr/local/lib/wxPython-3.0.2.0/lib/libwx_osx_cocoau-3.0.0.2.0.dylib
PlugIn Identifier: libwx_osx_cocoau-3.0.0.2.0.dylib
PlugIn Version:    ??? (3)

Date/Time:       2020-10-18 20:38:20.491 -0400
OS Version:      Mac OS X 10.8.5 (12F45)
Report Version:  10

Interval Since Last Report:          2977055 sec
Crashes Since Last Report:           825
Per-App Interval Since Last Report:  48455 sec
Per-App Crashes Since Last Report:   3
Anonymous UUID:                      226CCC9B-23B0-5C52-8360-6A35C6714BF6

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 000000010740a000-000000010740b000 [    4K] r-x/rwx SM=COW  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libwx_osx_cocoau-3.0.0.2.0.dylib	0x00000001080468bd wxWindow::DoGetSize(int*, int*) const + 45
1   libwx_osx_cocoau-3.0.0.2.0.dylib	0x000000010824b3fa wxWindowBase::SendSizeEvent(int) + 58
2   _core_.so                     	0x0000000107c84b14 _wrap_Window_SendSizeEvent + 244
3   org.python.python             	0x0000000107429f72 PyEval_EvalFrameEx + 3557
4   org.python.python             	0x0000000107429147 PyEval_EvalCodeEx + 1934
5   org.python.python             	0x000000010742f8df 0x107412000 + 121055
6   org.python.python             	0x000000010742b63a PyEval_EvalFrameEx + 9389
7   org.python.python             	0x000000010742f869 0x107412000 + 120937
8   org.python.python             	0x000000010742b63a PyEval_EvalFrameEx + 9389
9   org.python.python             	0x0000000107429147 PyEval_EvalCodeEx + 1934
10  org.python.python             	0x0000000107462d7a 0x107412000 + 331130
11  org.python.python             	0x00000001074216c6 PyObject_Call + 97
12  org.python.python             	0x000000010743e9bf 0x107412000 + 182719
13  org.python.python             	0x00000001074216c6 PyObject_Call + 97
14  org.python.python             	0x000000010742b78d PyEval_EvalFrameEx + 9728
15  org.python.python             	0x000000010742f869 0x107412000 + 120937
16  org.python.python             	0x000000010742b63a PyEval_EvalFrameEx + 9389
17  org.python.python             	0x0000000107429147 PyEval_EvalCodeEx + 1934
18  org.python.python             	0x000000010742f8df 0x107412000 + 121055
19  org.python.python             	0x000000010742b63a PyEval_EvalFrameEx + 9389
20  org.python.python             	0x0000000107429147 PyEval_EvalCodeEx + 1934
21  org.python.python             	0x0000000107462d7a 0x107412000 + 331130
22  org.python.python             	0x00000001074216c6 PyObject_Call + 97
23  org.python.python             	0x000000010742f018 PyEval_CallObjectWithKeywords + 177
24  _core_.so                     	0x0000000107be9478 wxPyCallback::EventThunker(wxEvent&) + 312
25  libwx_osx_cocoau-3.0.0.2.0.dylib	0x0000000108004094 wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) + 84
26  libwx_osx_cocoau-3.0.0.2.0.dylib	0x000000010800518f wxEvtHandler::SearchDynamicEventTable(wxEvent&) + 111
27  libwx_osx_cocoau-3.0.0.2.0.dylib	0x00000001080062f8 wxEvtHandler::TryHereOnly(wxEvent&) + 40
28  libwx_osx_cocoau-3.0.0.2.0.dylib	0x00000001080063ab wxEvtHandler::ProcessEventLocally(wxEvent&) + 59
29  libwx_osx_cocoau-3.0.0.2.0.dylib	0x0000000108006415 wxEvtHandler::ProcessEvent(wxEvent&) + 69
30  libwx_osx_cocoau-3.0.0.2.0.dylib	0x0000000108005f86 wxEvtHandler::SafelyProcessEvent(wxEvent&) + 22
31  libwx_osx_cocoau-3.0.0.2.0.dylib	0x0000000108247960 wxWindowBase::HandleWindowEvent(wxEvent&) const + 16
32  libwx_osx_cocoau-3.0.0.2.0.dylib	0x00000001080967d9 wxControl::ProcessCommand(wxCommandEvent&) + 9
33  libwx_osx_cocoau-3.0.0.2.0.dylib	0x0000000108064247 wxButton::OSXHandleClicked(double) + 71
34  com.apple.AppKit              	0x00007fff8bc57959 -[NSApplication sendAction:to:from:] + 342
35  com.apple.AppKit              	0x00007fff8bc577b7 -[NSControl sendAction:to:] + 85
36  com.apple.AppKit              	0x00007fff8bc576eb -[NSCell _sendActionFrom:] + 138
37  com.apple.AppKit              	0x00007fff8bc55bd3 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 1855
38  com.apple.AppKit              	0x00007fff8bc55421 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 504
39  com.apple.AppKit              	0x00007fff8bc54b9c -[NSControl mouseDown:] + 820
40  libwx_osx_cocoau-3.0.0.2.0.dylib	0x0000000108129d4d wxWidgetCocoaImpl::mouseEvent(NSEvent*, NSView*, void*) + 157
41  com.apple.AppKit              	0x00007fff8bc4c50e -[NSWindow sendEvent:] + 6853
42  libwx_osx_cocoau-3.0.0.2.0.dylib	0x0000000108111cfc -[wxNSWindow sendEvent:] + 140
43  com.apple.AppKit              	0x00007fff8bc48644 -[NSApplication sendEvent:] + 5761
44  libwx_osx_cocoau-3.0.0.2.0.dylib	0x00000001080186ea -[wxNSApplication sendEvent:] + 74
45  com.apple.AppKit              	0x00007fff8bb5e21a -[NSApplication run] + 636
46  libwx_osx_cocoau-3.0.0.2.0.dylib	0x0000000108102418 wxGUIEventLoop::OSXDoRun() + 248
47  libwx_osx_cocoau-3.0.0.2.0.dylib	0x0000000107fcf60f wxCFEventLoop::DoRun() + 31
48  libwx_osx_cocoau-3.0.0.2.0.dylib	0x0000000107f080e1 wxEventLoopBase::Run() + 65
49  libwx_osx_cocoau-3.0.0.2.0.dylib	0x0000000107ecd787 wxAppConsoleBase::MainLoop() + 103
50  _core_.so                     	0x0000000107be03dc wxPyApp::MainLoop() + 76
51  _core_.so                     	0x0000000107c2ad8f _wrap_PyApp_MainLoop + 79
52  org.python.python             	0x0000000107429f72 PyEval_EvalFrameEx + 3557
53  org.python.python             	0x0000000107429147 PyEval_EvalCodeEx + 1934
54  org.python.python             	0x0000000107462d7a 0x107412000 + 331130
55  org.python.python             	0x00000001074216c6 PyObject_Call + 97
56  org.python.python             	0x000000010743e9bf 0x107412000 + 182719
57  org.python.python             	0x00000001074216c6 PyObject_Call + 97
58  org.python.python             	0x000000010742b78d PyEval_EvalFrameEx + 9728
59  org.python.python             	0x000000010742f869 0x107412000 + 120937
60  org.python.python             	0x000000010742b63a PyEval_EvalFrameEx + 9389
61  org.python.python             	0x0000000107429147 PyEval_EvalCodeEx + 1934
62  org.python.python             	0x000000010742f8df 0x107412000 + 121055
63  org.python.python             	0x000000010742b63a PyEval_EvalFrameEx + 9389
64  org.python.python             	0x000000010742f869 0x107412000 + 120937
65  org.python.python             	0x000000010742b63a PyEval_EvalFrameEx + 9389
66  org.python.python             	0x0000000107429147 PyEval_EvalCodeEx + 1934
67  org.python.python             	0x00000001074289b3 PyEval_EvalCode + 54
68  org.python.python             	0x0000000107464c70 0x107412000 + 339056
69  org.python.python             	0x0000000107464d3c PyRun_FileExFlags + 165
70  org.python.python             	0x0000000107464726 PyRun_SimpleFileExFlags + 410
71  org.python.python             	0x0000000107488e27 Py_Main + 2715
72  libdyld.dylib                 	0x00007fff85d257e1 start + 1

Steps to reproduce:
Add a Frame.
Push the "Add a MenuBar" button.
Push the OK button in the dialog that appears.

**Comment by DietmarSchwertberger** [comment]
Thanks a lot. This should be fixed now.

**Comment by programmingkidx** [comment]
It does appear to be fixed. Thank you.

**Comment by DietmarSchwertberger** [comment]
1.0.0b1 is online.
