### ISSUE TITLE
Feature request: make TextCtrls resizable in the design window

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#450]
Currently when you place a TextCtrl in a GridSizer, you can't click and drag one of the blue corner boxes to resize the TextCtrl. I suggest this be changed so the user can change the length and width of a TextCtrl.

**Comment by DietmarSchwertberger** [comment]
I doubt that this is worth the effort.

I usually want to set sizes to nice values like 60,80, 100 and most of the time in combination with -1.

When setting sizes, most of the time more than one widget is affected. You can repeat the latest change using `Ctrl-R` and `Ctrl-Y`.

You may implement it yourself and submit a pull request. The starting points are `misc.SelectionMarker`  and `edit_windows.py` `ManagedBase.finish_widget_creation`.
