### ISSUE TITLE
Can't add slot to boxsizer

### ISSUE THREAD

**Issue by iMacker2020** [wxGlade/wxGlade#451]
When I added a StaticText to a boxsizer, I right-clicked on the box and selected "Add Slot". Nothing happened. 

Steps to reproduce:
Add a Frame.
Add a StaticText to "SLOT 1". 
Right click on the BoxSizer and select "Add Slot".
Sometimes nothing happens.

Info:
wxGlade 1.0.0b1
wxPython 3.0.2.0
Python 2.7.2

**Comment by DietmarSchwertberger** [comment]
I would guess that this is a bug in wxPython which delays event handling. On 3.0.3 I did see it only once. There's nothing I could do, as there is no installable version where these could be reproduced. There is installable version of 3.0.2 available any more. If you can provide me with a 3.0.2 and this reproducibly fails, I can fix it.
If you continue to see these problems, please upgrade to some recent versions.

**Comment by DietmarSchwertberger** [comment]
Could you please check whether this would fix your problem?

In main.py wxGlade.OnInit please comment out this line:

self.Bind(wx.EVT_IDLE, self.OnIdle)

This modification will block error messages, so it would not be a solution, but it would indicate the way to go.

**Comment by DietmarSchwertberger** [comment]
Please try this:

Comment out `event.Skip()` in `main.py wxGlade.OnIdle`:

```
    def OnIdle(self, event):
        "Idle tasks - currently show error messages only;  see: show_msgdialog()"
        self.show_msgdialog()
        #event.Skip()
```

**Comment by DietmarSchwertberger** [comment]
I have modified wxGlade to use CallLater instead of EVT_IDLE on macOS with wxPython Classic.
Please try the latest repository version.

**Comment by DietmarSchwertberger** [comment]
The workaround is in 1.0.0b2.
