### ISSUE TITLE
StaticText not properly aligned in frame

### ISSUE THREAD

**Issue by iMacker2020** [wxGlade/wxGlade#452]
![misaligned](https://user-images.githubusercontent.com/69224955/97378688-52042b80-1899-11eb-9ed2-436198551eca.png)

Sometimes when I change the font of a StaticText, it will resize but not reposition itself correctly in the design window. The picture shows the design window at the top with the StaticText barely visible. The Preview window shows how it should look.

Directions:
Add a StaticText to SLOT 1.
Add another slot.
Add a TextCtrl to SLOT 2.
For this TextCtrl:
- set the proportion to 1
- check the EXPAND checkbox

For the StaticText:
- set the Font to 30 point, Bold, with a Family of Modern.

The result is that sometimes the StaticText will be mostly covered by the TextCtrl.

My Info:
Python 2.7.2
wxPython 3.0.2.0
wxGlade 1.0.0b1

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. I have committed a change. I think this will fix it. Please try.

**Comment by DietmarSchwertberger** [comment]
1.0.0b2 is online.
