### ISSUE TITLE
Feature request: be able to set minimum size

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#453]
Please add the ability to set the minimum size for a widget. Currently the size of a widget can be set. The minimum size is different because it controls how small a widget can become. All widgets that are a subclass of wx.Window have the SetMinSize() function available to them. This setting probably should be located under the Size setting found in the Common tab. 

Right now a window with widgets can be resized to the point it is nothing but a dot on the screen. With the minimum size set the window will not be resizable to that small a size.

Thank you.

**Comment by DietmarSchwertberger** [comment]
I will look into this after 1.0.

As workaround, you can enter it already under Code -> Property.
I have not tested it, just check whether the generated code is OK:
![grafik](https://user-images.githubusercontent.com/5512021/97788968-2f398600-1bbd-11eb-944f-610beace3e28.png)

**Comment by programmingkidx** [comment]
Thanks for the suggestion.
Can wxGlade be changed to use these properties in the preview window? Currently I am able to resize the preview  window to virtually nothing even with the MinSize property set.

**Comment by DietmarSchwertberger** [comment]
Please check the generated code. For widgets `SetMinSize` is called already, not `SetSize`.
If you want to restrict the minimum size of a frame, you can call `SetMinSize` on this.

**Comment by programmingkidx** [comment]
This is true for the generated code. I was hoping to test the MinSize property using the preview window.

**Comment by DietmarSchwertberger** [comment]
Thats using the same code.

**Comment by programmingkidx** [comment]
For some reason it doesn't work.

**Comment by DietmarSchwertberger** [comment]
Do you have any indication that the preview behaves different from the final code? They're both using SetMinSize.
Maybe, SetMinSize does just behave different from what you are expecting.

**Comment by programmingkidx** [comment]
Yes, I did generate the code and it worked correctly. Resizing stopped at the limit I set. The preview window did not stop at the limit and I was able to make it very small.

**Comment by DietmarSchwertberger** [comment]
Could you please upload a minimum .wxg sample where you see the difference?
The file I'm using does not stop resizing.

**Comment by DietmarSchwertberger** [comment]
And please state platform and versions.

**Comment by programmingkidx** [comment]
Info: 
Mac OS 10.8
wxGlade 1.0.0b1
Python 2.7.2
wxPython 3.0.2.0

**Comment by iMacker2020** [comment]
Sample file
[resize.zip](https://github.com/wxGlade/wxGlade/files/5504256/resize.zip)

**Comment by programmingkidx** [comment]
[resize.zip](https://github.com/wxGlade/wxGlade/files/5504258/resize.zip)
Sample file

**Comment by DietmarSchwertberger** [comment]
But that's Frame's min size.

As written above:
> Please check the generated code. For widgets SetMinSize is called already, not SetSize.
> If you want to restrict the minimum size of a frame, you can call SetMinSize on this.

I will add min size to revision 1.1. For Frame, you can check the size of the design window by looking at the size property.

**Comment by DietmarSchwertberger** [comment]
Attributes "max size" for sizer elements and "min size" for frames is in the master branch now. The user interface may change before a release 1.1.
