### ISSUE TITLE
"Add Slot" not working

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#454]
When I right-click on a BoxSizer and select "Add Slot", nothing happens.

Steps to reproduce:
Add a frame.
Right-click on sizer_1.
Select "Add Slot".

Result:
Nothing happens.

Expected results:
A new slot appears.

My info:
wxPython 3.0.2.0
Python 2.7.2
wxGlade 1.0.0b1
Mac OS 10.8.5.

Note:
When I switched applications then switched back to wxGlade, several slots had appeared.

**Comment by programmingkidx** [comment]
Just wanted to add that deleting the slots does not work. I tried the delete key and selecting "Remote Slot" from the slot's contextual menu.

**Comment by DietmarSchwertberger** [comment]
I would guess that this is a bug in wxPython which delays event handling. On 3.0.3 I did see it only once. There's nothing I could do, as there is no installable version where these could be reproduced. There is installable version of 3.0.2 available any more. If you can provide me with a 3.0.2 and this reproducibly fails, I can fix it.
If you continue to see these problems, please upgrade to some recent versions.

**Comment by DietmarSchwertberger** [comment]
Could you please try whether this has an influence?
In `main.py wxGlade.OnInit` please comment out this line:
```
self.Bind(wx.EVT_IDLE, self.OnIdle)
```

**Comment by programmingkidx** [comment]
I think this fixed the problem. I tried adding and removing slots many times and the problem did not return.

**Comment by DietmarSchwertberger** [comment]
I think that wx.CallAfter 'events' are somehow stalled in the queue, caused by EVT_IDLE.

If you can try to comment/uncomment a few times to confirm the correlation, I would prepare some experiements to find a workaround (e.g. I could imagine that a wxTimer instead of EVT_IDLE could work as well).

**Comment by programmingkidx** [comment]
I did uncomment the code and did see a few times where a slot will not add or delete. The thing is this problem is so random. This could be a bug with wxPython. So far when the line is commented, the issue does not return.

**Comment by DietmarSchwertberger** [comment]
Could you please also try whether this would work as well?
 - keep the `self.Bind` call
 - comment out `event.Skip()` in `main.py wxGlade.OnIdle`:
```
    def OnIdle(self, event):
        "Idle tasks - currently show error messages only;  see: show_msgdialog()"
        self.show_msgdialog()
        #event.Skip()
```

**Comment by DietmarSchwertberger** [comment]
I have modified wxGlade to use CallLater instead of EVT_IDLE on macOS with wxPython Classic.
Please try the latest repository version.

**Comment by programmingkidx** [comment]
I did about 10 tests and could not reproduce the problem anymore. So I think this issue is fixed. Thank you.

**Comment by DietmarSchwertberger** [comment]
The workaround is in 1.0.0b2.
