### ISSUE TITLE
Pushing return on a text field should update the design window

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#455]
Currently when entering a value in one of the fields (for example the Border textfield under the Layout tab), if the user pushes the return key, no changes are implemented into the design window. I suggest this be changed so that the GUI does update once the return key is pushed. It would allow the user to see the difference the change in value  would make more easily.

My Info:
OS: Mac OS 10.8.5
wxGlade 1.0.0b1
wxPython 3.0.2.0
Python 2.7.2

**Comment by DietmarSchwertberger** [comment]
It's implemented and on Windows it's actually working.
I will look into this on macOS.

**Comment by DietmarSchwertberger** [comment]
I think it should be fixed now. Turned out that inside an EVT_TEXT_ENTER handler the spin control value is not yet set to the new value on macOS only. The fix is specific to properties with spin controls. Other, text only, should not have problems.

**Comment by programmingkidx** [comment]
Fixed.

**Comment by DietmarSchwertberger** [comment]
1.0.0b2 is online.
