### ISSUE TITLE
Entering a letter in the proportion or border field causing an internal error

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#456]
When a widget is select and someone enters a letter into the proportion or border field, an internal error message is displayed. I think it would be better if the error was handled more gracefully. Instead of an internal error, a dialog could be displayed that alerts the user that the field only uses numbers.

My Info:
wxGlade 1.0.0b1
wxPython 3.0.2.0
Python 2.7.2
Mac OS 10.8.5

**Comment by DietmarSchwertberger** [comment]
On other platforms it's not possible at all to enter non-digits. I will check how to handle it on macOS.

**Comment by DietmarSchwertberger** [comment]
should be fixed now.

**Comment by programmingkidx** [comment]
It is fixed.
