### ISSUE TITLE
Add git commit ID to About dialog for beta build

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#457]
Currently only the version of wxGlade is displayed in the About dialog. This isn't enough information to determine which version of this program the user is testing. If the About dialog displayed the git commit ID, this would help a tester know if he or she is using the correct version. I understand this git commit ID would be unpleasant to look at. So I suggest that this ID only be displayed when the user clicks on the version text.

**Comment by DietmarSchwertberger** [comment]
Unfortunately this requires reading the output from git, e.g. 
```
subprocess.check_output(["git", "describe"]).strip()
```
This is something that I won't implement...
