### ISSUE TITLE
Setting color of StaticText control does not work

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#458]
Charging the color of a StaticText control does not work.

Step to reproduce:
Select a StaticText widget.
Under the Common tab check the Font checkbox.
Push the "..." button.
Push the "Specific Font" button.
Set the color to Aqua.
Push the Ok button.

Results:
The color of the StaticText is still black.

Expected results:
The color of the StaticText to be Aqua.

My Info:
Windows XP
wxGlade 1.0.0b1
wxPython 4.1.0
Python 2.7.18

**Comment by DietmarSchwertberger** [comment]
This property is for the font. For the colour, use Foreground.

**Comment by programmingkidx** [comment]
I tried the foreground. It did not change the color of the StaticText.

**Comment by DietmarSchwertberger** [comment]
I have just tried on Windows 10 and there's no problem.
If you have a specific file that does not work, I will have a look. Otherwise I would assume that it's Windows XP specific and that's not something that I willl work on.

**Comment by programmingkidx** [comment]
I forgot to mention I tried changing the foreground on Mac OS 10.8 and it didn't work. The background option does work. The foreground option does work on Windows XP also.

**Comment by programmingkidx** [comment]
I just did another test and the preview will display the the colored StaticText correctly, just not the design window.

**Comment by DietmarSchwertberger** [comment]
On which platform?

**Comment by programmingkidx** [comment]
Mac OS 10.8.

**Comment by DietmarSchwertberger** [comment]
Thanks. Should be fixed now.

**Comment by programmingkidx** [comment]
It is fixed :)
