### ISSUE TITLE
wxGlade modifies generated Event-Handler when generating Code a second time

### ISSUE THREAD

**Issue by StPanning** [wxGlade/wxGlade#459]
Version 1.0.0b1 on Python 3.8.5 and wxPython 4.1.0 

Steps to reproduce:
1) Create Eventhandler in wxGlade:
```Python
    def OnPaint(self, event):  # wxGlade: PlotBoard.<event_handler>
        print("Event handler 'OnPaint' not implemented!")
        event.Skip()
```

2) remove the 'print' line
```Python
    def OnPaint(self, event):  # wxGlade: PlotBoard.<event_handler>
        event.Skip()
```
3) Generate Code Again
```Python
    def OnPaint(self, event):  # wxGlade: PlotBoard.<event_handler>
        print("Event handler 'OnPaint' not implemented!")
        event.Skip()
```
the print line is visible again. The Eventhandler is recreated, instead of left alone.

[plotboard_wxg.gz](https://github.com/wxGlade/wxGlade/files/5569688/plotboard_wxg.gz)

**Comment by DietmarSchwertberger** [comment]
Please try "Keep user code".
![grafik](https://user-images.githubusercontent.com/5512021/99732122-36b6c580-2abf-11eb-81f6-00aec21bf36a.png)

**Comment by DietmarSchwertberger** [comment]
P.S.: You don't need the sizer in this example. Also, a grid sizer as toplevel sizer is usually not a good idea.

**Comment by StPanning** [comment]
thanks, that solved the problem.
