### ISSUE TITLE
SplitterWindow not displaying circle on resize handle

### ISSUE THREAD

**Issue by iMacker2020** [wxGlade/wxGlade#460]
The SplitterWindow control does not display the circle on the resize handle. This issue is present when the wxSP_3DSASH is on or off. This issue isn't present on Mac OS X, but it is present on Windows XP. 

I included the wxg file. 

My Info:
Windows XP
wxGlade 1.0.0b1
Python 2.7.18
wxPython 4.1.0

How it looks on Mac OS X:
![Mac OS X splitter](https://user-images.githubusercontent.com/69224955/99923472-e7ada200-2d03-11eb-9123-8d14ecc9c7c8.png)

How it looks like on Windows XP - no circle:
![Windows XP splitter](https://user-images.githubusercontent.com/69224955/99923512-090e8e00-2d04-11eb-8746-ae42c67c0a22.png)

[wxglade.zip](https://github.com/wxGlade/wxGlade/files/5580821/wxglade.zip)

**Comment by DietmarSchwertberger** [comment]
That's normal behaviour on WIndows. There has never been a circle.
You need to make sure yourself that the user sees that there is a border that can be dragged.
