### ISSUE TITLE
Design and preview window very different

### ISSUE THREAD

**Issue by iMacker2020** [wxGlade/wxGlade#461]
I created a view hierarchy using Boxsizers. The layout looks correct on the Design window. In the preview window most of the widgets are missing. 

The design window is on top. The preview window is on the bottom.
![design and preview](https://user-images.githubusercontent.com/69224955/100257008-704e5d00-2f13-11eb-8c91-9aaccdf7d7d2.png)

This is the wxg file:
[example.zip](https://github.com/wxGlade/wxGlade/files/5598097/example.zip)

My info:
wxGlade 1.0.0b1
wxPython 4.1.0
Python 2.7.18
Windows XP

**Comment by DietmarSchwertberger** [comment]
The structure of a scrolled window in a sizer etc. will not work. By incident wxGlade does display better than what will come out finally.

See this update with a more useful structure:
[example_update.zip](https://github.com/wxGlade/wxGlade/files/5599048/example_update.zip)

**Comment by DietmarSchwertberger** [comment]
P.S.: Don't use (grid) sizers to present data. Use proper structures like grid or listctrls.
