### ISSUE TITLE
Edit menu should have clipboard functions

### ISSUE THREAD

**Issue by iMacker2020** [wxGlade/wxGlade#462]
I was trying to copy a frame. I right clicked on the frame and did not see any clipboard functions like Cut, Copy, Paste, or Clear. The Edit menu was also missing these functions. Please add this missing functionality to wxGlade.

My Info:
wxGlade 1.0.0b1

**Comment by DietmarSchwertberger** [comment]
You can use Duplicate, Ctrl-C or drag a frame to the application (the root of the tree view).

**Comment by DietmarSchwertberger** [comment]
The problem with menu entries is that there is a palette, a property notebook and a tree. Which part would the edit menu refer to? The context menus are clear and actually, the Ctrl key combinations are the more useful options.
