### ISSUE TITLE
Add warning for names containing special characters

### ISSUE THREAD

**Issue by dlmarquis** [wxGlade/wxGlade#463]
I accidentally used a hyphen when naming my application, and Python kept throwing a "can't assign to operator" error until I changed it. In situations like this, there should be some indication that the name could be invalid, to avoid confusion.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. The '-' is allowed as it's required for LISP. I will change this.

**Comment by DietmarSchwertberger** [comment]
I will only change this for 1.1. The risk to introduce other bugs is too high.

**Comment by DietmarSchwertberger** [comment]
pre-release 1.1.0a1 is online now
