### ISSUE TITLE
Toolbar is too small and is not fully displayed

### ISSUE THREAD

**Issue by A2va** [wxGlade/wxGlade#464]
wxGlader version: 1.0.0b
I created a layout with wxGlade and the preview is good.
![image](https://user-images.githubusercontent.com/49582555/101182391-4bae5f80-364e-11eb-9226-59b029ee8375.png)
But when i export the code that render like this:
![image](https://user-images.githubusercontent.com/49582555/101182894-03dc0800-364f-11eb-9549-1cf817544f9e.png)

I have already worked with a toolbar with wxFormBuilder and it works so I don't think it's wxPython

**Comment by DietmarSchwertberger** [comment]
Please upload sample files.

**Comment by A2va** [comment]
Inside the zip I put the wxGlade files and the generated code. For the custom widget DisplayCanvas you can find to code [here](https://github.com/A2va/Transimage/blob/master/transimage/canvas.py) and his instanciation look like this:
```python
DisplayCanvas(self,id=wx.ID_ANY,size=wx.DefaultSize,ProjectionFun=None,BackgroundColor='#00ff00')
```
[wxGlade files.zip](https://github.com/wxGlade/wxGlade/files/5646839/wxGlade.files.zip)

**Comment by DietmarSchwertberger** [comment]
Next time please attach a self-contained sample which does not refer non-existant bitmaps...

This looks like a bug in wx/Python. Once you add a second tool or a separator, things seem to work.

**Comment by A2va** [comment]
Sorry for the bitmap I forgot it. 
Thanks for your answer, I will report the bug to wxPython.

**Comment by DietmarSchwertberger** [comment]
When reporting, attach sample code with a panel instead of custom widget and a bitmap from the art selector:

[min_sample.zip](https://github.com/wxGlade/wxGlade/files/5647382/min_sample.zip)
