### ISSUE TITLE
Reproduceable issue when moving spacer between slots under certain circumstances

### ISSUE THREAD

**Issue by RagingRoosevelt** [wxGlade/wxGlade#465]
# General

Produces an Error Dialog with an error of type AttributeError with no summary.

wxGlade version: 0.9.6

[wxglade.log](https://github.com/wxGlade/wxGlade/files/5644207/wxglade.log)

Visual representation of the scenario:
![image](https://user-images.githubusercontent.com/6985440/101194714-32d48880-3613-11eb-9d81-e921f00d2f59.png)

# Steps to reproduce
1. new program instance
2. add frame
3. add second slot to default spacer
4. add 2-slot spacer into slot 2 of default spacer
5. add text control to slot 1 of child spacer
6. try to move the child spacer from slot 2 to slot 1 of the parent spacer

# Similar Reproducing Scenarios

I could also generate the issue by starting out with the text control in slot 2, moving it to slot one, then moving the child spacer to the other slot of its parent.

# Similar but Non-Reproducing Scenarios
I tried to reproduce the issue under several separate circumstances that didn't reproduce the issue:
1. Skipping step 5 (adding text control)
2. In step 4, making the child spacer 1-slot rather than 2-slot
3. In step 5, rather than adding text control slot 1 of the child spacer, adding it to slot 2

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting, but 0.9 will not see any fixes any more.
I have just tested with 1.0.0 and there it seems to work. (1.0.0 will not generate the sizer as before. Instead, it will add either nothing or a  panel plus sizer.)
Please use either the current repository version or 1.0.0b from Sourceforge or Github.
