### ISSUE TITLE
unable to launch wxglade

### ISSUE THREAD

**Issue by HSeffouh1** [wxGlade/wxGlade#467]
I'm not able to start wxglade.
under Windows OS, wxpython installed.
running command > py wxglade.py but nothing happens 
any thoughts.
Thanks

**Comment by DietmarSchwertberger** [comment]
I don't know what `py` is supposed to do.
You should have a Python interpreter installed.
Check where your Python interpreter is located.
I can run e.g. `D:\Python\Python36-64\python.exe d:\Python\wxglade\wxglade.py`

**Comment by HSeffouh1** [comment]
> I don't know what `py` is supposed to do.
> You should have a Python interpreter installed.
> Check where your Python interpreter is located.
> I can run e.g. `D:\Python\Python36-64\python.exe d:\Python\wxglade\wxglade.py`

works!! thanks a lot
i used "python wxglade.py" instead of "py wxglade.py"

**Comment by HSeffouh1** [comment]
Thx @DietmarSchwertberger
