### ISSUE TITLE
wxSpinCtrlDouble not accepting decimals

### ISSUE THREAD

**Issue by HSeffouh1** [wxGlade/wxGlade#468]
Hi @DietmarSchwertberger and All
I'm having an issue on wxGlade not being able to type decimals.
i've got the 1.0.0b2 wxGlade 
Python 3.7 and wxpython 4.1.1
any idea please?
![image](https://user-images.githubusercontent.com/53316053/102780640-94784f00-4396-11eb-9a3f-86dd2d9b87c6.png)

**Comment by DietmarSchwertberger** [comment]
Where can't you type decimals? Inside wxGlade? In the final application? What does the generated code look like?
It might be related to localization.
E.g. in my locale, I need to enter decimals with a comma while the Range needs to be entered with a decimal point:
![grafik](https://user-images.githubusercontent.com/5512021/102802690-55a6c100-43b7-11eb-9f82-1ec24a1a2a01.png)

![grafik](https://user-images.githubusercontent.com/5512021/102802735-65260a00-43b7-11eb-91f2-efe1fdfae917.png)

**Comment by HSeffouh1** [comment]
It does not allow me to add numbers after the dot on the preview application.
also tried with a coma, unable to.

![image](https://user-images.githubusercontent.com/53316053/102826951-f9a56200-43e1-11eb-8fd7-bcb2835c9695.png)

![image](https://user-images.githubusercontent.com/53316053/102827063-2eb1b480-43e2-11eb-89b1-af6e6e09856d.png)

**Comment by DietmarSchwertberger** [comment]
The code looks correct. Does SpinCtrlDouble in the wxPython demo work for you? I would guess not.

**Comment by DietmarSchwertberger** [comment]
Ah, OK, I see. The initalization value needs to match the number format settings of the OS.
I will change this to use `initial=0.0` instead of the string value `"0.0"`.

**Comment by HSeffouh1** [comment]
still same thing, not accepting decimals :-( 
![image](https://user-images.githubusercontent.com/53316053/102914595-d54c9280-4480-11eb-9513-318c6b69e113.png)

**Comment by DietmarSchwertberger** [comment]
Seems that 4.1.1 requires the call of SetDigits.
I'm not sure whether it's a bug or a feature. The trac tickets are not clear:
https://trac.wxwidgets.org/ticket/18764
https://trac.wxwidgets.org/ticket/17085

The old behaviour was certainly more useful.

**Comment by DietmarSchwertberger** [comment]
I'm about to add the property. As workaround, you can add `self.N2_Input.SetDigits(2)` to 'code to be inserted after'.

**Comment by HSeffouh1** [comment]
> I'm about to add the property. As workaround, you can add `self.N2_Input.SetDigits(2)` to 'code to be inserted after'.

Thanks for the info, however the code inserted on 'Code to be inserted after' did not work..

**Comment by DietmarSchwertberger** [comment]
It will not work for the preview as the code... properties are not used for the preview, but it should work for the generated code.
Does it not?

**Comment by HSeffouh1** [comment]
> It will not work for the preview as the code... properties are not used for the preview, but it should work for the generated code.
> Does it not?

Ohh I see!! indeed i have not tried it, i will generate the code and test it out.
keep you posted!
thx again

**Comment by DietmarSchwertberger** [comment]
1.0.1 is online.
