### ISSUE TITLE
RuntimeError after deleting a button from a dialog

### ISSUE THREAD

**Issue by jostrn** [wxGlade/wxGlade#469]
Hi!

I created a dialog with three buttons, then I deleted one of these buttons with the Remove button in its context menu. When I click on the top level dialog then, the following error appears reproducible.

Regards,
Josef

### Error Summary
An internal error occurred
Error type: <class 'RuntimeError'>
Error summary: No summary available
This is a bug - please report it.

### Error Details
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'RuntimeError'>
Exception details:   wrapped C/C++ object of type TextCtrl has been deleted

Application stack traceback:
  File "C:\Program Files\wxGlade-1.0.0\edit_windows.py", line 1009, in on_size
    WindowBase.on_size(self, event)
  File "C:\Program Files\wxGlade-1.0.0\edit_windows.py", line 491, in on_size
    prop_size.set(size_widget)
  File "C:\Program Files\wxGlade-1.0.0\new_properties.py", line 1759, in set
    IntPairPropertyD.set(self, value, activate, deactivate, notify)
  File "C:\Program Files\wxGlade-1.0.0\new_properties.py", line 108, in set
    self.update_display()
  File "C:\Program Files\wxGlade-1.0.0\new_properties.py", line 1472, in update_display
    self.text.SetValue(self._convert_to_text(self.value) or "")

Date and time:       2020-12-26T17:47:48.835369
Python version:      3.7.9
wxPython version:    4.1.1
wxWidgets platform:  __WXMSW__
wxGlade version:     1.0.0

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. I can't reproduce this yet.
I could add a containment, but I would prefer to check why it happens to see whether there is more to fix.
Would you mind uploading a minimum sample .wxg plus step by step. (Also, please specify, which context menu: from the tree or in the design window.)

**Comment by DietmarSchwertberger** [comment]
(I tried with both the stock buttons OK/NO/CANCEL as well with three other buttons.)
![grafik](https://user-images.githubusercontent.com/5512021/103157435-0d224580-47b3-11eb-9bad-96cc8150101f.png)

**Comment by DietmarSchwertberger** [comment]
@jostrn : could you please provide example plus description soon? I would like to fix this and relase 1.0.1.

**Comment by jostrn** [comment]
Dear Dietmar, here's an animated gif how I get to the bug:

![process](https://user-images.githubusercontent.com/17170266/103293635-8a86c980-49f0-11eb-97b1-a2f48768c655.gif)

Thank you for caring for wxGlade. It is a great tool.

**Comment by DietmarSchwertberger** [comment]
Thanks, but that's a different error "TypeError". This was caused by a bug in new_properties.py and triggered by deleting the "Affirmative" button, i.e. the OK button:
![grafik](https://user-images.githubusercontent.com/5512021/103314239-c0dd3c80-4a22-11eb-923a-5ec42b24c7b8.png)
After deleting "button_OK", the property causes this TypeError.
A fix is now in the repository.


Do you remember how to reproduce the "RuntimeError" from your first post? I have checked the sources, but could not find how this can happen.

**Comment by DietmarSchwertberger** [comment]
P.S.: I could reproduce the RuntimeError now at least once. I will work on this. It occurs only after the TypeError, I think.

**Comment by DietmarSchwertberger** [comment]
1.0.1 is online.
