### ISSUE TITLE
[Feature] Add "Undo" function [sf#47]

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxGlade/wxGlade#47]
**Reported by rsonnenfeld on 2018-01-01 02:53 UTC**
Another reviewer mentioned this.  It's a good idea, but I certainly wouldn't make it a top priority if you have more interesting work.  I have already wished I could undo a change.  Start with one level deep, maybe go three or four if it's not too painful.  The current workaround is to just manually delete the thing you just did.  Undo could be limited to deleting the most recently added widget/spacer/panel/sizer, etc., or it could extend to undoing the property you just changed (more work probably ...).

**Comment by DietmarSchwertberger** [comment]
**Updated by dschwertberger on 2018-01-01 12:12 UTC**
- **status**: open --> accepted
- **assigned_to**: Dietmar Schwertberger
- **Group**: 0.9.0 --> 1.1.0

**Comment by DietmarSchwertberger** [comment]
**Commented by dschwertberger on 2018-01-01 12:12 UTC**
That's certainly on the list.
The internal structures would not allow this easily at the moment. At the moment it would require to dump the whole file on every structural change just to be able to restore it. This might be too slow.
For now undo could only be implemented for property changes. See history.History if you want to contribute...

**Comment by DomenGabercek** [comment]
I've been using wxGlade as a template for my project some time now. Adding my own custom widgets and functionality. I would also like to add the Undo function, but I think that implementing this functionallity is out of my league, I also couldn't find any information on the mentioned history.History. I'd like to know if you have already started working or this, is this a plan for the near or far future.

**Comment by DietmarSchwertberger** [comment]
The history is in the history.py file. It's currently uses as this:
 - select one widget
 - modify e.g. "border = 3" and "Alignment wxALIGN_CENTER"
 - select another widget
 - press Ctrl-Y to apply the last modification to this widget (i.e. Alignment)
 - or press Ctrl-R to apply all the modifications from the previous widget to this widget (i.e. border + alignment)

Revision 0.9 will have a toolbar and related menu items to make it easier to find these features...
The history does not yet cover grid based properties (e.g. event tables). I'm working on copy&paste improvements for these and hopefully can add them to the history as well.

A simple undo of properties should not be too hard to implement, maybe for 1.0.
A full undo including structural modifications (adding/removing widgets) will take longer, though.

**Comment by DietmarSchwertberger** [comment]
A first implementation is in the repository (master branch).

**Comment by DietmarSchwertberger** [comment]
pre-release 1.1.0a1 is online now
