### ISSUE TITLE
"Save As..." dialog defaults to entire path as file name

### ISSUE THREAD

**Issue by deeppunster** [wxGlade/wxGlade#473]
The "Save As" dialog defaults to including the entire path as the filename on a Mac.  If not changed, it results in the file being saved in the directory, but with the entire path included in the file name.

For example, if my first "Save As" saved the file as "/Users/me/wxglade.wxg", then a subsequent "Save As" dialog will have "/Users/me/wxglade.wxg" as the proposed filename.  it should only be "wxglade.wxg".

This occurs on MacOS 10.14.6 (Mojave) with Python 3.9.1.  (This does NOT occur on Manjaro with Python 3.8.)

If you need additional information to reproduce or screenshots, please let me know.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. I will look into this in the next days.
I'm not a fan of the macOS file dialogs...

**Comment by DietmarSchwertberger** [comment]
It's fixed now in the repository in branches master and REV_1.0

**Comment by DietmarSchwertberger** [comment]
Revision 1.0.2 ist online.
