### ISSUE TITLE
Adding more rows or columns to GridSizer only makes it smaller

### ISSUE THREAD

**Issue by iMacker2020** [wxGlade/wxGlade#474]
I was adding checkboxes to a Frame with a 10x10 gridsizer in it. I noticed the distance between checkboxes was too high, so I increased the number of rows to 20.

<img width="728" alt="before" src="https://user-images.githubusercontent.com/69224955/107827610-1b252900-6d55-11eb-8513-1c8e46c62df7.png">

 Instead of increasing the number of rows, the gridsizer became smaller. 

<img width="730" alt="after" src="https://user-images.githubusercontent.com/69224955/107827622-22e4cd80-6d55-11eb-9f64-73c2953bf14b.png">

I did want the cells to become smaller, but extra cells should have appeared also.

My Info:
M1 Mac
Mac OS 11.1
wxPython 4.0.6
Python 2.7.14
wxGlade 1.0.1

**Comment by DietmarSchwertberger** [comment]
The behaviour is correct. It has now 20 rows therefore they are smaller.
You need to add the slots as well before you can add anything.

"Insert Row Before"  or "Add row" will add slots.

I know that this should be improved, but it's not on the list for short term improvements.

**Comment by iMacker2020** [comment]
Thank you for the suggestion.
