### ISSUE TITLE
Setting bottom border does not move widget

### ISSUE THREAD

**Issue by iMacker2020** [wxGlade/wxGlade#475]
The bottom border does not appear to work. When I check wxBottom and set the border to a high value for a widget, I expect the widget to move upwards. This does not happen.

Steps to reproduce:
Create a frame.
Add a 5x5 gridsizer to it.
Add three radio buttons to it in a vertical top to bottom way. 
Select a radio button.
Under the Layout tab check wxBottom.
Under border set it to a high value.

<img width="1227" alt="no change" src="https://user-images.githubusercontent.com/69224955/107831257-a43f5e80-6d5b-11eb-8163-f4f61243ed69.png">

My info:
M1 Mac
Mac OS 11.1
wxPython 4.0.6.
wxGlade 1.0.1
Python 2.7.14

**Comment by DietmarSchwertberger** [comment]
I don't see a bug here. A GridSizer has cells of constant size. A FlexGrid sizer would increase the cell size.
