### ISSUE TITLE
Gridsizer not always fully covering frame

### ISSUE THREAD

**Issue by iMacker2020** [wxGlade/wxGlade#476]
Steps to reproduce:
Create a new frame.
Remove sizer_1.
Add a 20x20 GridSizer.
The grid will sometimes not fully cover the window.
<img width="717" alt="not fully there" src="https://user-images.githubusercontent.com/69224955/107865274-ad4f2f00-6e32-11eb-9bd4-474ae9de5273.png">

This issue doesn't happen all the time. It happens randomly.

My info:
M1 Mac
Mac OS 11.1
wxPython 4.0.6
wxGlade 1.0.1
Python 2.7.14

**Comment by DietmarSchwertberger** [comment]
I can't see this on my installations. I don't have a 4.0.6 on macOS, though.
Are you sure that the screenshot is from a GridSizer, not FlexGridSizer?

**Comment by iMacker2020** [comment]
I'm pretty sure it was from GridSizer.

**Comment by iMacker2020** [comment]
I was doing some testing and I found I could reproduce this issue using a Gridbagsizer. So it could be a gridbagsizer. When I create a frame and replace the boxsizer with a gridbagsizer I see this issue. The problem is the Size attribute under the Common tab is checked and set to 585, 525. I feel this should not happen.

**Comment by iMacker2020** [comment]
The frame was what actually had its Size attribute under the Common tab set to 585, 525, not the gridbagsizer. I am not sure why the gridbagsizer doesn't expand to fill the entire frame like a gridbagsizer would. This problem is also seen with the flexgridsizer.  Attached is a wxg file that demonstrates this issue.
[problem.zip](https://github.com/wxGlade/wxGlade/files/5978553/problem.zip)

**Comment by DietmarSchwertberger** [comment]
The gridbagsizer is not supposed to fill the available space unless setting a row or col to be growable.
If you use a gridbagsizer with 20x20, this is a clear indication that your overall structure has a problem.
From your bug reports I would guess you are trying to use grid sizers to resemble pixel placement of widgets.
Forget about this. It's a mess and a waste of time.

Please follow the documentation and keep in mind:

http://wxglade.sourceforge.net/docs/wxbasics.html#sizers-layout-managers

Note

    For your own projects, always use the simplest available sizers. Usually you will need mainly box sizers and maybe one or two FlexGridSizers.
    Use nested sizers to match the hierarchical / logical structure of your project. This will make it easy to re-arrange things to find the best user interface.
    Never ever try to use a Grid(Bag)Sizer as main sizer of a window trying to resemble pixel placement or Tkinter’s grid geometry manager. This is a mess to create and maintain. Actually, a GridBagSizer is rarely needed.
