### ISSUE TITLE
Feature request: copy and paste support for wxMenuBar

### ISSUE THREAD

**Issue by iMacker2020** [wxGlade/wxGlade#477]
Currently when displaying a contextual menu for a wxMenuBar, there is no copy or paste options available. This makes moving a menubar from one frame to another very difficult. I suggest that this feature be added to wxGlade.

**Comment by DietmarSchwertberger** [comment]
I will look into this, but you can use Ctrl-C / Ctrl-V or Drag & Drop.

**Comment by iMacker2020** [comment]
> On Feb 15, 2021, at 12:53 PM, Dietmar Schwertberger <notifications@github.com> wrote:
> 
> 
> I will look into this, but you can use Ctrl-C / Ctrl-V or Drag & Drop.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Thank you.

**Comment by DietmarSchwertberger** [comment]
Clipboard handling is now improved.
