### ISSUE TITLE
Feature request: be able to generate code for only one frame

### ISSUE THREAD

**Issue by iMacker2020** [wxGlade/wxGlade#478]
Current when generating code for your wxg file, all the frames' code is kept in one file. I suggest an item be added to the contextual menu for frames that enables the user to generate code for just that selected frame.

**Comment by DietmarSchwertberger** [comment]
You can generate separate files.

What would be the use case for the context menu approach?

**Comment by iMacker2020** [comment]
How do you generate separate files for each window in a wxg file? The way I do it is to just copy and paste the window into a new wxg file.

The use case would be someone who created all his windows for his program in one wxg file and just wants to generate the code for one window. So keeping the code for each window in a separate file.

**Comment by DietmarSchwertberger** [comment]
http://wxglade.sourceforge.net/docs/source_code.html#prerequisites-and-code-generation
