### ISSUE TITLE
Treeview on MacOS, seems not accessible.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [wxGlade/wxGlade#479]
Hi. I'm trying wxGlade1.0.1 under MacOS10.15 using VoiceOver.
The tree view (f2) seems to be totally unaccessible.
Is it something already known? Thanks.

**Comment by DietmarSchwertberger** [comment]
I'm not sure. I'm sometimes testing with NVDA on Windows and this seems to work reasonably.
Only the grid is not really accessible and there are accessibility options to work around.

From this thread it seems that TreeCtrl is not a native control on macOS: https://wxpython-users.wxwidgets.narkive.com/9hFJ9GkQ/wx-treecontrol-not-visible-on-os-x

**Comment by DietmarSchwertberger** [comment]
I had  a look on Windows. Replacing Tree with DataViewTreeCtrl seems not too attractive. The Tree ctrl is more accessible.

**Comment by DietmarSchwertberger** [comment]
Could you please try `DVC_TreeCtrl.py` from the demo?
Is it accessible? Does VoiceOver indicate the hierarchical level of an entry?

**Comment by GabrieleBattaglia** [comment]
On 24 Feb 2021, at 22:03, Dietmar Schwertberger <notifications@github.com> wrote:
> 
> 
> Could you please try DVC_TreeCtrl.py from the demo?
> Is it accessible? Does VoiceOver indicate the hierarchical level of an entry?
> 

Hi. I’m sorry it is not.
I checked once again all the accessibility feature in preferences, they are all on.
Within a project in wxGlade, by pressing f2 or reaching the Tree by moving VoiceOver cursor, you get VO saying “Window” and nothing else happens. You can’t interact with it. On the left you have the toolbar and on the right there is the button to insert a Frame in the Application you’re building.
Gabe.

**Comment by DietmarSchwertberger** [comment]
Did you try  DVC_TreeCtrl.py from the demo?

The wxPython demo can be found here: [https://extras.wxpython.org/wxPython4/extras/](https://extras.wxpython.org/wxPython4/extras/)
Look in the subfolder matching your version number and download e.g. `wxPython-demo-4.1.1.tar.gz`

**Comment by GabrieleBattaglia** [comment]
On 26 Feb 2021, at 21:10, Dietmar Schwertberger <notifications@github.com> wrote:
> Did you try DVC_TreeCtrl.py from the demo?
> The wxPython demo can be found here: https://extras.wxpython.org/wxPython4/extras/ <https://extras.wxpython.org/wxPython4/extras/>
> Look in the subfolder matching your version number and download e.g. wxPython-demo-4.1.1.tar.gz
> 
Hi. Yes, I tried it. It is workable but in a unconfrtable manner. You must interact with every branch of the tree, than press VO+Space to expand, then deinteract, then move on the sons branches and repeat. The same thing to close/colapse. If you go just by vertical arrows, VO place its focus on the element name and you can edit it.

However, maybe I didn’t explain what I meant when writing about the tree control. It was probably due to my poor English and I apologize for that.
I were meaning the application tree in wxGlade. That area you focus on by pressing f2 once launched wxGlade.py. It works perfectly on Windows O.S. but absolutely it doesn’t under MacOS, at least here in my machine. And, as it is maybe the most important part of wxGlade, it can be considered crucial to fix, I guess.
HTH and available for any further tests or help. Gabe.

**Comment by DietmarSchwertberger** [comment]
Well, the Tree ctrl can't be fixed on macOS. So replacing it with a `DataViewTreeCtrl` would be the ohly option.
