### ISSUE TITLE
Saving each frame to a separate file should not require a file name

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#480]
When saving each frame in a wxg file to a separate file, the user should not be required to specify a file name in the dialog that the "..." button displays because it would not work. If the user does not delete this file from the Output Path field wxglade will fail when the Generate button is pushed.

Steps to reproduce:
Create a new wxg file (or see attachment).
Add two frames to it.
Add a menubar with menus to the first frame.
Click on "Application" at the top of the tree.
Click on the "Separate file for each class" radio button.
Click on the "Python" radio button under the Language area.
Click the "..." button next to "Output Path" field.

What happens:
A file save dialog will appear asking you to enter a name for a new file.

What should happen:
A dialog should appear that has you select the destination for all the class files without having to name a new file. 

Pushing the "Generate Source" button in the Properties area causes an error dialog to appear saying "Output directory does not exist".

My info:
wxPython 4.0.6
Python 2.7.14
wxGlade 1.0.1
Mac OS 11.1

**Comment by programmingkidx** [comment]
[menu_test.zip](https://github.com/wxGlade/wxGlade/files/6045766/menu_test.zip)

**Comment by DietmarSchwertberger** [comment]
Well, I did not expect anyone to use the file selector - just enter the directory name. It's much easier.

Now a DirSelector is used if multiple_files is active.
