### ISSUE TITLE
Changes to Class field for a frame do not show up in the tree

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#482]
Steps to reproduce:
Click on a frame in the tree view.
In the Common tab enter a new name in the "Class" field.
Push the return key.

Results: 
No changes are seen in the tree.

Expected Results:
The text in the parentheses of the frame should have updated to match what was typed in the Class text field. 

My Info:
Mac OS 11.1
wxPython 4.0.6
wxGlade 1.0.1
Python 2.7.14

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. It's now fixed in the repository.

**Comment by DietmarSchwertberger** [comment]
Revision 1.0.2 ist online.
