### ISSUE TITLE
Bug Report: Name Error, name 'widget' is not defined

### ISSUE THREAD

**Issue by taku-n** [wxGlade/wxGlade#483]
I got an Error Dialog.

### Error Summary

An internal error occurred while Generate Preview

Error type: NameError
Error summary: name 'widget' is not defined

This is a bug - please report it.

### Error Details

Error details:

ERROR   : An internal error occurred while Generate Preview
An unexpected error occurred!

Exception type:      <class 'NameError'>
Exception details:   name 'widget' is not defined

Application stack traceback:
  File "D:\wxGlade\application.py", line 631, in preview
    frame = preview_class(None, -1, '')
  File "E:\taku-n\scadama\_ui_316924814.py", line 155, in __init__
    self.Bind(widget.EVT_ORDER, self.on_bid_order, self.orderbutton_bid)

Date and time:       2021-03-22T18:06:30.366697
Python version:      3.8.3
wxPython version:    4.1.1
wxWidgets platform:  __WXMSW__
wxGlade version:     1.0.1

- What did you do? Maybe you want to include a screenshot.
I pressed the Show Preview button of my frame_main widget.

- What did you want to happen?
I wanted to get a preview of my frame_main widget.

- What did actually happen?
An Error Dialog appeared instead of the preview window.

- Provide a short example to reproduce the issue.
git clone https://github.com/taku-n/scadama.git
cd scadama
git checkout 275135b

- Include the internal error log file C:\Users\*\AppData\Roaming/wxglade\wxglade.log if required.

2021-03-22 18:06:29,125 root INFO: Generated E:\taku-n\scadama\_ui_316924814.py

2021-03-22 18:06:30,364 root ERROR: An internal error occurred while Generate Preview
An unexpected error occurred!

Exception type:      <class 'NameError'>
Exception details:   name 'widget' is not defined

Application stack traceback:
  File "D:\wxGlade\application.py", line 631, in preview
    frame = preview_class(None, -1, '')
  File "E:\taku-n\scadama\_ui_316924814.py", line 155, in __init__
    self.Bind(widget.EVT_ORDER, self.on_bid_order, self.orderbutton_bid)

Date and time:       2021-03-22T18:06:30.366697
Python version:      3.8.3
wxPython version:    4.1.1
wxWidgets platform:  __WXMSW__
wxGlade version:     1.0.1

### Remarks
"widget" is my widget.py having a custom widget, OrderButton.
OrderButton propagate an event, EVT_ORDER.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting.
It's fixed in master and REV_1.0 branches now.
The preview code is now ignoring this exception.

**Comment by taku-n** [comment]
I checked that it works on the master branch wxGlade.
Wow, I can see the preview now, exactly.
Thank you so much!
