### ISSUE TITLE
[Contribution] `application/x-wxg` mimetype

### ISSUE THREAD

**Issue by smac89** [wxGlade/wxGlade#484]
I wasn't really sure where to put this file, but I wanted to contribute something I recently got working on aur [package](https://aur.archlinux.org/packages/wxglade/) for this project:

#### wxglade-mime.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>

<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
    <mime-type type="application/x-wxg">
        <comment>wxGlade design file</comment>
        <sub-class-of type="application/xml"/>
        <!-- workaround for Nautilus/Nemo
        See: https://gitlab.gnome.org/GNOME/nautilus/-/issues/1816 -->
        <generic-icon name="application-x-wxg"/>
        <!-- end workaround -->
        <magic priority="60">
        	<match type="string" offset="0" value="&lt;?xml version=&quot;1.0&quot;?&gt;">
        		<match type="string" offset="0:256" value="&lt;!-- generated by wxGlade"/>
        	</match>
        </magic>
        <glob pattern="*.wxg"/>
    </mime-type>
</mime-info>
```

This allows for detection of `.wxg` files by most file managers and associates those files with `wxglade`.

**Comment by DietmarSchwertberger** [comment]
Where does this have to be placed?

**Comment by smac89** [comment]
On Linux, it goes in `prefix/share/mime/packages` directory.

**Comment by DietmarSchwertberger** [comment]
This directory is probably not writable for a user, right? So wxglade can't copy the file there.
So I will just place it in the root directory of the repository.

**Comment by smac89** [comment]
> This directory is probably not writable for a user, right? So wxglade can't copy the file there.
> So I will just place it in the root directory of the repository.

It can be installed locally by a user. They just have to place it in `$XDG_DATA_HOME/mime/packages`. However package installations on Linux usually do not touch a user's home directory.

I think it' fine to just include it as a file in the root directory that way, depending on the need, a package maintainer can install it globally or a user can put it in the directory I mentioned above. They will also need to place the icons appropriately in `$XDG_DATA_HOME/icons/hicolor/SxS/mimetypes/` so that the icons are appropriately associated with the mimetype.

**Comment by DietmarSchwertberger** [comment]
Thanks for the contribution. The file is in the repository now.
