### ISSUE TITLE
wx.WHITE Causes Unreadable Text on MacOS (See Issue #304)

### ISSUE THREAD

**Issue by mrunion** [wxGlade/wxGlade#487]
In the latest code, and in 1.0.1, line 1495 in new_properties.py still has the background colors being set specifically to white (wx.WHITE). This causes text to be unreadable on MacOS 11 in Dark Mode. I can set the text to Gray, as mentioned in Issue #304 (which is closed).

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. This should be fixed now in both branches.
I will probably release 1.0.2 within two weeks. Please provide feedback if the issue persists.

**Comment by mrunion** [comment]
Awesome! Confirmed that the is fixed in the version downloaded from this repo.
