### ISSUE TITLE
Font size in layout tree too small

### ISSUE THREAD

**Issue by wphilips** [wxGlade/wxGlade#488]
On fedora 33, HIDPI laptop screen, 150 dpi, 
the font size of the tree view is much too small: it is at the edge of legigibility and there seems 
to be no way to make it larger, neither in the wxGlade preferences, not in in the OS appearance-font 
preferences.

Is it possible to provide a preference to change it, or at least make the current size a bit larger?

![wxglade](https://user-images.githubusercontent.com/2874424/117553468-1de0a300-b052-11eb-8e81-5906ec1c3fb1.png)

**Comment by DietmarSchwertberger** [comment]
I will look into this.
As workaround, you can insert a `SetFont` line into tree.py -> `WidgetTree.__init__`:
```
class WidgetTree(TREE_BASE):#, Tree):
    def __init__(self, parent, application):
        style = wx.TR_DEFAULT_STYLE|wx.TR_HAS_VARIABLE_ROW_HEIGHT
        style |= wx.TR_EDIT_LABELS
        if wx.Platform == '__WXGTK__':    style |= wx.TR_NO_LINES|wx.TR_FULL_ROW_HIGHLIGHT
        elif wx.Platform == '__WXMAC__':  style &= ~wx.TR_ROW_LINES
        TREE_BASE.__init__(self, parent, -1, style=style)
        self.SetFont( self.GetFont().Scaled(1.2) )
```

**Comment by DietmarSchwertberger** [comment]
P.S.: Please try different values for the scaling factor and provide feedback about your prefered value.

**Comment by wphilips** [comment]
I tried your new code. An optimal value (for me) would a scale factor of around 1.3 - 1.5. Of course there is a balance
between readability and the number of items on screen. I think I will stick with 1.5

The new gui option works as expected (after a restart).

Thanks for the speedy fix.

**Comment by DietmarSchwertberger** [comment]
The font size will now be modified immediately.

**Comment by DietmarSchwertberger** [comment]
pre-release 1.1.0a1 is online now
