### ISSUE TITLE
time.clock() not in python 3.8.5 (main.py)

### ISSUE THREAD

**Issue by DRCars** [wxGlade/wxGlade#489]
main.py will not load a saved .wxg file. Apparently, time.clock() not in module time in python 3.8.5. The following should correct the issue:

around line 907
        try:           
            start=time.clock()
        except AttributeError:
            start = time.process_time()

around line 990
      try:           
          end=time.clock()
      except AttributeError:
          end = time.process_time()

**Comment by DietmarSchwertberger** [comment]
I think you are using an old version. This bug has been fixed in 2020.

https://github.com/wxGlade/wxGlade/issues/387
