### ISSUE TITLE
Allow to merge grid cells

### ISSUE THREAD

**Issue by KayHolgerLiesenberg** [wxGlade/wxGlade#490]
I come across the need to align ctrls over grids & sizers quite frequently ... mostly for reasons of taste, visual impression, providing easy to understand structuring

let's assume we have a grid like this:
`A1, B1, C1`
`A2, B2, C2`
`A3, B3, C3 `

by allowing to merge A3 & B3 col C will still enable to structure ctrls straigth aligned:
`A1,  B1, C1`
`A2,  B2, C2`
`Merged, C3 `

we can merge over rows and over lines like this big cell "M" here:
`A1, B1, C1`
`MMMMMM, C2`
`MMMMMM, C3 `

the merged rectangle allows to place a sizer and structure ctrls inside it.

to keep it simple in first step lets assume:
- there is no way back ... once you merge cells, you can merge them with other cells, but can't split them again
- we can merge cells like a rectangle only, so following is not allowed:
`A1, B1, C1`
`MM ,B2, C2`
`MMMMMM, C3 `

**Comment by DietmarSchwertberger** [comment]
Gridbag sizers can do that.
Don't overuse them. They are rarely needed. Especially, don't use them as main sizer of your windows. That's usually a mess.

**Comment by KayHolgerLiesenberg** [comment]
sounds promising - how do you get it to do it?
in wxglade UI v1.0.2 (Windows) I can add a grid and configure it to be a gridbag.
Now how do you teach the cells to join?

**Comment by DietmarSchwertberger** [comment]
Use the span property on the layout tab.
![grafik](https://user-images.githubusercontent.com/5512021/121743782-2cfbba80-cb02-11eb-9cf3-24cddc753346.png)
