### ISSUE TITLE
ValueError during C++ code generation

### ISSUE THREAD

**Issue by PhilippeBekaert** [wxGlade/wxGlade#494]
Having % characters (and probably other special characters??) in radio box label texts crashes wxglade C++ code generation.
Error details and minimal wxg example below.

Best, Ph.

----------------------------------------------------------------------------------------
    
    ERROR   : An internal error occurred while Generate Code
    An unexpected error occurred!
    
    Exception type:      <class 'ValueError'>
    Exception details:   unsupported format character '"' (0x22) at index 13
    
    Application stack traceback:
      File "/home/philippe/Downloads/wxGlade-1.0.0/application.py", line 500, in generate_code
        writer.generate_code(self, widget)
      File "/home/philippe/Downloads/wxGlade-1.0.0/codegen/__init__.py", line 456, in generate_code
        self._generate_code(None, None, None, c)
      File "/home/philippe/Downloads/wxGlade-1.0.0/codegen/__init__.py", line 446, in _generate_code
        self._generate_code(klass or parent_klass, obj, builder, child)
      File "/home/philippe/Downloads/wxGlade-1.0.0/codegen/__init__.py", line 446, in _generate_code
        self._generate_code(klass or parent_klass, obj, builder, child)
      File "/home/philippe/Downloads/wxGlade-1.0.0/codegen/__init__.py", line 440, in _generate_code
        builder = self.add_object(parent_klass, parent, parent_builder, obj)
      File "/home/philippe/Downloads/wxGlade-1.0.0/codegen/cpp_codegen.py", line 910, in add_object
        init, ids, final = builder.get_code(obj)
      File "/home/philippe/Downloads/wxGlade-1.0.0/wcodegen/__init__.py", line 827, in get_code
        init, post = BaseWidgetWriter.get_code(self, obj)
      File "/home/philippe/Downloads/wxGlade-1.0.0/wcodegen/__init__.py", line 540, in get_code
        lines.append(line % self.tmpl_dict)
    
    Date and time:       2021-08-14T14:07:34.778127
    Python version:      3.8.10
    wxPython version:    4.0.7
    wxWidgets platform:  __WXGTK__
    wxGlade version:     1.0.0
    
----------------------------------------------------------------------------------------------
    <?xml version="1.0"?>
    

    <application encoding="UTF-8" for_version="3.0" header_extension=".h" indent_amount="2" indent_symbol="space" is_template="0" language="C++" mark_blocks="1" option="0" overwrite="1" path="TCOPanel.cpp" source_extension=".cpp" use_gettext="0" use_new_namespace="1">
        <object class="TCOPanel" name="TCOPanel" base="EditTopLevelPanel">
            <style>wxTAB_TRAVERSAL</style>
            <object class="wxBoxSizer" name="sizer_7" base="EditBoxSizer">
                <orient>wxVERTICAL</orient>
                <object class="sizeritem">
                    <option>0</option>
                    <border>4</border>
                   <flag>wxALL|wxEXPAND</flag>
                    <object class="wxRadioBox" name="pullBox" base="EditRadioBox">
                       <events>
                            <handler event="EVT_RADIOBOX">pullCB</handler>
                        </events>
                        <id>pullID=?</id>
                        <label>Pull Up/Down</label>
                        <dimension>1</dimension>
                        <selection>0</selection>
                         <choices>
                             <choice>None</choice>
                            <choice>+0.1 %</choice>
                            <choice>- 0.1</choice>
                            <choice>+4</choice>
                            <choice>- 4</choice>
                        </choices>
                        <style>wxRA_SPECIFY_COLS</style>
                    </object>
                </object>
            </object>
        </object>
    </application>

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. This is fixed now in REV_1.0 and master branch.

**Comment by DietmarSchwertberger** [comment]
Released v1.0.3
