### ISSUE TITLE
Wrong C++ code generted for sizer.Fit()

### ISSUE THREAD

**Issue by bebidek** [wxGlade/wxGlade#496]
Generating C++ code for Frame with Panel and Sizer but without fixed size (size checkbox unchecked) results in line:
`sizer_1->->Fit();`

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. A fix is in the repository now in both branches.
Sorry for the C++ bugs, but myself I'm using only wxPython.

**Comment by DietmarSchwertberger** [comment]
Released v1.0.3
