### ISSUE TITLE
Error 'configparser.MissingSectionHeaderError'

### ISSUE THREAD

**Issue by jdauthre** [wxGlade/wxGlade#500]
wxglade stopped working with this error:
Exception type:      <class 'configparser.MissingSectionHeaderError'>
Exception details:   File contains no section headers.
file: 'C:\\Users\\jdaut\\AppData\\Roaming\\wxglade\\wxglade.ini', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'  -Much more of these - deleted for brevity

Application stack traceback:
  File "D:\wxGlade\main.py", line 1449, in OnInit
    common.init_preferences()
  File "D:\wxGlade\common.py", line 730, in init_preferences
    config.preferences.read(config.rc_file)
  File "C:\Users\jdaut\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\jdaut\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 1085, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)

Date and time:       2021-11-26T14:13:34.310861
Python version:      3.9.7
wxPython version:    4.1.1
wxWidgets platform:  __WXMSW__
wxGlade version:     1.0.3

I reinstalled wxglade,python and wxpython  but the problem still occurs.

Any help appreciated

**Comment by DietmarSchwertberger** [comment]
Please delete the file `C:\Users\jdaut\AppData\Roaming\wxglade\wxglade.ini`

**Comment by jdauthre** [comment]
Thankyou, that fixed it

**Comment by DietmarSchwertberger** [comment]
Do you know how the empty config file was created? Did you run wxGlade before or did you run it and just stop it? I'm wondering whether I need to implement some containment. I never experienced such behaviour, even though Windows is my main platform.

**Comment by jdauthre** [comment]
I was running wxGlade  and  wing personal, editing  an application in the latter, but when I went back to wxGlade the problem appeared and remained after trying to reopen it. Reinstalling it did not help , as I assume the data in the appdata folder was not deleted. I have been using wxGlade for a good year or so without this happening before. If it happens again I will try and keep a more careful note of what I did

**Comment by DietmarSchwertberger** [comment]
I'm closing this now. If it occurs again, please re-open and I will at least implement some error handling.

**Comment by tofuSCHNITZEL** [comment]
I'm having the same issue at the moment... but I don't have a folder %appdata%\wxglade\ so I can't delete anything (that would have been my first idea)
I got in this situation because my PC BSOD'd while I was working with wxglade and after rebooting this is the error I get when starting wxglade. I will try to run chkdsk next because maybe the the file/folder will "appear"

**Comment by DietmarSchwertberger** [comment]
In the master branch there is now a version that will report that the file is not loaded.
So, wxGlade does still start. The message will remain there until preferences are saved again.

**Comment by tofuSCHNITZEL** [comment]
great! thanks for the fix!

**Comment by DietmarSchwertberger** [comment]
pre-release 1.1.0a1 is online now
