### ISSUE TITLE
Wrong GridBagSizer codegen for Perl

### ISSUE THREAD

**Issue by sciurius** [wxGlade/wxGlade#501]
wxGlade 1.1.0pre (from git)

When code is generated for the members of a GridBagSizer, GBPosition and GBSpan are generated as lists (e.g. `(1, 0)`) instead of arrays (e.g. `[1, 0]`) or explicit objects, `Wx::GBPosition->new(`1, 0)` resp. `Wx::GBSpan->new(1,` 2)`.

The latter can be obtained by modifying line 207 of `perl_codegen.py` to:
````
    $tmpl_gridbagsizeritem = '%s->Add(%s, Wx::GBPosition->new%s, Wx::GBSpan->new%s, %s, %s);\n'
````

**Comment by DietmarSchwertberger** [comment]
Thanks a lot. It's in the repository now in the master branch.

**Comment by sciurius** [comment]
Confirmed. Thanks.
