### ISSUE TITLE
wxGlade fails mysteriously on codegen

### ISSUE THREAD

**Issue by sciurius** [wxGlade/wxGlade#502]
% wxglade -g perl PreferencesDialog.wxg 
... loads and works and saves fine ...
% wxglade -g perl PreferencesDialog.wxg 
INFO    : Starting wxGlade version "1.1.0pre" on Python 3.9.7
INFO    : Read wxGlade project from file "/home/jv/src/ChordPro/lib/App/Music/ChordPro/Wx/PreferencesDialog.wxg"
ERROR   : loading file "b'PreferencesDialog.wxg'": 'NoneType' object has no attribute 'refresh'

wxGlade git version on Fedora 33. 
v1.0.2 behaves the same.

**Comment by DietmarSchwertberger** [comment]
For me it's working (on Windows).
The first run will create a .pm file. The second run will rename it to .pm.bak and then create a new .pm file.
Does it work for you if you remove the .pm file before running a second time?

**Comment by sciurius** [comment]
It works for most wxg files. I have attached the file that crashes, I hope you can reproduce it.
[PreferencesDialog.wxg.txt](https://github.com/wxGlade/wxGlade/files/7680977/PreferencesDialog.wxg.txt)

**Comment by DietmarSchwertberger** [comment]
I think I tried this file from github. Does it work if you delete inbetween?

**Comment by sciurius** [comment]
I made a copy to an empty directory. So there is only the .wxg, and no .pm yet.
````
% ls -l
-rw-r--r-- 1 jv jv 30895 Dec  8 23:58 PreferencesDialog.wxg
% wxglade -g perl PreferencesDialog.wxg 
INFO    : Starting wxGlade version "1.1.0pre" on Python 3.9.7
INFO    : Read wxGlade project from file "/home/jv/tmp/xx/PreferencesDialog.wxg"
ERROR   : loading file "b'PreferencesDialog.wxg'": 'NoneType' object has no attribute 'refresh'
Exit 1
````

**Comment by sciurius** [comment]
0.9.6fix2 (REV_0.9) works okay, 
1.0.0a1 fails, but gives a stack trace:
```` % wxglade -g perl PreferencesDialog.wxg
INFO    : Starting wxGlade version "1.0.0a1" on Python 3.9.7
INFO    : Read wxGlade project from file "/home/jv/tmp/xx/PreferencesDialog.wxg"
ERROR   : An unhandled exception occurred
An unexpected error occurred!

Exception type:      <class 'AttributeError'>
Exception details:   'NoneType' object has no attribute 'remove'

Application stack traceback:
  File "/home/jv/wrk/wxGlade/wxGlade/wxglade.py", line 389, in <module>
    run_main()
  File "/home/jv/wrk/wxGlade/wxGlade/wxglade.py", line 386, in run_main
    command_line_code_generation( filename=options.filename, language=options.language, out_path=options.output )
  File "/home/jv/wrk/wxGlade/wxGlade/wxglade.py", line 271, in command_line_code_generation
    b = _guiless_open_app(filename)
  File "/home/jv/wrk/wxGlade/wxGlade/wxglade.py", line 226, in _guiless_open_app
    common.root.clear()
  File "/home/jv/wrk/wxGlade/wxGlade/application.py", line 154, in clear
    self.children[-1].recursive_remove(0)
  File "/home/jv/wrk/wxGlade/wxGlade/edit_base.py", line 389, in recursive_remove
    child.recursive_remove(level+1)
  File "/home/jv/wrk/wxGlade/wxGlade/edit_base.py", line 389, in recursive_remove
    child.recursive_remove(level+1)
  File "/home/jv/wrk/wxGlade/wxGlade/edit_base.py", line 389, in recursive_remove
    child.recursive_remove(level+1)
  [Previous line repeated 1 more time]
  File "/home/jv/wrk/wxGlade/wxGlade/edit_base.py", line 400, in recursive_remove
    common.app_tree.remove(self)  # remove mutual reference from widget to/from Tree item

Date and time:       2021-12-09T00:28:14.575168
Python version:      3.9.7
wxPython version:    not_set
wxWidgets platform:  not_set
wxGlade version:     1.0.0a1
````

**Comment by DietmarSchwertberger** [comment]
With your attached file, I can see the problem. I will look into it.

**Comment by DietmarSchwertberger** [comment]
It's fixed now in the master branch. It was related to a gridbag sizer slot that was overlapped by another item spanning two columns. I missed a code that should not be executed when running from command line.
May I add your file to wxGlade test cases?
I will fix also in the REV_1.0 branch soon.

**Comment by sciurius** [comment]
Confirmed.

Yes is it ok to add the file to your test cases.

Thanks for the ongoing support!
