### ISSUE TITLE
Unexpected error on my first attempt to use

### ISSUE THREAD

**Issue by jerdantas** [wxGlade/wxGlade#504]
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'TypeError'>
Exception details:   DC.DrawText(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'

Application stack traceback:
  File "/home/dantas/anaconda3/envs/pygubu/lib/python3.10/site-packages/wx/lib/buttons.py", line 496, in OnPaint
    self.DrawLabel(dc, width, height)
  File "/home/dantas/anaconda3/envs/pygubu/lib/python3.10/site-packages/wx/lib/buttons.py", line 456, in DrawLabel
    dc.DrawText(label, (width-tw)/2+dx, (height-th)/2+dy)

Date and time:       2021-12-30T15:50:55.227468
Python version:      3.10.0
wxPython version:    4.1.1
wxWidgets platform:  __WXGTK__
wxGlade version:     1.0.3

**Comment by DietmarSchwertberger** [comment]
I think 4.1.1 is not officially supported yet with Python 3.10 and so I have not tried yet as there are no Windows binaries.
Python 3.10 does not support floats any more for integer arguments. There were discussions on github or discuss.wxpython.org.

I will look into this. I will with a snapshot build of 4.1.2.

**Comment by DietmarSchwertberger** [comment]
Could you please try the master branch from the wxGlade repository?
I have just uploaded a modification.

**Comment by DietmarSchwertberger** [comment]
Alternatively, you may add `int` and `round` to `new_properties.py` `TextProperty.create_editor`:

`hsizer.SetItemMinSize(self.text, 100, int(round(h*1.5)))`
and
`hsizer.SetItemMinSize(self.text, -1, int(round(h*1.5)))`


`

**Comment by DietmarSchwertberger** [comment]
Release 1.0.4 is online. Please test.
