### ISSUE TITLE
wxGlade does not detect a save is needed after deleting an argument from a custom widget

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#505]
1. Rename attached file as custom_widget.wxg
2. Open custom_widget.wxg in wxGlade
3. Select window_1
4. Select Widget tab
5. Select one of the arguments
6. Click "Remove" button
7. The argument is removed, but no asterisk is displayed on wxGlade's main window title bar.
8. Select File -> Exit
9. wxGlade closes without showing a confirmation dialog to save changes.

I am using wxGlade 1.0.4 on Python 3.8.10 + wxPython 4.1.1 gtk3 (phoenix) wxWidgets 3.1.5 + Linux Mint 20.2.

[custom_widget.wxg.txt](https://github.com/wxGlade/wxGlade/files/7802071/custom_widget.wxg.txt)

**Comment by DietmarSchwertberger** [comment]
Thanks a lot for reporting.
Fixing this will take a bit longer. It seems I forgot this case also when implementing the Undo/Re-Do functionality. (Which is not part of 1.0.4 but in the master branch of the repository.)

**Comment by DietmarSchwertberger** [comment]
A fix is now in the master branch.

**Comment by DietmarSchwertberger** [comment]
pre-release 1.1.0a1 is online now
