### ISSUE TITLE
Problem with Python 3.10

### ISSUE THREAD

**Issue by rafalfr** [wxGlade/wxGlade#508]
The error occurred when I tried to create a new dialog window. It looks like in Python 3.10 variables passed to the self.DrawLabel() and dc.DrawText() must be integers not floats.

ERROR   : None
An unexpected error occurred!

Exception type:      <class 'TypeError'>
Exception details:   DC.DrawText(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'

Application stack traceback:
  File "/usr/lib/python3.10/site-packages/wx/lib/buttons.py", line 492, in OnPaint
    self.DrawLabel(dc, width, height)
  File "/usr/lib/python3.10/site-packages/wx/lib/buttons.py", line 452, in DrawLabel
    dc.DrawText(label, (width-tw)/2+dx, (height-th)/2+dy)

Date and time:       2022-01-19T22:13:52.849856
Python version:      3.10.1
wxPython version:    4.0.7.post2
wxWidgets platform:  __WXGTK__
wxGlade version:     1.1.0pre

**Comment by DietmarSchwertberger** [comment]
Have you built that version yourself? wxPython 4.0.7 is not compatible with Python 3.10.
Please try a recent snapshot or git version.

The code line in wxPython 4.1.2 lib.buttons is
`dc.DrawText(label, (width-tw)//2+dx, (height-th)//2+dy)`
not 
`dc.DrawText(label, (width-tw)/2+dx, (height-th)/2+dy)`
