### ISSUE TITLE
Wrong default size for wx.grid.Grid in generated code.

### ISSUE THREAD

**Issue by TonyReinberger** [wxGlade/wxGlade#509]
I'm generating Python3 code and using the latest REV_1.0 branch.

If I leave the grid size of the grid to the default, the generated code is:

`self.my_grid= wx.grid.Grid(self.my_frame, wx.ID_ANY, size=(1, 1))`

It looks ok in the design window but when you look at the preview, it is virtually invisible. I've set the size in wxGlade to -1, -1 so that it sets the size in the generated code and works for the preview but this is not saved in the wxg file because it is recognized as the default. As a result, the preview and generated code do not work if you open the project again in wxGlade. My workaround for now is to add "extra code to be inserted after" in the code properties:

`self.my_grid.SetMinSize((-1, -1))`

This stops the problem from affecting the generated code but it does not fix the preview. I think the problem is that the generated line should not include the `size=(1, 1)` part when the default is chosen.

Cheers,

Tony

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. It seems the root cause is a workaround that was introduced in 2005.

In grid/codegen.py you can replace line 34:
`init.append('self.%s = %s(%s, %s, size=(1, 1))\n' % (obj.name, klass, parent, id))`
with
`init.append('self.%s = %s(%s, %s)\n' % (obj.name, klass, parent, id))`

I need to check a few things before I implement the change.

**Comment by TonyReinberger** [comment]
Thanks. I spent a lot of time wondering what I was doing wrong. The wxPython documentation is a big help. That and wxGlade is probably the reason I'm not using Tkinter. I've changed the code on my branch and removed my extra code workaround. It seems to work as expected.

I'm glad I could help improve it and thanks for maintaining the code. I assume you will close this issue when it's in the released code.

**Comment by DietmarSchwertberger** [comment]
Yes, I will keep it "pending" until 1.1 is release. I hope that I will find time for this in the next weeks. Anyway, it should be save to use the code from the master branch. 1.1 will not be much different. The main change to 1.0.x is the undo/re-do.

**Comment by DietmarSchwertberger** [comment]
pre-release 1.1.0a1 is online now
