### ISSUE TITLE
Art Selector dialog doesn't modify existing width and height

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#511]
1. Rename the attached files as art_selector_sizes.wxg
2. Open art_selector_sizes.wxg in wxGlade.
3. Select frame_toolbar.
4. Select Widget tab.
5. Click "Edit tools..."
6. Click the "A" button for the Primary Bitmap.
7. In the ART selector dialog, leave image name set to "NEW", change the Width and/or Height values and click "OK".
8. The size of the Primary Bitmap in the Toolbar Editor dialog does not change.

The size of the bitmap is only changed if you change the image name as well as the size.

[art_selector_sizes.wxg.txt](https://github.com/wxGlade/wxGlade/files/8363789/art_selector_sizes.wxg.txt)

I am using wxGlade 1.0.4 on Python 3.8.10 + wxPython 4.1.1 gtk3 (phoenix) wxWidgets 3.1.5 + Linux Mint 20.3.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. I will fix it, but don't hold your breath.
As workaround, you can just edit the text box.

**Comment by DietmarSchwertberger** [comment]
This is improved now.
Actually, it worked, but in the steps you described you did not select an image and therefore the dialogs return value was -1 and the value for the bitmap was not updated.
When image and size are available already, the art selection dialog will now be set to these values when it is shown.

**Comment by DietmarSchwertberger** [comment]
pre-release 1.1.0a1 is online now
