### ISSUE TITLE
Missing Art provider names in Art selector dialog

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#512]
When checking the list of Art provider names in wxGlade v.1.0.4's Art selector dialog, I noticed that names for the following IDs are missing:
wx.ART_REMOVABLE
wx.ART_FULL_SCREEN
wx.ART_EDIT

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. These were not in the wxPython docs...
I have added them now.

**Comment by DietmarSchwertberger** [comment]
pre-release 1.1.0a1 is online now
