### ISSUE TITLE
Internal Error when opening .wxg file

### ISSUE THREAD

**Issue by nickstone8** [wxGlade/wxGlade#513]
Start wxGlade and create a simple frame based dialog. Save to .wxg file. Quit wxGlade. Start wxGlade and attempt to open the .wxg file. Get error message: 

ERROR   : None
An unexpected error occurred!

Exception type:      <class 'AttributeError'>
Exception details:   module 'time' has no attribute 'clock'

Application stack traceback:
  File "/usr/share/wxglade/misc.py", line 311, in handler
    func( *args, **kwargs )
  File "/usr/share/wxglade/main.py", line 895, in open_app
    self._open_app(infile)
  File "/usr/share/wxglade/main.py", line 907, in _open_app
    start = time.clock()

Date and time:       2022-04-13T17:56:19.951829
Python version:      3.8.10
wxPython version:    4.0.7
wxWidgets platform:  __WXGTK__
wxGlade version:     0.9.4

My system is Linux, Mint XFCE:
5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by DietmarSchwertberger** [comment]
Please use a more recent version.

**Comment by DietmarSchwertberger** [comment]
Duplicate of https://github.com/wxGlade/wxGlade/issues/387
