### ISSUE TITLE
Idle and Timer events

### ISSUE THREAD

**Issue by brendan-simon-indt** [wxGlade/wxGlade#517]
Is there a way to specify `Idle` and `Timer` events?
So that I can override the handlers in my derived frame (or app or whatever)?

**Comment by DietmarSchwertberger** [comment]
You can add any event name to the 'Events' tab.
![grafik](https://user-images.githubusercontent.com/5512021/171025897-a43a0f0d-85f2-4852-9bc1-dde57eaf12da.png)

I will add an easier way to add events, but that will not happen soon.

Anyway, for usage questions please use the mailing list. This here is an issue tracker, not a support forum.

**Comment by brendan-simon-indt** [comment]
ok.  thanks Dietmar :)

**Comment by brendan-simon-indt** [comment]
Generated event code (for `EVT_IDLE` and `EVT_TIMER`) does not work with wxPython `4.1.2` (`4.1.2a1.dev5412+727f3aff`)

Example generated code.

```python
class Main_Frame_WXG(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Main_Frame_WXG.__init__
        ...
        self.Bind(wx.EVT_IDLE, self.on_idle, self)
        self.Bind(wx.EVT_TIMER, self.on_timer, self)

        # end wxGlade
```

It works if I manually change the generated code to replace the `Bind()` calls as follows.

```python
        self.Bind(wx.EVT_IDLE, self.on_idle)
        self.Bind(wx.EVT_TIMER, self.on_timer)
```
