### ISSUE TITLE
Startup script parses python `3.10` as `3.1`

### ISSUE THREAD

**Issue by asiplas** [wxGlade/wxGlade#518]
The `[:3]` to parse python version fails to account for versions like 3.10 and parses them as 3.1; search path is set to `/usr/lib/python3.1/site-packages` instead of `/usr/lib/python3.10/site-packages` leading to `ERROR: wxglade.py not found!`

https://github.com/wxGlade/wxGlade/blob/70d8d037998730dc350ae4345df7fd039ed0d63c/wxglade#L41

**Comment by smac89** [comment]
Was just about to report this.

**Comment by DietmarSchwertberger** [comment]
Sorry for the long delay. Somehow I missed this one....
A fix is in the repository for both master and REV_1.0 branches.

**Comment by DietmarSchwertberger** [comment]
revision 1.0.5 about to be released
