### ISSUE TITLE
Errors while editing a StatusBar

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#520]
Several times I have encountered errors when trying to setup a StatusBar in wxGlade on Linux Mint. Until now I haven't been able to identify a repeatable sequence that will trigger these errors.

I am currently using wxGlade 1.0.4 with Python 3.10.4 + wxPython 4.2.0 gtk3 (phoenix) wxWidgets 3.2.0 + Linux Mint 21.

The following sequence is repeatable:

* Start wxGlade.
* Add a Frame.
* Select the Widget tab for the Frame and check "Has StatusBar".
* Select the frame_statusbar in the tree and select its Widget tab.
* Click in Size TextCtrl, delete the -1 and enter 100.
* Press the Enter key, or just move the mouse pointer to a different application's window (so wxGlade's window loses the focus).

An Error Dialog will appear containing the following details:

```
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'TypeError'>
Exception details:   Grid.SetCellValue(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'int'
  overload 2: argument 1 has unexpected type 'int'

Application stack traceback:
  File "/usr/share/wxglade-1.0.4/new_properties.py", line 3041, in on_kill_focus_editor
    self._on_editor_edited(event)
  File "/usr/share/wxglade-1.0.4/new_properties.py", line 3034, in _on_editor_edited
    self.grid.SetCellValue(self.cur_row, col, value)

Date and time:       2022-09-05T11:26:25.300193
Python version:      3.10.4
wxPython version:    4.2.0
wxWidgets platform:  __WXGTK__
wxGlade version:     1.0.4
```

After closing that error, further Error Dialogs will keep appearing as you try to recover the situation.

This includes after selecting File -> New which triggers a different error:

```
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'AttributeError'>
Exception details:   'NoneType' object has no attribute 'NumberRows'

Application stack traceback:
  File "/usr/share/wxglade-1.0.4/new_properties.py", line 2997, in on_focus_editor
    if self.cur_row is not None and self.cur_row>=0 and self.cur_row<self.grid.NumberRows:

Date and time:       2022-09-05T11:30:20.906642
Python version:      3.10.4
wxPython version:    4.2.0
wxWidgets platform:  __WXGTK__
wxGlade version:     1.0.4
```

If instead of editing the Size TextCtrl, I edit the values directly in the Grid below, the errors do not occur.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. This is fixed in the repository now.

**Comment by DietmarSchwertberger** [comment]
pre-release 1.1.0a1 is online now
