### ISSUE TITLE
Problem using Esc to cancel an insert operation in a Frame

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#522]
Using: Python 3.10.4 + wxPython 4.2.0 gtk3 (phoenix) wxWidgets 3.2.0 + Linux Mint 21 + wxGlade 1.0.4

- Open wxGlade.
- Add a Frame.
- Select Button in the palette.
- Move Mouse Pointer to the Design window.
- The mouse pointer changes to a plus sign '+' and the "Add a widget or another sizer here." tooltip appears.
- With the mouse pointer still in the Design window, press the "Esc" key.
- The tooltip disappears, but the mouse pointer doesn't revert to the arrow head.
- Click the left mouse button.
- The button is added to the sizer (the operation wasn't cancelled).

If I move the mouse pointer out of the Design window before I press the Esc key, the insert operation _is_ cancelled. 

If I click in the Design window before I select the Button in the palette, then pressing the Esc key when the mouse pointer is in the Design window does cancel the insert operation.

If I use a Dialog instead of a Frame, the Esc key _will_ cancel the insert operation when the mouse pointer is in the Design window.

**Comment by DietmarSchwertberger** [comment]
Seems to work on Windows. Need to check on one of my Linux VMs.

**Comment by DietmarSchwertberger** [comment]
Can't reproduce it on my installations yet. I will update to wxPython 4.2 in the next days. If I still can't reproduce it, I will post instructions how to debug this on your platform yourself.
The relevant function is `_cancel()` in `misc.py`.

**Comment by reticulatus** [comment]
I have installed the Screenkey app on my PC to display any keys that are pressed and then made a short video which shows that pressing the Esc key in the Design window doesn't cancel the insert operation. 

https://user-images.githubusercontent.com/6072789/191719527-7c63ea29-daef-49d8-9e39-8009d3336bf5.mp4

**Comment by DietmarSchwertberger** [comment]
Don't worry, I do believe that you that the issue is real.
Regarding "Select windows...": yes, please try without, even though I don't think so.

**Comment by reticulatus** [comment]
Unchecking the  "Select windows when the mouse moves over them" option did stop the problem occurring. 

I have used that option for years as it allows me to type in a partially covered window without clicking on it, which would raise it in the stacking order and possibly cover what I was trying to read.

**Comment by DietmarSchwertberger** [comment]
Ok, after some searching I could install Gnome tweak tools on my Ubuntu VM and enable "Focus On Hover". With this I see the same behaviour as you do. I will look into this. It could take some days, though.

**Comment by DietmarSchwertberger** [comment]
It seems that the EVT_CHAR_HOOK behaviour is different with this kind of focus vs. a focus with a mouse click. For this week I have to stop. Will continue to look, though.

**Comment by DietmarSchwertberger** [comment]
wxGlade binds EVT_CHAR_HOOK handlers for palette, tree, properties and the design window.
With "Focus on Hover" the window beneath the mouse cursor does not necessarily receive the character and the previous window does not either.
E.g. in your case, usually the focus is on the palette which will then receive the ESCAPE press and stop inserting.
When clicking the design window, the design window will receive the focus and the key presses.

With "Focus on Hover", neither the design window nor any other window will receive the key press if the mouse is over the design window.

I don't see how to fix this and I don't see the advantage this mode. The behaviour could be a wxPython/wxWidgets bug, but I will not investigate this.

**Comment by DietmarSchwertberger** [comment]
I have uploaded a branch `CHAR_DEBUG` for printing messages around the character events.
You may try to debug the issue yourself if you want.
