### ISSUE TITLE
Misleading "Add a sizer here" tooltip & confusing behaviour when there is no position for one

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#523]
Using: Python 3.10.4 + wxPython 4.2.0 gtk3 (phoenix) wxWidgets 3.2.0 + Linux Mint 21

With wxGlade 1.0.4 configured to have the palette, properties and tree combined in a single window.

- Open wxGlade
- Add a Frame
- Select Button in the palette
- Left-click in the Design window
- The Button is added to the Frame
- Select a BoxSizer in the palette
- Move the mouse pointer over the Panel in the Design window
- The mouse pointer changes to a plus '+' and an "Add a sizer here" tooltip appears.
- Left-click on the Panel in the Design window
- The Panel gets selected in the Design window and in the Tree control. No new sizer is added. The keyboard focus is set on the Common -> Name TextCtrl in Panel's properties window. 
- Move the mouse pointer over all the items in the Tree control.
- The mouse pointer changes to an 'X' over each of the items.
- Pressing the Esc key doesn't cancel the insert operation or revert the mouse pointer for the tree items (because the keyboard focus in set to the Name TextCtrl?).
- Move the mouse pointer to the Design window.
- The mouse pointer changes to a plus '+' and the "Add a sizer here" tooltip appears again.
- Press the Esc key.
- The insert operation is now cancelled. The mouse pointer stays as '+' in the Design window.
- Move the mouse pointer over all the items in the Tree control.
- The mouse pointer now shows an arrow head over all the items.
- Move the mouse pointer back to the Design window.
- The mouse pointer now shows as an arrow head in the Design window.

The display of the '+' mouse pointer and the "Add a sizer here" tooltip in the Design window is misleading as there is nowhere for a sizer to go.

Allowing the left-click on the Panel in the Design window is confusing because it looks like something has happened, but the insert operation is actually still pending.

Not responding to the Esc key in the Tree control is confusing because it makes it seem that that the insert operation can't be cancelled.

**Comment by DietmarSchwertberger** [comment]
The tooltips should now be correct and also updated when a child is added or removed.
I need to check for the Escape behaviour.

**Comment by DietmarSchwertberger** [comment]
On the tree it's easy to identify the element beneath the mouse pointer. In the design window it's not so easy. I don't know whether it's worth the effort. The tooltip help has been improved.

**Comment by DietmarSchwertberger** [comment]
pre-release 1.1.0a1 is online now
