### ISSUE TITLE
Show Preview with STC as Custom Widget raises TypeError

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#524]
- Run wxGlade
- Add a Frame
- Add a Custom widget with instance class set to stc.StyledTextCtrl
- Select the widget's Code tab
- In the Extra (import) section, enter: import wx.stc as stc
- Save the design as a .wxg file
- Select the Frame in the tree control
- Click "Show Preview"

An error similar to this is displayed:

```
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'TypeError'>
Exception details:   DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'

Application stack traceback:
  File "/home/richardt/Sources/applications/GUI Builders/wxGlade/issues/_wxglade_509896714.py", line 39, in self_window_1_on_paint

Date and time:       2022-09-26T09:07:54.437643
Python version:      3.10.6
wxPython version:    4.2.0
wxWidgets platform:  __WXGTK__
wxGlade version:     1.0.4

```

If you generate and run the code for the design, it runs without errors.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. Things should work now again also with Python 3.10.

**Comment by DietmarSchwertberger** [comment]
revision 1.0.5 about to be released
