### ISSUE TITLE
Installation failure (OpenSuse 15.4)

### ISSUE THREAD

**Issue by cedricowen91** [wxGlade/wxGlade#526]
After unpacking the zip file, I ran python3 wxglade.py as instructed.
This caused a segmentation fault:

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007ffff2d4a6cb in gtk_widget_size_allocate_with_baseline () from /usr/lib64/libgtk-3.so.0
(gdb) 

Here is the full log:
INFO    : Starting wxGlade version "1.0.4" on Python 3.6.15
INFO    : Using wxPython 4.1.1
INFO    : Loading "wconfig" modules from /home/cedric/Downloads/wxGlade-1.0.4/widgets/widgets.txt:
INFO    : Load code generators:
INFO    :   C++ generator loaded
INFO    :   lisp generator loaded
INFO    :   perl generator loaded
INFO    :   python generator loaded
INFO    :   XRC generator loaded
INFO    : Loading widgets from /home/cedric/Downloads/wxGlade-1.0.4/widgets/widgets.txt:
INFO    :       frame
INFO    :       dialog
INFO    :       panel
INFO    :       notebook
INFO    :       splitter_window
INFO    :       button
INFO    :       toggle_button
INFO    :       bitmap_button
INFO    :       spin_button
INFO    :       text_ctrl
INFO    :       choice
INFO    :       combo_box
INFO    :       list_box
INFO    :       check_list_box
INFO    :       checkbox
INFO    :       radio_button
INFO    :       radio_box
INFO    :       spin_ctrl
INFO    :       spin_ctrl_double
INFO    :       slider
INFO    :       gauge
23:15:20: Debug: Adding duplicate image handler for 'Windows bitmap file'
23:15:20: Debug: Adding duplicate animation handler for '1' type
23:15:20: Debug: Adding duplicate animation handler for '2' type
INFO    :       calendar_ctrl
INFO    :       generic_calendar_ctrl
INFO    :       datepicker_ctrl
INFO    :       list_ctrl
INFO    :       tree_ctrl
INFO    :       grid
INFO    :       static_text
INFO    :       hyperlink_ctrl
INFO    :       static_line
INFO    :       static_bitmap
INFO    :       spacer
INFO    :       property_grid_manager
INFO    :       search_ctrl
INFO    :       custom_widget
INFO    :       menubar
INFO    :       toolbar
INFO    :       statusbar
INFO    : Load sizer generators:
INFO    :   for C++
INFO    :   for lisp
INFO    :   for perl
INFO    :   for python
INFO    :   for XRC
Segmentation fault (core dumped)

**Comment by DietmarSchwertberger** [comment]
Could you please try the current version from the repository?
You can download it from https://github.com/wxGlade/wxGlade/archive/refs/heads/master.zip
Probably the issue is fixed. If you confirm that this is working, I will prepare a new release.

**Comment by DietmarSchwertberger** [comment]
also in the REV_1.0 branch

**Comment by DietmarSchwertberger** [comment]
revision 1.0.5 about to be released
