### ISSUE TITLE
Implement resources module

### ISSUE THREAD

**Issue by Jalkhov** [wxGlade/wxGlade#527]
## Introduction

Hello everyone, I've been working on a small project, it's about a resource system for **WxGlade**, before I go I want to clarify that this idea is totally inspired by the **Qt Designer** software system. That said, rather than explaining the operation of the latter, I will start with the objective of my project (which are similar), and then everyone can try Qt Designer on their own.

## Main objective

That the resources of our projects do not depend on **absolute or relative paths**. This can sometimes result in problems with compilers like **PyInstaller** or **Nuitka**, how? Converting the images with the **py2img** library of **WxPython**, this in turn has the advantage that our compiled programs will not have our raw images in the program directory.

## What do I want to do?

Now, to present a little the operation, **for this example I will use as target language, Python**. From WxGlade we go to our option **Resources**, it will open a window that will allow us to create resource files, which I wanted to baptize with the extension `.wrc`.

A resource file (for now) will be able to contain images, icons... You can create as many resource files as you want (for those who like to have their stuff categorized). From this same interface you can select the images and assign an alias to each one.

Consider the following (simple) project tree:

```
TEST/
└── test.wxg
```

All the files (their paths, preferably next to the `.wxg` file) of resources will be added to our .wxg file inside a `<resources>` tag, our file would look something like this:

```xml
...
                    <object class="wxStaticBitmap" name="bitmap_1" base="EditStaticBitmap">
                    </object>
...
    <resources>
        <include location="brand.wrc" />
    </resources>
</application>
```

There is an empty Bitmap that will serve as an example for what we want to achieve.

On the other hand, our resource file, which we will call `brand.wrc` will have the following structure:

```xml
<WRC>
    <wresource>
        <file alias="statue">statue.png</file>
    </wresource>
</WRC>
```

Our directory would look something like this:

```
TEST/
├── test.wxg
└── icons.wrc
```

Once this is done... What's next?

In WxGlade every time we have to choose a Bitmap, we are shown a button and a dialog to select it...This new functionality would add an extra button probably called: **Select from Resource**, where you select the resource file and the desired image, yes, maybe everything so far looks the same, but the magic comes later.

Applying the above mentioned, the structure of our Bitmap in the `.wxg` file would look something like this:

```xml
...
                    <object class="wxStaticBitmap" name="bitmap_1" base="EditStaticBitmap">
                        <bitmap from-resource>brand.statue</bitmap>
                    </object>
...
```

Once this is done, we proceed to press the magic **Generate code** button.

Our typical Python file will be generated along with a new file called `brand.py`, which will have the following content:

```python
from wx.lib.embeddedimage import PyEmbeddedImage

statue = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACkElEQVQ4jaVTS0hUYRT+/v+/'
	...
    b'DuZAwAosrwyuVvVcHnr0xzP9DVqyA+786Bxu59FrE6H+n5+WVsiiXYZ3B/wCcTkx4vCZjaQA'
    b'AAAASUVORK5CYII=')
```

Our output file would look something like this (although we will also have to take into account if the user has different frames and uses the option to separate classes in different files):

```python
import wx
import brand

class TestFrame(wx.Frame):
    def __init__(self, *args, **kwds):
...
        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, brand.statue.GetBitmap(), wx.BITMAP_TYPE_ANY))
        sizer_1.Add(bitmap_1, 1, 0, 0)
...
```

I think it's obvious what happens, you import our "resource file", reference the image and get the Bitmap with `GetBitmap()`.

## What have I done so far?

So far I only have the graphic part

![Screenshot_4](https://user-images.githubusercontent.com/36505934/212675034-8e4eae7e-abe8-467e-aa5c-c371adcbbb61.png)

I was trying to work on the logic part but I ran into a lot of mishaps.

* In [my fork](https://github.com/Jalkhov/wxGlade/tree/resources-module) I managed to:
  * Get the DOM of the project
  * Modify the DOM (ONE INSTANCE)
  * Add the `<resources>` tags and register the new resource file and save the `.wxg` file with that information.

The problem comes when you press the save button, WxGlade deletes all this information because it is not programmed to recognize it.

My attempts were mostly oriented to modify `common.root.children` but apparently only **widgets** can go there, and even if I managed to add the **resources** tags there, when saving it would be deleted.

For reference, when you create a resource file in **Qt Designer**, this information is added to the project file when you save the changes, it is like a kind of buffer that is modified and not applied until you save the changes, and if I am not mistaken, WxGlade also has that kind of buffer.

## What am I looking for?

Some guidance on how I might add this information:

```xml
<resources>
    <include location="brand.wrc" />
</resources>
```

to the `.wxg` file in a persistent way (clearly it would be deleted when all resource files are deleted). With that taken care of the rest is much """"easier"""".

If there is the possibility that the main developer wants to discard this idea I understand perfectly, and excuse the testament, it is only that I didn't want to look like a crazy person looking for a job to be done and that I really have a clear idea of my objective. In case you want to consider this, I think it would be a good idea to move this to a discussion.

**Comment by DietmarSchwertberger** [comment]
Sorry for the late reply.
I see the point for loading resources from a resource file, optionally included into a .exe file.
The current workaround, described at https://wxglade.sourceforge.net/docs/bitmaps.html#customizing-bitmap-loading, is not very nice.

I don't see why this should be implemented for wxGlade, though. Especially, I would not at all want the resources to be included into a resource file while working on a project.

So, this should be addressed to the people who develop the "compilers", installers and maybe wxPython itself.
