### ISSUE TITLE
WxGlade segfault

### ISSUE THREAD

**Issue by luciorgomes** [wxGlade/wxGlade#528]
WxGlade started to segfault when running. I'm on Endeavour (Arch based). Maybe caused by some Python recent update (3.10.10-1 version)?

 '/home/luciorg/wxGlade-1.0.4/wxglade'                       SEGV ✘ 
INFO    : Starting wxGlade version "1.0.4" on Python 3.10.10
INFO    : Using wxPython 4.2.0
INFO    : Loading "wconfig" modules from /home/luciorg/wxGlade-1.0.4/widgets/widgets.txt:
INFO    : Load code generators:
INFO    :   lisp generator loaded
INFO    :   perl generator loaded
INFO    :   C++ generator loaded
INFO    :   XRC generator loaded
INFO    :   python generator loaded
INFO    : Loading widgets from /home/luciorg/wxGlade-1.0.4/widgets/widgets.txt:
INFO    : 	frame
INFO    : 	dialog
INFO    : 	panel
INFO    : 	notebook
INFO    : 	splitter_window
INFO    : 	button
INFO    : 	toggle_button
INFO    : 	bitmap_button
INFO    : 	spin_button
INFO    : 	text_ctrl
INFO    : 	choice
INFO    : 	combo_box
INFO    : 	list_box
INFO    : 	check_list_box
INFO    : 	checkbox
INFO    : 	radio_button
INFO    : 	radio_box
INFO    : 	spin_ctrl
INFO    : 	spin_ctrl_double
INFO    : 	slider
INFO    : 	gauge
15:36:18: Debug: Adding duplicate image handler for 'Windows bitmap file'
15:36:18: Debug: Adding duplicate animation handler for '1' type
15:36:18: Debug: Adding duplicate animation handler for '2' type
INFO    : 	calendar_ctrl
INFO    : 	generic_calendar_ctrl
INFO    : 	datepicker_ctrl
INFO    : 	list_ctrl
INFO    : 	tree_ctrl
INFO    : 	grid
INFO    : 	static_text
INFO    : 	hyperlink_ctrl
INFO    : 	static_line
INFO    : 	static_bitmap
INFO    : 	spacer
INFO    : 	property_grid_manager
INFO    : 	search_ctrl
INFO    : 	custom_widget
INFO    : 	menubar
INFO    : 	toolbar
INFO    : 	statusbar
INFO    : Load sizer generators:
INFO    :   for lisp
INFO    :   for perl
INFO    :   for C++
INFO    :   for XRC
INFO    :   for python
zsh: segmentation fault (core dumped)  '/home/luciorg/wxGlade-1.0.4/wxglade'

**Comment by DietmarSchwertberger** [comment]
Is this happening right on start up? It could be the same as issue #526 
Could you please try the current version from the repository?
You can download it from https://github.com/wxGlade/wxGlade/archive/refs/heads/master.zip
Probably the issue is fixed. If you confirm that this is working, I will prepare a new release.

**Comment by DietmarSchwertberger** [comment]
also in the REV_1.0 branch

**Comment by DietmarSchwertberger** [comment]
revision 1.0.5 about to be released
