### ISSUE TITLE
Generating code fails when using extra property at windows

### ISSUE THREAD

**Issue by MrSilco** [wxGlade/wxGlade#529]
I would have liked to generate code for **Perl** from a wxg file that has an extra property at a window. I get the following error:

> ERROR   : An internal error occurred while Generate Code
> An unexpected error occurred!
> 
> Exception type:      <class 'AttributeError'>
> Exception details:   'PerlFrameCodeGenerator' object has no attribute 'generate_code_extraproperties'
> 
> Application stack traceback:
>   File "/Volumes/AC/Work/GSAT-3351/wxGlade/application.py", line 536, in generate_code
>     writer.generate_code(self, widget)
>   File "/Volumes/AC/Work/GSAT-3351/wxGlade/codegen/__init__.py", line 474, in generate_code
>     self._generate_code(None, None, None, c)
>   File "/Volumes/AC/Work/GSAT-3351/wxGlade/codegen/__init__.py", line 467, in _generate_code
>     self.finalize_class(obj)
>   File "/Volumes/AC/Work/GSAT-3351/wxGlade/codegen/__init__.py", line 649, in finalize_class
>     code_lines = self.generate_code_ctor(code_obj, is_new, tab)
>   File "/Volumes/AC/Work/GSAT-3351/wxGlade/codegen/perl_codegen.py", line 386, in generate_code_ctor
>     for l in builder.generate_code_extraproperties(code_obj):
> 
> Date and time:       2023-03-23T10:27:02.659381
> Python version:      3.10.8
> wxPython version:    4.2.0
> wxWidgets platform:  __WXMAC__
> wxGlade version:     1.1.0pre

Anyway the code generation works with all languages but **Perl & Lisp**. For reproduction, create a MainDialog, add a property for it after that generate code.

**Comment by DietmarSchwertberger** [comment]
revision 1.0.5 about to be released

**Comment by MrSilco** [comment]
The code generation works now. Thanks for the fix! I could only test the Perl code because I don't really know Lisp and it looks good.
