### ISSUE TITLE
Infinite loop generating xrc with button

### ISSUE THREAD

**Issue by scottb88** [wxGlade/wxGlade#532]
Create wxg file with a button with the text: "Save &&\nClose"

Entered into wxGlade as:

Save &&
Close

Two ampersands to escape into one, instead of being an accelerator key.
Desired result on button:

Save &
Close

The design window shows the desired results on the button.

While generating xrc file, val holds the button text and it infinite loops.
widgets/button/codegen.py line 62 to 69

The issue has been reproduced on 1.05 and head as of 2023-06-29.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. This should now be fixed in the master branch. Please test.

**Comment by scottb88** [comment]
It works now. Thank you very much.

**Comment by DietmarSchwertberger** [comment]
pre-release 1.1.0a1 is online now
