### ISSUE TITLE
Please include wxTimePickerCtrl

### ISSUE THREAD

**Issue by MichaelNZ85** [wxGlade/wxGlade#533]
I'm using wxGlade for a project that needs a wxTimePickerCtrl, and I'm struggling to get one into my grid generated by wxGlade in the class that is subclassed from the frame generated by wxGlade. This would be so much easier if wxGlade included this control along with wxDatePickerCtrl

**Comment by DietmarSchwertberger** [comment]
I will look into this, but don't hold your breath.
You should be able to design with a DatePickerCtrl and set Instance Class to wxTimePickerCtrl.
Alternatively, use a Custom Widget: https://wxglade.sourceforge.net/docs/custom_widgets.html#more-examples

**Comment by DietmarSchwertberger** [comment]
I found I had designed an icon for TimePicker some time ago already. 
So, I have added support for it to the master branch (actually, more or less just copied the code from DatePicker).
Please try whether it's working.
