### ISSUE TITLE
wxGlade crashes when you delete a Property Grid Manager from the Design window.

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#535]
Python 3.10.12
wxPython 4.2.1 gtk3 (phoenix) wxWidgets 3.2.2.1
Linux Mint 21.2

* Start wxGlade 1.1.0a1.
* Add a Frame.
* Add a Property Grid Manager to the Frame's sizer_1.
* Ensure the Design window has the focus and the Property Grid Manager is selected.
* Press the 'Del' key.

wxGlade crashes and writes 'Segmentation fault (core dumped)' to stderr.

So far I haven't been able to duplicate with any other control.

I also tested the same steps using v1.0.5 and it also crashes.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. I can't see this on Windows with the wxPython version that I have.
I will look into it, but it will probably take to the end of the week.

**Comment by DietmarSchwertberger** [comment]
I can see this in my Ubuntu VM with wxPython 4.1.1 when the PropertyGridManager actually has the focus, i.e. the cursor is in one of the data cells. I don't see it if the PropertyGridManager is just selected.

**Comment by reticulatus** [comment]
On my system, if I click on the Design window's title bar to give the window the focus and the cursor is _not_ in any of the data cells, then it does crash when I press 'Del'.

However, if I right-click of the control and select 'Remove PropertyGridManager' from the context menu, then wxGlade doesn't crash. 

Also, if I select the PropertyGridManager in the tree control and press 'Del' it doesn't crash there either.

**Comment by DietmarSchwertberger** [comment]
I have uploaded a fix for `misc.restore_focus`. At the time I probably thought that `common.app_tree.FindFocus()` would only return a widget if `common.app_tree` has the focus.

There is still some work required to make things smoother.

**Comment by DietmarSchwertberger** [comment]
1.1.0a2 does contain the fix and is online.
