### ISSUE TITLE
wxGrid accessibility support for screen readers on Windows

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxGlade/wxGlade#539]
This 'issue' is not really about wxGlade.

I'm currently working on adding accessibility support for wxWidgets, which eventually also will its way into wxPython.
The rest of this post explains some technical backgrounds. If you're not interested in these, you may just skip to the next post which tells how to test and provide feedback.

As of now, wxGrid does not support screen readers. The reason is that it is a generic widget, i.e. it is drawn by wxWidgets itself. It is not using an underlying native Windows widget.
The other notable generic widget is wxDataView, which has accessibililty support in wxWidgets already.

The communication between screen readers and wxWidgets is done via  'Microsoft Active Accessiblilty' or IAccessible.
Unfortunately, via MSAA the screen readers only support a hierarchy of grid to cells.

A cell or label can have one of these roles, though:
 - ROLE_SYSTEM_COLUMNHEADER
 - ROLE_SYSTEM_ROWHEADER
 - ROLE_SYSTEM_CELL

The accessibility information that a screen reader will display is retrieved via several methods:
- get_accName
- get_accValue
- get_accDescription
- get_accHelp

There is no specification what these methods should return for a grid, so I need some feedback. See next post.

**Comment by DietmarSchwertberger** [comment]
I have prepared a first test version which will return this to a screen reader:
 - Name: the cell contents, retrieved via GetCellValue()
 - Value: the row and column information
 - Description: nothing
 
This does not yet support things like triggering default actions. It will return "Edit" as default action, though. So please tell me whether this is useful.
Also, it does not implement `get_accHelp`. I would guess that this should return the same what is displayed as tooltip.

It does not support selection via the screen reader. I'm not sure whether this needs to be implemented. You can select cells via the keyboard.

Please download the test application from [Sourceforge](https://sourceforge.net/projects/wxglade/files/wxWidgets/wxGrid_Accessibility/2023-01-29/)


Don't hold the shift key while starting the app, because then it would open a console window with a lot of debug messages.

For now, just ignore all the menu items. The application is based on the grid demo of wxWidgets.
The cell contents:
 - Columns A to C describe and show several data types.
 - The next column is just empty.
 - Columns D and following have column labels. The column 'Localized Dates' has a line break inbetween.
 - Columns E to G contain floating point values. The first row has some info about the precision of the values.
 - Column H contains an integer in the second row and an integer with range restriction in the fourth row.
 - Colums I and J contain some dates with different format.

**Comment by DietmarSchwertberger** [comment]
P.S.: I don't know how accessibly github is. We could also move this discussion to the wxGlade mailing list.

**Comment by GabrieleBattaglia** [comment]
Hi Dietmar. I tried to built the very first infrastructure of an app and the item in palette window (f4) are spoken all as button. In the preview version they were correctly reported by NVDA. Is it only me?

**Comment by DietmarSchwertberger** [comment]
The pull request for wxWidgets is now online. Still awaiting feedback.

**Comment by vortex1024** [comment]
HI Dietmar, was this merged? and if yes, from what version onwards? Thanks

**Comment by DietmarSchwertberger** [comment]
It was merged into wxWidgets two weeks ago, so it should be part of the next wxWidgets release. It will take time until it will be part of a wxPython release.
https://github.com/wxWidgets/wxWidgets/commit/47a4e70928ea3b06b490d6236a9baa60b01f0194
