### ISSUE TITLE
Erreur de segmentation (core dumped)

### ISSUE THREAD

**Issue by romacar** [wxGlade/wxGlade#542]
Hello,

when I start wxglade, I receive the following message:
**Erreur de segmentation (core dumped)**
and this layout on terminal:

**_INFO    : Starting wxGlade version "1.1.0a2" on Python 3.11.8
INFO    : Using wxPython 4.2.1
INFO    : Loading "wconfig" modules from /run/media/carlos.romero-martin/T7/wxGlade/wxGlade-1.1.0a2/widgets/widgets.txt:
INFO    : Load code generators:
INFO    :   C++ generator loaded
INFO    :   lisp generator loaded
INFO    :   perl generator loaded
INFO    :   python generator loaded
INFO    :   XRC generator loaded
INFO    : Loading widgets from /run/media/carlos.romero-martin/T7/wxGlade/wxGlade-1.1.0a2/widgets/widgets.txt:
INFO    :       frame
INFO    :       dialog
INFO    :       panel
INFO    :       notebook
INFO    :       splitter_window
INFO    :       button
INFO    :       toggle_button
INFO    :       bitmap_button
INFO    :       spin_button
INFO    :       text_ctrl
INFO    :       choice
INFO    :       combo_box
INFO    :       list_box
INFO    :       check_list_box
INFO    :       checkbox
INFO    :       radio_button
INFO    :       radio_box
INFO    :       spin_ctrl
INFO    :       spin_ctrl_double
INFO    :       slider
INFO    :       gauge
15:46:36: Debug: Adding duplicate image handler for 'Windows bitmap file'
15:46:36: Debug: Adding duplicate animation handler for '1' type
15:46:36: Debug: Adding duplicate animation handler for '2' type
INFO    :       calendar_ctrl
INFO    :       generic_calendar_ctrl
INFO    :       datepicker_ctrl
INFO    :       timepicker_ctrl
INFO    :       list_ctrl
INFO    :       tree_ctrl
INFO    :       grid
INFO    :       static_text
INFO    :       hyperlink_ctrl
INFO    :       static_line
INFO    :       static_bitmap
INFO    :       spacer
INFO    :       property_grid_manager
INFO    :       search_ctrl
INFO    :       custom_widget
INFO    :       menubar
INFO    :       toolbar
INFO    :       statusbar
INFO    : Load sizer generators:
INFO    :   for C++
INFO    :   for lisp
INFO    :   for perl
INFO    :   for python
INFO    :   for XRC_**

Thanks for you support
Best regards

Carlos

**Comment by DietmarSchwertberger** [comment]
What platform is this?

**Comment by romacar** [comment]
Hello, 

openSuSE Tumbleweed

Linux LaptopCRM 6.8.1-1-default #1 SMP PREEMPT_DYNAMIC Tue Mar 19 
07:32:20 UTC 2024 (d922afa) x86_64 x86_64 
x86_64 GNU/Linux


Carlos
--------------------------------------------------------------------------------

**Comment by DietmarSchwertberger** [comment]
Unfortunately there is only an old Tumbleweed virtual machine available for download: https://www.osboxes.org/opensuse/#google_vignette
This had an older Python version where I did not see problems.
Updating Python reports version conflicts and unfortunately it does not work afterwards:
![grafik](https://github.com/wxGlade/wxGlade/assets/5512021/011ab19b-618a-43b0-a2a5-4e8682e148cf)

I have now tried twice to update the distribution, but after that it does not boot at all. This is something that I have *never* seen with any Linux distribution.
Sorry, but I can't debug a distribution that is in such a bad shape.

**Comment by DietmarSchwertberger** [comment]
The openSUSE 15.5 Leap has ancient Python versions and is not even configured for GUI applications ("Unable to access the X Display, is %DISPLAY set properly?")

**Comment by romacar** [comment]
Hello,

How can I help you move forward, I'm stuck.
Can you give me instructions for debugging. I will provide you with my changes.
Obviously if you agree
Best regards

Carlos

**Comment by DietmarSchwertberger** [comment]
The reason is probably that an event is pending while some object is being deleted.
E.g. this commit fixed such a race condition which was only seen on SUSE: https://github.com/wxGlade/wxGlade/commit/a651a88c3b01dc6d6f6b9ade7d2855f519f1a048
Unfortunately, these conditions are hard to debug. Even if there was a stack backtrace, this would only show the situation after the problem.
Maybe you can step through with a debugger.

**Comment by romacar** [comment]
Hello,

I modify the main.py and it works very well
you find the main.py module with my modifications
delimited by --- CRMDevAppIT in two places in the code

Best regards

Carlos Romero Martin
--------------------------------------------------------------------------------
Le lundi 1 avril 2024, 20 h 44 min 53 s CEST Dietmar Schwertberger a écrit :
> The reason is probably that an event is pending while some object is being
> deleted. E.g. this commit fixed such a race condition which was only seen on
> SUSE:
> https://github.com/wxGlade/wxGlade/commit/
a651a88c3b01dc6d6f6b9ade7d2855f519f
> 1a048 Unfortunately, these conditions are hard to debug. Even if there was a
> stack backtrace, this would only show the situation after the problem. Maybe
> you can step through with a debugger.

**Comment by bh1rio** [comment]
The same error, and the same stdout info

EndeavourOS x64
kernel 6.8.2-arch2-1
python 3.11.8
wxpython 4.2.1

**Comment by DietmarSchwertberger** [comment]
@romacar : Would you mind posting your modifications here such that I can include them?

**Comment by romacar** [comment]
here my changes:
#--------> Start -CRMDDevAppIT        
        try:
#            select_page = self.pagenames[selection]  if selection!=-1  else None

            select_page = self.pagenames[selection]
            if selection == -1:
                None
        except:
            select_page = ""
            None
#--------> End -CRMDDevAppIT        
#--------> Start -CRMDDevAppIT        
            #self.notebook.RemovePage(self.notebook.GetPageCount())
            #compat.DestroyLater(dummy_panel)
#--------> End -CRMDDevAppIT       

Best regards
Carlos

**Comment by romacar** [comment]
Hi,
bad news, it doesn't work. The problem is still there

**Comment by DietmarSchwertberger** [comment]
I have now spent an hour on installing an Endavour virtual machine. This OS fails already at "After install tasks" "Update Systems" where it's downloading packages that it will then report as being corrupt.
Who is creating such distributions and why?

**Comment by bh1rio** [comment]
> I have now spent an hour on installing an Endavour virtual machine. This OS fails already at "After install tasks" "Update Systems" where it's downloading packages that it will then report as being corrupt. Who is creating such distributions and why?
> 
> ```
> error: failed to commit transaction (invalid or corrupted package (PGP signature))
> Errors occurred, no packages were upgraded.
> ```

You can do `Update Mirrors(Arch)` and `Update Mirrors(Endeavour)` in welcome window before install.
Then, do install with 'online' option.

I get success with this flow.

**Comment by DietmarSchwertberger** [comment]
In my Welcome window, there is only a single 'Update Mirrors' and that did not help.
![grafik](https://github.com/wxGlade/wxGlade/assets/5512021/538334fb-f9fa-4932-8577-9267b6953b29)

**Comment by reticulatus** [comment]
I found this thread: https://forum.endeavouros.com/t/i-am-receiving-invalid-or-corrupted-package-error-pgp-signature/41435

Does the suggestion for updating endeavouros-keyring help?

**Comment by DietmarSchwertberger** [comment]
@reticulatus :
Thanks, yesterday I spent another hour, trying the suggestions from https://forum.endeavouros.com/t/faq-issues-with-signature-is-marginal-trust-signature-is-unknown-trust-or-invalid-or-corrupted-package/6756 without success.

From your link I have tried the first command and it fails already with
```
File /var/cache/pacman/pkg/endeavouros-keyring-20231222-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```

I really don't understand the motivation to create yet another Linux distribution but not taking care at all about even the most basic functions.

It seems Endeavour OS is based on Arch. I will check whether my old Arch VM can be updated to Python 3.11.
My Ubuntu LTS VM does not have suitable wxPython packages.

**Comment by DietmarSchwertberger** [comment]
I have now downloaded an Arch 2022.01.01 VM from osboxes, which is usually a reliable source for VMs.
Unfortunately, it behaves the same.

```
sudo pacman -Syu

...

(512/512) checking package integrity                                 [######################################] 100%
error: linux-api-headers: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
:: File /var/cache/pacman/pkg/linux-api-headers-6.7-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 

...

error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.
```

Sorry, but these distributions are now on my black list.

**Comment by DietmarSchwertberger** [comment]
Ok, I found my first contact with Arch Linux 2018.09 was in 2020:
https://github.com/matplotlib/matplotlib/pull/11944#issuecomment-622378527
Four years and versions later it's still the same crap where even the most basic update command is failing.

Trying to support it was a waste of time and still is.
Do such distributions serve any other purpose than that some people can feel great about their very own cool platform?

**Comment by bh1rio** [comment]
> In my Welcome window, there is only a single 'Update Mirrors' and that did not help. ![grafik](https://private-user-images.githubusercontent.com/5512021/321345733-538334fb-f9fa-4932-8577-9267b6953b29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzgzMTIsIm5iZiI6MTcxMjgzODAxMiwicGF0aCI6Ii81NTEyMDIxLzMyMTM0NTczMy01MzgzMzRmYi1mOWZhLTQ5MzItODU3Ny05MjY3YjY5NTNiMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMTIyMDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q3Nzc4OGU4NjAyOTM1MmFmNzQ3YTgxYjkwMmNmMTNlYjIxMWY3N2ZlYTM5NGQ1NjlhYWE0MDkzNTZjNmM1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.juwuiouqCKbywV4OARe_gp4ed15C2xE55K3dJr4JLsE)

![截图_2024-04-11_20-23-06](https://github.com/wxGlade/wxGlade/assets/12414463/5a95a66f-a87a-4df9-bee1-61a404473dfc)

Download the newest version endeavouros iso.....

**Comment by bh1rio** [comment]
> @reticulatus : Thanks, yesterday I spent another hour, trying the suggestions from https://forum.endeavouros.com/t/faq-issues-with-signature-is-marginal-trust-signature-is-unknown-trust-or-invalid-or-corrupted-package/6756 without success.
> 
> From your link I have tried the first command and it fails already with
> 
> ```
> File /var/cache/pacman/pkg/endeavouros-keyring-20231222-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
> ```
> 
> I really don't understand the motivation to create yet another Linux distribution but not taking care at all about even the most basic functions.
> 
> It seems Endeavour OS is based on Arch. I will check whether my old Arch VM can be updated to Python 3.11. My Ubuntu LTS VM does not have suitable wxPython packages.

I think your iso is to old, and PGP sign is out date.
maybe you will download a newest iso

**Comment by DietmarSchwertberger** [comment]
These are the latest VMs. In the case of Endeavour OS it's even the only one.

**Comment by DietmarSchwertberger** [comment]
I have wasted one more evening with installing a VM from the ISO image.
And guess what? The online installation just stalls at 40%. The offline installation is stuck at partition setup. After re-boot at least the offline installation runs through. The initial system update then destroyed the installation again (file boot/vmlinzu-linux not found)
Please get a proper OS.

**Comment by DietmarSchwertberger** [comment]
This is probably a bug in gtk.
Could you please try the latest repository version of wxGlade? The dummy panel for size calculation is now deleted later.

**Comment by H4K0** [comment]
Hi, same error here. Sorry if report is not in right place where suppose to be.

My environment:
   **OS:** Arch Linux x86_64 
   **Kernel:** 6.9.5-arch1-1
   **Shell:** zsh 5.9
   **DE:** Plasma 6.0.5
   **Terminal:** konsole 


**1. What did you?**
     Download, accomplish requirements and run wxglade.py

**2. What do you want to happen?**
    Normally open de UI like always

**3. What actually happened?**
    In both cases, from wxGlade (sudo pacman -Syu wxglade) and from sourceforge (https://sourceforge.net/projects/wxglade/files/wxglade/1.1.0/  then run via $python wxglade.py), the output it's the same, and never open the UI:

Tested releases from Source Forge:
├── wxGlade
│   ├── wxGlade-1.0.3
│   ├── wxGlade-1.0.4
│   └── wxGlade-1.1.0
                   ├── wxGlade-1.1.0a1
                   └── wxGlade-1.1.0a2


**pacman | python via terminal**
`Output:`
$wxglade
INFO    : Starting wxGlade version "1.0.5" on Python 3.12.4 | INFO    : Starting wxGlade version "1.1.0a2" on Python 3.12.4

INFO    : Using wxPython 4.2.1
INFO    : Loading "wconfig" modules from /usr/lib/python3.12/site-packages/wxglade/widgets/widgets.txt:
INFO    : Load code generators:
INFO    :   C++ generator loaded
INFO    :   lisp generator loaded
INFO    :   perl generator loaded
INFO    :   python generator loaded
INFO    :   XRC generator loaded
INFO    : Loading widgets from /usr/lib/python3.12/site-packages/wxglade/widgets/widgets.txt:
INFO    :       frame
INFO    :       dialog
INFO    :       panel
INFO    :       notebook
INFO    :       splitter_window
INFO    :       button
INFO    :       toggle_button
INFO    :       bitmap_button
INFO    :       spin_button
INFO    :       text_ctrl
INFO    :       choice
INFO    :       combo_box
INFO    :       list_box
INFO    :       check_list_box
INFO    :       checkbox
INFO    :       radio_button
INFO    :       radio_box
INFO    :       spin_ctrl
INFO    :       spin_ctrl_double
INFO    :       slider
INFO    :       gauge
10:29:35: Debug: Adding duplicate image handler for 'Windows bitmap file'
10:29:35: Debug: Adding duplicate animation handler for '1' type
10:29:35: Debug: Adding duplicate animation handler for '2' type
INFO    :       calendar_ctrl
INFO    :       generic_calendar_ctrl
INFO    :       datepicker_ctrl
INFO    :       list_ctrl
INFO    :       tree_ctrl
INFO    :       grid
INFO    :       static_text
INFO    :       hyperlink_ctrl
INFO    :       static_line
INFO    :       static_bitmap
INFO    :       spacer
INFO    :       property_grid_manager
INFO    :       search_ctrl
INFO    :       custom_widget
INFO    :       menubar
INFO    :       toolbar
INFO    :       statusbar
INFO    : Load sizer generators:
INFO    :   for C++
INFO    :   for lisp
INFO    :   for perl
INFO    :   for python
INFO    :   for XRC
**[1]    13452 segmentation fault (core dumped)  wxglade  |  [1]    35186 segmentation fault (core dumped)  python wxglade.py
**
`EndOutput:`

**4. Provide a short example to reproduce the issue.**
    Install via pacman or download the script from sourceforge and lunch the app, reproduce the same output.


The problem are the segmentation fault, I can´t debug it.

Please let me know if need more information and really thank you for this great code/app.

Thanks again for helpful, and sorry for my English.

**Comment by DietmarSchwertberger** [comment]
@H4K0 : Could you please try with the current version from the repository?

**Comment by DietmarSchwertberger** [comment]
version 1.1.0b1 is online
