### ISSUE TITLE
Error when running first tutorial in docu

### ISSUE THREAD

**Issue by perwallner** [wxGlade/wxGlade#543]
When adding the very first window in the first tutorial https://wxglade.sourceforge.net/docs/tutorial.html I expected to get a ... Frame. I got this:
<img width="698" alt="Skärmavbild 2024-04-03 kl  18 08 23" src="https://github.com/wxGlade/wxGlade/assets/478470/e86b42a8-e710-446e-80de-436eb99e4add">

Error log:
ERROR   : None
An unexpected error occurred!

Exception type:      <class ’TypeError’>
Exception details:   Sizer.SetItemMinSize(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type ’float’
  overload 2: argument 2 has unexpected type ’int’
  overload 3: argument 1 has unexpected type ’ExpandoTextCtrl’
  overload 4: argument 1 has unexpected type ’ExpandoTextCtrl’
  overload 5: argument 1 has unexpected type ’ExpandoTextCtrl’
  overload 6: argument 1 has unexpected type ’ExpandoTextCtrl’

Application stack traceback:
  File ”/usr/local/lib/python3.11/site-packages/wx/core.py”, line 2346, in Notify
    self.notify()
  File ”/usr/local/lib/python3.11/site-packages/wx/core.py”, line 3552, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ”/Users/vi/Downloads/wxGlade-1.0.0/main.py”, line 135, in edit_properties
    self.create_editor(edit_widget)
  File ”/Users/vi/Downloads/wxGlade-1.0.0/main.py”, line 194, in create_editor
    property_instance.create_editor(current_page, current_sizer)
  File ”/Users/vi/Downloads/wxGlade-1.0.0/new_properties.py”, line 1390, in create_editor
    hsizer.SetItemMinSize(self.text, 100, h * 1.5)

Date and time:       2024-04-03T18:02:54.908212
Python version:      3.11.8
wxPython version:    4.2.1
wxWidgets platform:  __WXMAC__
wxGlade version:     1.0.0
=============================================

System:
- iMac Retina 5k 27" 2017 3,5 GHz Quad-Core Intel Core i5
- macOs 13.6.6 (22G630)
- Python 3.11.8 (Homebrew)
- wxPython 4.2.1

BR / Per

**Comment by DietmarSchwertberger** [comment]
1.0.0 is rather old.

This message is related to changes in Python. Float values used to be converted to integers automatically, but this does not happen any more.
Could you please try at least 1.0.4 or 1.1.0a2 or the current github version?
This has code like `int(round(h*1.5))` instead of ` h * 1.5`.

https://sourceforge.net/projects/wxglade/files/wxglade/1.1.0/

**Comment by DietmarSchwertberger** [comment]
P.S.: The changes are only minor, but in general it's best to open the tutorial from the Help menu.

**Comment by perwallner** [comment]
Hi!
Thanks a bunch!
I recently downloaded the sw from source forge and thought it was the latest… 
So I just downloaded 1.0.5 and all seems well! Sorry for my bad research… 😳

I’m more of a backend programmer and never really cared much about GUIs. I recently had reason to start writing a gui app,
but since it’s really a pain in the you-know-where I’m looking for a decent design tool. Afai reckon, the main choices are Glade and FormBuilder, and so
I’ve started out by comparing the two. If you’re interested I’ll give you feedback.

Tally-ho! 🏇🏽

Tschüß,
Per
-----------------------------------------------------------------
Per Wallner
Ålfors 232
815 91 Tierp
Skype: perwallner
LinkedIn: http://www.linkedin.com/in/perwallner
Phone: +46 70 979 0303

**Comment by DietmarSchwertberger** [comment]
Don't forget to download and run the wxPython demo as well. This demonstrates most of the available widgets.

Be aware that wxGlade can support any widget via the "Custom Widget". The version 1.1 has undo/redo.

Tell me if you're missing something.

**Comment by perwallner** [comment]
I have the demo package from https://extras.wxpython.org/wxPython4/extras/4.2.1/
Is that the one,p or is there some specific demo for wxPython/Glade?

Thanks for the Custom Widget hint - I appreciate it!

After an hour or two Glade certainly seems much more intuitive to work with!

1.1 seems ’α'… Would you regard it as ’stable enough’?
I’ll keep you posted! 

Bästa hälsningar
Per
-----------------------------------------------------------------
Per Wallner
Ålfors 232
815 91 Tierp
Skype: perwallner
LinkedIn: http://www.linkedin.com/in/perwallner
Phone: +46 70 979 0303

**Comment by DietmarSchwertberger** [comment]
That's the demo I was talking about. I'm emphasizing this, as many people are missing it.

I think 1.1.0a2 or the github master branch is stable enough. I got a bug report for SUSE and probably receive a fix for this. I think macOs is less picky.
I'm mainly on Windows and there it is fine for general use. Once #542 is fixed, I will probably upload a beta version.

In general, if there is a problem, I try to find a fix within a short time. On Linux that's often difficult if there is no suitable VM available for download for the specific distribution. On macOs there is only one 'distribution', but the situation may get worse due to the switch to ARM.

**Comment by perwallner** [comment]
OK, fine! 

Great, then even I dare try 1.1! 😉
I’m still on intel, for as long as I can update this ol’ rig… 

(Btw, I like Glade more’n’more!)

Bästa hälsningar
Per
-----------------------------------------------------------------
Per Wallner
Ålfors 232
815 91 Tierp
Skype: perwallner
LinkedIn: http://www.linkedin.com/in/perwallner
Phone: +46 70 979 0303

**Comment by DietmarSchwertberger** [comment]
> (Btw, I like Glade more’n’more!)
Well, it's great for a certain type of applications. E.g. I'm doing a lot of measurement and control software with tabs, buttons and plots.
It won't help you much for things like document editors. But even then, it can help you with the required dialogs.

**Comment by perwallner** [comment]
We’re in the same club - I’m not overly interested in docs… 😂

Bästa hälsningar
Per
-----------------------------------------------------------------
Per Wallner
Ålfors 232
815 91 Tierp
Skype: perwallner
LinkedIn: http://www.linkedin.com/in/perwallner
Phone: +46 70 979 0303
