### ISSUE TITLE
wxNotebook has unsupported style NB_FLAT

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#545]
The issue can be triggered by the following steps:

1. Start wxGlade.
2. Add a Frame.
3. Add a Notebook to the Frame.
4. In the Properties window, select the Notebook's Widget tab.
5. Check the wxNB_FLAT option.
6. Select File -> Save and save the project.
7. In the Properties window, select the Frame's Common tab.
8. Click on the 'Show Preview' button.

An Error Dialog is then displayed which says:

```
ERROR   : An internal error occurred while Generate Preview
An unexpected error occurred!

Exception type:      <class 'AttributeError'>
Exception details:   module 'wx' has no attribute 'NB_FLAT'

Application stack traceback:
  File "/usr/share/wxglade-1.1.0a2/application.py", line 670, in preview
    frame = preview_class(None, -1, '')
  File "/home/richardt/Development/python/_wxglade_850982435.py", line 22, in __init__
    self.notebook_1 = wx.Notebook(self.panel_1, -1, style=wx.NB_FLAT | wx.NB_TOP)

Date and time:       2024-04-16T08:22:10.027208
Python version:      3.10.12
wxPython version:    4.2.1
wxWidgets platform:  __WXGTK__
wxGlade version:     1.1.0a2
```

I can't find any mention of NB_FLAT in the wxPython 4.2.1 documentation.

**Edit**: it does appear in 4.0.7: https://docs.wxpython.org/4.0.7/wx.Notebook.html
```
wx.NB_FLAT: (Windows CE only) Show tabs in a flat style.
```

**Comment by reticulatus** [comment]
I don't get tooltips for any of the Style checkboxes. In fact I don't get tooltips for a lot of the entries in the Properties dialog.

In the case of the Notebook control, on the Common tab, I get tooltips for Name down to Max Size, but not for any of the options below Max Size. On the Layout tab I get tooltips for the Border width SpinCtrl, but not for any of the other controls.

Should I be seeing tooltips for all options?

I am using wxPython 4.2.1 + Python 3.10.12 + Linux Mint 21.3

**Comment by DietmarSchwertberger** [comment]
You should see tooltips for the most styles and also for many other checkboxes.

On Windows:
![grafik](https://github.com/wxGlade/wxGlade/assets/5512021/301d962e-4ebb-490a-962b-1b2d99a19848)

![grafik](https://github.com/wxGlade/wxGlade/assets/5512021/45755e7d-a28a-4379-839d-d86f82ef8c59)

![grafik](https://github.com/wxGlade/wxGlade/assets/5512021/5698e365-89fe-46eb-be2d-c639343fa7d6)

I have just checked and on Ubuntu I also don't see tooltips for checkboxes inside static sizer boxes. I will look into this.

**Comment by DietmarSchwertberger** [comment]
On the common tab, the properties below Size / Max Size don't have tooltips.

It seems there's a bug in wxGTK such that tooltips within static sizers are not shown.

Here, I have tooltips for all widgets outside the static box.
Inside, only the tooltips for the text control are shown:
![grafik](https://github.com/wxGlade/wxGlade/assets/5512021/2fa62531-337d-4fd8-8165-9bff4bde1cab)

It seems that this is an old bug or feature:
https://github.com/wxWidgets/wxWidgets/issues/13160

I need to think about this.

**Comment by DietmarSchwertberger** [comment]
OK, I have confirmed that the workaround to use the static box as parent does indeed work.
So, as first step I will modify the property panel. Second step will be the code generation.
Thanks for reporting. I would not have found this in a 100 years.

**Comment by DietmarSchwertberger** [comment]
Please try the latest version from Github.

Code generation needs to be fixed and also there are probably no tooltips yet on gtk for grid based properties.
On Windows grid based properties have tooltips like these:
![grafik](https://github.com/wxGlade/wxGlade/assets/5512021/02491aa0-a9ce-4bd3-aa6a-2f28263f1d7c)

**Comment by reticulatus** [comment]
I have tested the latest version from GitHub and can confirm that the tooltips for the checkboxes on the Layout and Widget tabs are now appearing. 

On the Events tab tooltips are shown for the items in the grid.

**Comment by DietmarSchwertberger** [comment]
Now you should also see tooltips for the Insert/Add/Remove buttons.
It's only about the keyboard shortcuts, though.

**Comment by reticulatus** [comment]
Yes, tooltips for the Insert/Add/Remove buttons now working.

**Comment by DietmarSchwertberger** [comment]
Code generation is now also fixed for wx >= 3.0.

**Comment by DietmarSchwertberger** [comment]
I have now removed this obsolete style. Don't think that anyone ever used wxGlade for Windows CE and probably nobody does any development for CE any more. (Even though I would assume it's still in use in some embedded environments.)

**Comment by reticulatus** [comment]
I have just downloaded and tested the latest master branch.

When I add a Notebook to a Frame I get the following error:

```
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'KeyError'>
Exception details:   'wxNB_FLAT'

Application stack traceback:
  File "/home/richardt/.local/lib/python3.10/site-packages/wx/core.py", line 2346, in Notify
    self.notify()
  File "/home/richardt/.local/lib/python3.10/site-packages/wx/core.py", line 3552, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/home/richardt/Sources/applications/UI Builders/wxGlade/issues/545_nb_flat_style_and_tooltips_on_gtk/wxGlade-master/main.py", line 136, in edit_properties
    self.create_editor(edit_widget)
  File "/home/richardt/Sources/applications/UI Builders/wxGlade/issues/545_nb_flat_style_and_tooltips_on_gtk/wxGlade-master/main.py", line 196, in create_editor
    property_instance.create_editor(current_page, current_sizer)
  File "/home/richardt/Sources/applications/UI Builders/wxGlade/issues/545_nb_flat_style_and_tooltips_on_gtk/wxGlade-master/new_properties.py", line 1237, in create_editor
    style_def = config.widget_config["generic_styles"][name]

Date and time:       2024-04-19T08:10:09.571423
Python version:      3.10.12
wxPython version:    4.2.1
wxWidgets platform:  __WXGTK__
wxGlade version:     1.1.0a2
```

This results in a completely blank Properties panel for the Notebook.

**Comment by reticulatus** [comment]
The error reported in my previous comment appears to be due to line 41 in `widgets/notebook/wconfig.py`

```
    'style_list': ['wxNB_TOP', 'wxNB_LEFT', 'wxNB_RIGHT', 'wxNB_BOTTOM',
                   'wxNB_FIXEDWIDTH', 'wxNB_MULTILINE', 'wxNB_NOPAGETHEME',
                   'wxNB_FLAT'],
```

If I remove 'wxNB_FLAT' from the list, the error does not occur.

**Comment by DietmarSchwertberger** [comment]
Sorry and thanks. It's now fixed in the repository.
