### ISSUE TITLE
When a SearchCtrl is added, it is given the name 'text_ctrl_1'

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#546]
When I add a SearchCtrl to a wxGlade project it is given the name `'text_ctrl_1'` ?

I was expecting it to be `'search_ctrl_1'`.

Using wxGlade 1.1.0a2 + wxPython 4.2.1 + Python 3.10.12 + Linux Mint 21.3.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. It's changed now in the repository. Please test.

**Comment by reticulatus** [comment]
Tested current master branch and confirmed default name is fixed.
