### ISSUE TITLE
python3 ./wxglade.py - shows segmentation fault (core dumpled) on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by shashwatss** [wxGlade/wxGlade#550]
Hello, 

- after cloning the repo, I executed the command `python3 ./wxglade.py`. The GUI opens, and then when I close it, the terminal shows - Segmentation fault(core dumped).

- I also installed wxglade from ubuntu apt - `apt install wxglade`, which in-turn installs the python3-wxglade as dependencies. Installation ended successfully, and I was also able to see a wxglade icon in 'applications'. Upon executing the command `wxglade --version in terminal, it loads the version followed by the preamble "Segmentation fault (core dumped)" again.

Is the Segmentation Fault (core dumped) expected?

Many thanks in advance

**Comment by DietmarSchwertberger** [comment]
No, the core dump is certainly not expected. On my Ubuntu VM things are working.
```
osboxes@osboxes:~/wxGlade$ python3 wxglade.py
INFO    : Starting wxGlade version "1.1.0a2" on Python 3.11.6
INFO    : Using wxPython 4.2.1
...
```
```
osboxes@osboxes:~/wxGlade$ python3 wxglade.py --version
wxGlade version 1.1.0a2
Copyright (C) 2007-2012 Alberto Griggio
Copyright (C) 2011-2016 Carsten Grohmann
Copyright (C) 2016-2024 Dietmar Schwertberger
License MIT: The MIT License
             <http://www.opensource.org/licenses/mit-license.php>
osboxes@osboxes:~/wxGlade$ 
```

Also, the package seems to work:
```
sboxes@osboxes:~/wxGlade$ wxglade
INFO    : Starting wxGlade version "1.0.5+repack" on Python 3.11.6
INFO    : Using wxPython 4.2.1
...
```

Recently there were issues with Arch and SUSE, but these should be fixed in the repository as well.

**Comment by tmbartie** [comment]
I am also having this problem on 24.04 LTS, both with the ubuntu package installed from apt install wxglade, and the zipfile download from the wxGlade website.  The terminal output is shown below.  There seems to be no attempt to load the GUI, or at least nothing is drawn on the screen.

```
tmb@Bonobo:~/Downloads/wxGlade-1.0.5$ ./wxglade
INFO    : Starting wxGlade version "1.0.5" on Python 3.12.3
INFO    : Using wxPython 4.2.1
INFO    : Loading "wconfig" modules from /home/tmb/Downloads/wxGlade-1.0.5/widgets/widgets.txt:
INFO    : Load code generators:
INFO    :   python generator loaded
INFO    :   lisp generator loaded
INFO    :   XRC generator loaded
INFO    :   perl generator loaded
INFO    :   C++ generator loaded
INFO    : Loading widgets from /home/tmb/Downloads/wxGlade-1.0.5/widgets/widgets.txt:
INFO    : 	frame
INFO    : 	dialog
INFO    : 	panel
INFO    : 	notebook
INFO    : 	splitter_window
INFO    : 	button
INFO    : 	toggle_button
INFO    : 	bitmap_button
INFO    : 	spin_button
INFO    : 	text_ctrl
INFO    : 	choice
INFO    : 	combo_box
INFO    : 	list_box
INFO    : 	check_list_box
INFO    : 	checkbox
INFO    : 	radio_button
INFO    : 	radio_box
INFO    : 	spin_ctrl
INFO    : 	spin_ctrl_double
INFO    : 	slider
INFO    : 	gauge
13:55:17: Debug: Adding duplicate image handler for 'Windows bitmap file'
13:55:17: Debug: Adding duplicate animation handler for '1' type
13:55:17: Debug: Adding duplicate animation handler for '2' type
INFO    : 	calendar_ctrl
INFO    : 	generic_calendar_ctrl
INFO    : 	datepicker_ctrl
INFO    : 	list_ctrl
INFO    : 	tree_ctrl
INFO    : 	grid
INFO    : 	static_text
INFO    : 	hyperlink_ctrl
INFO    : 	static_line
INFO    : 	static_bitmap
INFO    : 	spacer
INFO    : 	property_grid_manager
INFO    : 	search_ctrl
INFO    : 	custom_widget
INFO    : 	menubar
INFO    : 	toolbar
INFO    : 	statusbar
INFO    : Load sizer generators:
INFO    :   for python
INFO    :   for lisp
INFO    :   for XRC
INFO    :   for perl
INFO    :   for C++
Segmentation fault (core dumped)
```

**Comment by shashwatss** [comment]
Hallo,
I performed a latest pull from the master(although not much has changed) and also a sudo apt upgrade and update on my system.

The GUI loads fine -> although upon closing it, it shows "Segmentation Fault (core dumped)"
`
```
Starting wxGlade version "1.1.0a2" on Python 3.12.3
INFO    : Using wxPython 4.2.1
INFO    : Loading "wconfig" modules from /home/xxx/tools/wxGlade/widgets/widgets.txt:
INFO    : Load code generators:
INFO    :   XRC generator loaded
INFO    :   C++ generator loaded
INFO    :   perl generator loaded
INFO    :   lisp generator loaded
INFO    :   python generator loaded
INFO    : Loading widgets from /home/xxx/tools/wxGlade/widgets/widgets.txt:
INFO    : 	frame
INFO    : 	dialog
INFO    : 	panel
INFO    : 	notebook
INFO    : 	splitter_window
INFO    : 	button
INFO    : 	toggle_button
INFO    : 	bitmap_button
INFO    : 	spin_button
INFO    : 	text_ctrl
INFO    : 	choice
INFO    : 	combo_box
INFO    : 	list_box
INFO    : 	check_list_box
INFO    : 	checkbox
INFO    : 	radio_button
INFO    : 	radio_box
INFO    : 	spin_ctrl
INFO    : 	spin_ctrl_double
INFO    : 	slider
INFO    : 	gauge
06:55:06 PM CEST: Debug: Adding duplicate image handler for 'Windows bitmap file'
06:55:06 PM CEST: Debug: Adding duplicate animation handler for '1' type
06:55:06 PM CEST: Debug: Adding duplicate animation handler for '2' type
INFO    : 	calendar_ctrl
INFO    : 	generic_calendar_ctrl
INFO    : 	datepicker_ctrl
INFO    : 	timepicker_ctrl
INFO    : 	list_ctrl
INFO    : 	tree_ctrl
INFO    : 	grid
INFO    : 	static_text
INFO    : 	hyperlink_ctrl
INFO    : 	static_line
INFO    : 	static_bitmap
INFO    : 	spacer
INFO    : 	property_grid_manager
INFO    : 	search_ctrl
INFO    : 	custom_widget
INFO    : 	menubar
INFO    : 	toolbar
INFO    : 	statusbar
INFO    : Load sizer generators:
INFO    :   for XRC
INFO    :   for C++
INFO    :   for perl
INFO    :   for lisp
INFO    :   for python


Segmentation fault (core dumped)

```

Until now, there have been no issues due to the Seg-fault pertaining to generation of gui code. 
I will hence close this issue. Thank you for your support. :)

**Comment by DietmarSchwertberger** [comment]
I will update my Ubuntu VM and check whether I can reproduce the core dump on closing. If I can reproduce it, I can probably fix it.

**Comment by DietmarSchwertberger** [comment]
On my updated VM I still can't see the problem.
```
osboxes@osboxes:~/wxGlade$ python3 wxglade.py
INFO    : Starting wxGlade version "1.1.0a2" on Python 3.12.3
INFO    : Using wxPython 4.2.1
```
Do you see the problem when you just start and end wxGlade or is it required to load a certain .wxg file?

**Comment by chucktilbury** [comment]
I have this problem and here is a difference:  

INFO    : Starting wxGlade version "1.0.5+repack" on Python 3.12.3
INFO    : Using wxPython 4.2.1

Note that my wxglade version line is "1.0.5" and yours is "1.1.0a2".  Is there a way to update that without reinstalling everything from scratch?

$ cat /etc/os-install
NAME="Linux Mint"
VERSION="22.1 (Xia)"
ID=debian
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 22.1"
VERSION_ID="22.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=xia
UBUNTU_CODENAME=noble

$ uname -a
Linux xxxxx 6.8.0-83-generic #83-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep  5 21:46:54 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

$ wx-config --cppflags --cxxflags --cflags --ld 
g++ -o
-I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.2 -I/usr/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__
-I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.2 -I/usr/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread
-I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.2 -I/usr/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread

$ gtk-query-settings
gtk-double-click-time: 400
gtk-double-click-distance: 5
gtk-cursor-blink: TRUE
gtk-cursor-blink-time: 1200
gtk-cursor-blink-timeout: 10
gtk-split-cursor: TRUE
gtk-cursor-aspect-ratio: 0.040000
gtk-theme-name: "Mint-Y-Aqua"
gtk-icon-theme-name: "Adwaita"
!           gtk-fallback-icon-theme: NULL
gtk-key-theme-name: NULL
gtk-menu-bar-accel: "F10"
gtk-dnd-drag-threshold: 8
gtk-font-name: "Ubuntu 12"
!                    gtk-icon-sizes: "panel-menu-bar=24,24"
gtk-modules: NULL
gtk-xft-antialias: 1
gtk-xft-hinting: 1
gtk-xft-hintstyle: "hintslight"
gtk-xft-rgba: "rgb"
gtk-xft-dpi: 98304
gtk-cursor-theme-name: "DMZ-White"
gtk-cursor-theme-size: 30
gtk-alternative-button-order: FALSE
gtk-alternative-sort-arrows: FALSE
!        gtk-show-input-method-menu: FALSE
!             gtk-show-unicode-menu: FALSE
!               gtk-timeout-initial: 500
!                gtk-timeout-repeat: 50
!                gtk-timeout-expand: 500
!                  gtk-color-scheme: ""
gtk-enable-animations: TRUE
!              gtk-touchscreen-mode: FALSE
!               gtk-tooltip-timeout: 500
!        gtk-tooltip-browse-timeout: 60
!   gtk-tooltip-browse-mode-timeout: 500
!            gtk-keynav-cursor-only: FALSE
!            gtk-keynav-wrap-around: TRUE
gtk-error-bell: TRUE
!                        color-hash: ((GHashTable*) 0x573c2629a9f0)
!          gtk-file-chooser-backend: NULL
gtk-print-backends: "file,cups"
gtk-print-preview-command: "evince --unlink-tempfile --preview --print-settings %s %f"
gtk-enable-mnemonics: TRUE
gtk-enable-accels: TRUE
!            gtk-recent-files-limit: 50
gtk-im-module: NULL
gtk-recent-files-max-age: 30
gtk-fontconfig-timestamp: 1762536893
gtk-sound-theme-name: "Yaru"
gtk-enable-input-feedback-sounds: TRUE
gtk-enable-event-sounds: TRUE
!               gtk-enable-tooltips: TRUE
!                 gtk-toolbar-style: GTK_TOOLBAR_BOTH_HORIZ
!             gtk-toolbar-icon-size: GTK_ICON_SIZE_LARGE_TOOLBAR
!                gtk-auto-mnemonics: TRUE
gtk-primary-button-warps-slider: TRUE
!                 gtk-visible-focus: GTK_POLICY_AUTOMATIC
gtk-application-prefer-dark-theme: FALSE
!                 gtk-button-images: FALSE
gtk-entry-select-on-focus: TRUE
gtk-entry-password-hint-timeout: 0
!                   gtk-menu-images: TRUE
!          gtk-menu-bar-popup-delay: 0
!     gtk-scrolled-window-placement: GTK_CORNER_TOP_LEFT
!             gtk-can-change-accels: FALSE
!              gtk-menu-popup-delay: 225
!            gtk-menu-popdown-delay: 1000
gtk-label-select-on-focus: TRUE
!                 gtk-color-palette: "black:white:gray50:red:purple:blue:light blue:green:yellow:orange:lavender:brown:goldenrod4:dodger blue:pink:light green:gray10:gray30:gray75:gray90"
!              gtk-im-preedit-style: GTK_IM_PREEDIT_CALLBACK
!               gtk-im-status-style: GTK_IM_STATUS_CALLBACK
gtk-shell-shows-app-menu: FALSE
gtk-shell-shows-menubar: FALSE
gtk-shell-shows-desktop: TRUE
gtk-decoration-layout: "menu:minimize,maximize,close"
gtk-titlebar-double-click: "toggle-maximize"
gtk-titlebar-middle-click: "lower"
gtk-titlebar-right-click: "menu"
gtk-dialogs-use-header: FALSE
gtk-enable-primary-paste: TRUE
gtk-recent-files-enabled: TRUE
gtk-long-press-time: 500
gtk-keynav-use-caret: FALSE
gtk-overlay-scrolling: TRUE

**Comment by DietmarSchwertberger** [comment]
You can just download the latest release as archive or clone the repository and then start it:
`python3 ./wxglade.py`

**Comment by ardovm** [comment]
FWIW, issue reported to Ubuntu: https://bugs.launchpad.net/ubuntu/+source/wxglade/+bug/2145224
