### ISSUE TITLE
Pressing Enter in a custom widget's arguments text entry raises AttributeError

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#552]
* Open wxGlade
* Add a Frame
* Add a Custom Widget to the Frame
* With the Custom Widget selected, select its Widget tab in the Properties panel
* Click on the blank entry at the bottom of the Arguments list
* Click in the Arguments TextEntry field
* Type something in the field e.g. `style=wx.BORDER_NONE`
* Press the Enter key

The new argument is added to the Arguments list, but an Error Dialog is displayed:
```
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'AttributeError'>
Exception details:   'NoneType' object has no attribute 'finalize'

Application stack traceback:
  File "/usr/share/wxglade-1.1.0b1/new_properties.py", line 3101, in on_char_editor
    self._on_editor_edited(event, set_index=row)
  File "/usr/share/wxglade-1.1.0b1/new_properties.py", line 3066, in _on_editor_edited
    if self._on_value_edited(self.cur_row, col, value, set_index=set_index, delay=False):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/wxglade-1.1.0b1/new_properties.py", line 3008, in _on_value_edited
    common.history.property_changed(self)
  File "/usr/share/wxglade-1.1.0b1/history.py", line 468, in property_changed
    item = self._finalize_item()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/wxglade-1.1.0b1/history.py", line 457, in _finalize_item
    item.finalize(self._monitor)
    ^^^^^^^^^^^^^

Date and time:       2024-08-01T21:19:22.342145
Python version:      3.12.3
wxPython version:    4.2.1
wxWidgets platform:  __WXGTK__
wxGlade version:     1.1.0b1
```
The wxGlade installation was downloaded from https://github.com/wxGlade/wxGlade/releases/tag/v1.1.0b1

I also downloaded the zip file for the current master branch in GitHub and it gave the same error.

A workaround is to click on the 'Add' button instead of pressing the Enter key.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. I don't see this on Windows. I can check on Linux only next week.

fyi: the "Arguments Add / Insert / Remove" is to enable acessibility for visually impaired people who are using screen readers.
Did you actively enable it?

![grafik](https://github.com/user-attachments/assets/6a9e745f-c3d7-4698-bdd0-3ed93df60225)


Some time ago I submitted PRs for wxWidgets to improve accessibility. At some time in the future I should be able to remove these workarounds from wxGlade.

**Comment by reticulatus** [comment]
> fyi: the "Arguments Add / Insert / Remove" is to enable acessibility for visually impaired people who are using screen readers. Did you actively enable it?
> 
I think I saw the option mentioned sometime and enabled it to see what it did, but then forgot to disable it again!

**Comment by DietmarSchwertberger** [comment]
It should be fixed now in the repository. It seems there is an event EVT_KILL_FOCUS on GTK but not on Windows.

**Comment by reticulatus** [comment]
Confirmed - the error no longer occurs.
