### ISSUE TITLE
how to generate status lights?

### ISSUE THREAD

**Issue by TianchaoHuo** [wxGlade/wxGlade#553]
Hello , I am a beginner in developing wxglade. could you please give some suggestions how to generate status lights with three colors( red yellow green)?

![image](https://github.com/user-attachments/assets/96a0b512-a08d-4c08-9f29-2acc9d961508)

**Comment by DietmarSchwertberger** [comment]
You could use bitmap buttons and switch the bitmaps.
I would suggest to ask such questions on https://discuss.wxpython.org/
Github is more for bug reports.
