### ISSUE TITLE
Backslash in "Output path" gets doubled when followed by n or t

### ISSUE THREAD

**Issue by niun** [wxGlade/wxGlade#555]
wxGlade Version 1.1.0b1, Python 3.11.9, Windows 10.

When saving a wxGlade project with a windows path for the "Output path" setting, the backslashes (`\`) used as path delimiters are getting doubled when followed by a "n" or "t" character. For example the path

    C:\Users\niun\projects\tools

gets saved in the .wxg project file as

    C:\Users\\niun\projects\\tools

When loading and saving again, it becomes

    C:\Users\\\niun\projects\\\tools

I narrowed it down to the `TextProperty.getStringValue()` method in `new_properties.py` ([line 1311](https://github.com/wxGlade/wxGlade/blob/master/new_properties.py#L1311)) which was previously changed in https://github.com/wxGlade/wxGlade/commit/6b0a65826d3be3502a1e622eefd73dd55bcc029e seemingly to fix exactly this problem. But now undoing this change (also for "\n") fixes the problem for me.

So I changed

```python
return self.get_value().replace("\\n", "\\\\n").replace("\n", "\\n").replace("\\t","\\\\t").replace("\t", "\\t")
```
to
```python
return self.get_value().replace("\n", "\\n").replace("\t", "\\t")
```
which fixes the problem for me. I suspect that somehow changes in the python string handling are to blame here. Maybe `"\\n"` was not interpreted as the two bytes `<backslash><newline>` in some old python version but as `<backslash><backslash>n`? But my head hurts, ... too much backslashes and replacements... or is the xml writer doing something different now?

Maybe it would be a backwards compatible fix to "hide" the real backslashes before the replacement? Like
```python
BSMASK = "$$MyUnAmBiGuOuSeBsLaShMaSk$$"
value_with_hidden_backslashes = self.get_value().replace("\\", BSMASK)
escaped_value = value_with_hidden_backslashes.replace("\n", "\\n").replace("\t", "\\t")
return escaped_value.replace(BSMASK, "\\")
```

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting.
Saving was OK, but on loading the unescaping routine was not called.
It's now fixed in the repository.

The escaping is there to allow newlines and tabs in properties being written to the XML file as escaped strings.
A path can't have newlines, but e.g. a tooltip.
![grafik](https://github.com/user-attachments/assets/e547901a-4e60-40ea-8123-64a45f2e3c5c)
```
<tooltip>Tooltip\nwith newline</tooltip>
```

The alternative would have worked as well: don't escape output_path on saving, as it can't contain tabs and newlines.
