### ISSUE TITLE
Not starting on Linux Mint 22

### ISSUE THREAD

**Issue by adevoss** [wxGlade/wxGlade#556]
Fresh installed Mint 22.
Installed wxGlade (1.0.5+repack-2) via Synaptic.

Starting wxGlade via menu.
The icon is on the taskbar really short (less than half a second)
Then nothing.

**Comment by reticulatus** [comment]
What error messages do you get when you try to run it from a terminal?

**Comment by adevoss** [comment]
> diagnostics, but then outputs "Segmentation fault (core dumped)" and crashes.

Same here with v1.0.5+repack-2.

Cloned this repo and got v1.1.0b1.
Application starts.
