### ISSUE TITLE
(perl) StaticText generates wrong code if wrapping

### ISSUE THREAD

**Issue by sciurius** [wxGlade/wxGlade#557]
`widgets/static_text/perl_codegen.py` generates:

    my $label_3 = Wx::StaticText->new($self, ... )

When the 'wrap' attribute is used, this line is followed by

    my $label_3->Wrap(...);

This creates a new variable, shadowing the previous `$label_3`, with an initial undefined value, leading to a crash

    Can't call method "Wrap" on an undefined value

A workaround is to check 'Store as attribute' which forces the object name to become `$self->{label_3}`.

I'm not sure what would be the correct fix... Enforce `store_as_attr` when Wrap is checked? Or

````
*** widgets/static_text/perl_codegen.py~        2021-12-09 00:26:29.717772891 +0100
--- widgets/static_text/perl_codegen.py 2024-09-04 11:38:21.255087408 +0200
***************
*** 15,21 ****
      def get_more_properties_code(self, obj):
          ret = []
          if obj.wrap>0:
!             ret.append( '%s->Wrap(%d);\n'%(self.tmpl_dict['name'], obj.wrap) )
          return ret
  
  
--- 15,24 ----
      def get_more_properties_code(self, obj):
          ret = []
          if obj.wrap>0:
!             name = self.tmpl_dict['name']
!             if not self.tmpl_dict['store_as_attr']:
!                 name = name[3:] # strip 'my'
!             ret.append( '%s->Wrap(%d);\n'%(name, obj.wrap) )
          return ret
  
````

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. I should have used `self.format_widget_access(obj)` instead of `self.tmpl_dict['name']`.
It's fixed now in the repository.
