### ISSUE TITLE
Inconsistent use of 'colour'

### ISSUE THREAD

**Issue by sciurius** [wxGlade/wxGlade#561]
wxWidgets consistently uses 'Colour'. wxGlade mixes 'Colour' and 'Color' inconsistently.

![scrot20240912191824](https://github.com/user-attachments/assets/968c9318-a6b2-4476-a798-e8567a376d4f)

While this doesn't really matter for internal code (hint: use 'colr' ☺) at UX level it should be consistent.

(Note that I consitently typed 'consitent' and had to manually edit all occurrences.)

**Comment by DietmarSchwertberger** [comment]
Well, wxWidgets is also not 100% consistent: there is a stock item `wxID_SELECT_COLOR`.
Unfortunately wxGlade uses widget property names like grid's `line_color` which can't be changed easily.
But you're right, it should be changed where possible.

**Comment by DietmarSchwertberger** [comment]
I hope I did not introduce a bug...
