### ISSUE TITLE
CustomWidget gets wrong parent

### ISSUE THREAD

**Issue by sciurius** [wxGlade/wxGlade#562]
In this simple setup:
App > Frame > Panel > StaticBoxSizer
Add a TextCtrl and a CustomWidget to the StaticBoxSizer.

The TextCtrl gets the StaticBox of the StaticBoxSizer as parent, which is correct, but the CustomWidget gets the panel as parent.

````
        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "sizer_1"), wx.VERTICAL)

        self.text_ctrl_1 = wx.TextCtrl(sizer_1.GetStaticBox(), wx.ID_ANY, "")
        sizer_1.Add(self.text_ctrl_1, 0, 0, 0)

        self.window_1 = CustomWidget(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.window_1, 1, wx.EXPAND, 0)
````

[wxglade.wxg.txt](https://github.com/user-attachments/files/17131720/wxglade.wxg.txt)

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. It should work now.

**Comment by sciurius** [comment]
Looks good! Thanks.
